SOPT: /home/runner/work/sopt/sopt/cpp/benchmarks/wavelets.cc File Reference
wavelets.cc File Reference
#include <sstream>
#include <benchmark/benchmark.h>
#include "sopt/wavelets/wavelets.h"
Functions
unsigned get_size (unsigned requested, unsigned levels)
std::string get_name (unsigned db)
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1>
void direct_matrix (benchmark::State &state)
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1>
void indirect_matrix (benchmark::State &state)
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1>
void direct_vector (benchmark::State &state)
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1>
void indirect_vector (benchmark::State &state)
BENCHMARK_TEMPLATE (direct_matrix, sopt::t_complex, 1, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_matrix, sopt::t_real, 1, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_matrix, sopt::t_complex, 10, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_vector, sopt::t_complex, 1, 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_vector, sopt::t_complex, 10, 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_vector, sopt::t_complex, 1, 2) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (direct_vector, sopt::t_real, 1, 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_matrix, sopt::t_complex, 1, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_matrix, sopt::t_real, 1, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_matrix, sopt::t_complex, 10, 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_vector, sopt::t_complex, 1, 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_vector, sopt::t_complex, 10, 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_vector, sopt::t_complex, 1, 2) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE (indirect_vector, sopt::t_real, 1, 1) -> Range(n, N) ->UseRealTime()
Variables
const auto n = 64
const auto N = 256 * 3
Function Documentation
BENCHMARK_TEMPLATE() [1/14]
BENCHMARK_TEMPLATE (direct_matrix , sopt::t_complex , 1 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [2/14]
BENCHMARK_TEMPLATE (direct_matrix , sopt::t_complex , 10 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [3/14]
BENCHMARK_TEMPLATE (direct_matrix , sopt::t_real , 1 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [4/14]
BENCHMARK_TEMPLATE (direct_vector , sopt::t_complex , 1 , 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [5/14]
BENCHMARK_TEMPLATE (direct_vector , sopt::t_complex , 1 , 2) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [6/14]
BENCHMARK_TEMPLATE (direct_vector , sopt::t_complex , 10 , 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [7/14]
BENCHMARK_TEMPLATE (direct_vector , sopt::t_real , 1 , 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [8/14]
BENCHMARK_TEMPLATE (indirect_matrix , sopt::t_complex , 1 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [9/14]
BENCHMARK_TEMPLATE (indirect_matrix , sopt::t_complex , 10 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [10/14]
BENCHMARK_TEMPLATE (indirect_matrix , sopt::t_real , 1 , 1) -> RangePair(n, N, n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [11/14]
BENCHMARK_TEMPLATE (indirect_vector , sopt::t_complex , 1 , 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [12/14]
BENCHMARK_TEMPLATE (indirect_vector , sopt::t_complex , 1 , 2) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [13/14]
BENCHMARK_TEMPLATE (indirect_vector , sopt::t_complex , 10 , 1) -> Range(n, N) ->UseRealTime()
BENCHMARK_TEMPLATE() [14/14]
BENCHMARK_TEMPLATE (indirect_vector , sopt::t_real , 1 , 1) -> Range(n, N) ->UseRealTime()
direct_matrix()
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1> void direct_matrix (benchmark::State & state)
Definition at line 16 of file wavelets.cc.
{
   auto const Nx = get_size(state.range_x(), LEVEL);
   auto const Ny = get_size(state.range_y(), LEVEL);
   auto const input = sopt::Image<TYPE>::Random(Nx, Ny).eval();
   auto output = sopt::Image<TYPE>::Zero(Nx, Ny).eval();
   auto const wavelet = sopt::wavelets::factory(get_name(DB), LEVEL);
   while (state.KeepRunning()) wavelet.direct(output, input);
   state.SetBytesProcessed(int64_t(state.iterations()) * int64_t(Nx) * int64_t(Ny) * sizeof(TYPE));
 }
References sopt::wavelets::factory(), get_name(), and get_size().
direct_vector()
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1> void direct_vector (benchmark::State & state)
Definition at line 38 of file wavelets.cc.
{
   auto const Nx = get_size(state.range_x(), LEVEL);
   auto const input = sopt::Array<TYPE>::Random(Nx).eval();
   auto output = sopt::Array<TYPE>::Zero(Nx).eval();
   auto const wavelet = sopt::wavelets::factory(get_name(DB), LEVEL);
   while (state.KeepRunning()) wavelet.direct(output, input);
   state.SetBytesProcessed(int64_t(state.iterations()) * int64_t(Nx) * sizeof(TYPE));
 }
References sopt::wavelets::factory(), get_name(), and get_size().
get_name()
std::string get_name (unsigned db)
Definition at line 9 of file wavelets.cc.
{
   std::ostringstream sstr;
   sstr << "DB" << db;
   return sstr.str();
 }
Referenced by direct_matrix(), direct_vector(), indirect_matrix(), and indirect_vector().
get_size()
unsigned get_size (unsigned requested, unsigned levels)
Definition at line 5 of file wavelets.cc.
{
   auto const N = (1u << levels);
   return requested % N == 0 ? requested : requested + N - requested % N;
 }
References N.
Referenced by direct_matrix(), direct_vector(), indirect_matrix(), and indirect_vector().
indirect_matrix()
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1> void indirect_matrix (benchmark::State & state)
Definition at line 27 of file wavelets.cc.
{
   auto const Nx = get_size(state.range_x(), LEVEL);
   auto const Ny = get_size(state.range_y(), LEVEL);
   auto const input = sopt::Image<TYPE>::Random(Nx, Ny).eval();
   auto output = sopt::Image<TYPE>::Zero(Nx, Ny).eval();
   auto const wavelet = sopt::wavelets::factory(get_name(DB), LEVEL);
   while (state.KeepRunning()) wavelet.indirect(input, output);
   state.SetBytesProcessed(int64_t(state.iterations()) * int64_t(Nx) * int64_t(Ny) * sizeof(TYPE));
 }
References sopt::wavelets::factory(), get_name(), and get_size().
indirect_vector()
template<class TYPE , unsigned DB = 1, unsigned LEVEL = 1> void indirect_vector (benchmark::State & state)
Definition at line 47 of file wavelets.cc.
{
   auto const Nx = get_size(state.range_x(), LEVEL);
   auto const input = sopt::Array<TYPE>::Random(Nx).eval();
   auto output = sopt::Array<TYPE>::Zero(Nx).eval();
   auto const wavelet = sopt::wavelets::factory(get_name(DB), LEVEL);
   while (state.KeepRunning()) wavelet.indirect(input, output);
   state.SetBytesProcessed(int64_t(state.iterations()) * int64_t(Nx) * sizeof(TYPE));
 }
References sopt::wavelets::factory(), get_name(), and get_size().
Variable Documentation
n
const auto n = 64
Definition at line 56 of file wavelets.cc.
Referenced by sopt::wavelets::daubechies_data(), and TEST_CASE().
N
const auto N = 256 * 3
Definition at line 57 of file wavelets.cc.
Referenced by sopt::credible_region::compute_energy_upper_bound(), concatenated_permutations(), sopt::wavelets::direct_transform(), function_cg(), function_l1p(), get_size(), sopt::utilities::get_wavelet_high_pass_1d(), sopt::utilities::get_wavelet_levels_1d(), sopt::wavelets::indirect_transform(), main(), matrix_cg(), and TEST_CASE().