SOPT: sopt::algorithm::ImagingProximalADMM< SCALAR > Class Template Reference
sopt::algorithm::ImagingProximalADMM< SCALAR > Class Template Reference
#include <imaging_padmm.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef PADMM::value_type value_type
typedef PADMM::Scalar Scalar
typedef PADMM::Real Real
typedef PADMM::t_Vector t_Vector
typedef PADMM::t_LinearTransform t_LinearTransform
typedef PADMM::t_Proximal t_Proximal
typedef PADMM::t_IsConverged t_IsConverged
Public Member Functions
template<class DERIVED >
ImagingProximalADMM (Eigen::MatrixBase< DERIVED > const &target)
virtual ~ImagingProximalADMM ()
SOPT_MACRO (l1_proximal, proximal::L1< Scalar >)
Maximum number of iterations.
SOPT_MACRO (l2ball_proximal, proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO (tight_frame, bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (lagrange_update_scale, Real)
Lagrange update scale β
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
const t_Vector & target () const
Vector of target measurements.
template<class DERIVED >
ImagingProximalADMM< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Proximal ADMM.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Proximal ADMM.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() () const
Calls Proximal ADMM.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PADMM.
ImagingProximalADMM &::type Phi (ARGS &&... args)
proximal::L1< Scalar > & l1_proximal ()
L1 proximal used during calculation.
proximal::WeightedL2Ball< Scalar > & l2ball_proximal ()
Proximal of the L2 ball.
const t_LinearTransform & Psi () const
Analysis operator Ψ
ImagingProximalADMM< Scalar > &::type Psi (ARGS &&... args)
SOPT_MACRO (itermax, l1, L1)
SOPT_MACRO (tolerance, l1, L1)
SOPT_MACRO (positivity_constraint, l1, L1)
SOPT_MACRO (real_constraint, l1, L1)
SOPT_MACRO (fista_mixing, l1, L1)
SOPT_MACRO (nu, l1, L1)
SOPT_MACRO (weights, l1, L1)
SOPT_MACRO (epsilon, l2ball, WeightedL2Ball)
SOPT_MACRO (weights, l2ball, WeightedL2Ball)
ImagingProximalADMM< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingProximalADMM< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingProximalADMM< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
Detailed Description
template<class SCALAR>
class sopt::algorithm::ImagingProximalADMM< SCALAR >
Definition at line 20 of file imaging_padmm.h.
Member Typedef Documentation
Real
template<class SCALAR > typedef PADMM::Real sopt::algorithm::ImagingProximalADMM< SCALAR >::Real
Definition at line 27 of file imaging_padmm.h.
Scalar
template<class SCALAR > typedef PADMM::Scalar sopt::algorithm::ImagingProximalADMM< SCALAR >::Scalar
Definition at line 26 of file imaging_padmm.h.
t_IsConverged
template<class SCALAR > typedef PADMM::t_IsConverged sopt::algorithm::ImagingProximalADMM< SCALAR >::t_IsConverged
Definition at line 31 of file imaging_padmm.h.
t_LinearTransform
template<class SCALAR > typedef PADMM::t_LinearTransform sopt::algorithm::ImagingProximalADMM< SCALAR >::t_LinearTransform
Definition at line 29 of file imaging_padmm.h.
t_Proximal
template<class SCALAR > typedef PADMM::t_Proximal sopt::algorithm::ImagingProximalADMM< SCALAR >::t_Proximal
Definition at line 30 of file imaging_padmm.h.
t_Vector
template<class SCALAR > typedef PADMM::t_Vector sopt::algorithm::ImagingProximalADMM< SCALAR >::t_Vector
Definition at line 28 of file imaging_padmm.h.
value_type
template<class SCALAR > typedef PADMM::value_type sopt::algorithm::ImagingProximalADMM< SCALAR >::value_type
Definition at line 25 of file imaging_padmm.h.
Constructor & Destructor Documentation
ImagingProximalADMM()
template<class SCALAR > template<class DERIVED > sopt::algorithm::ImagingProximalADMM< SCALAR >::ImagingProximalADMM (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for ProximalADMM
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 55 of file imaging_padmm.h.
       : l1_proximal_(),
         l2ball_proximal_(1e0),
         tight_frame_(false),
         residual_tolerance_(1e-4),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         nu_(1),
         lagrange_update_scale_(0.9),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         target_(target) {}
~ImagingProximalADMM()
template<class SCALAR > virtual sopt::algorithm::ImagingProximalADMM< SCALAR >::~ImagingProximalADMM () inline virtual
Definition at line 70 of file imaging_padmm.h.
 {}
Member Function Documentation
is_converged()
template<class SCALAR > ImagingProximalADMM<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 239 of file imaging_padmm.h.
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
Referenced by TEST_CASE().
l1_proximal()
template<class SCALAR > proximal::L1<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::l1_proximal () inline
L1 proximal used during calculation.
Non-const version to setup the object.
Definition at line 182 of file imaging_padmm.h.
 { return l1_proximal_; }
Referenced by sopt::algorithm::ImagingProximalADMM< SCALAR >::Psi().
l2ball_proximal()
template<class SCALAR > proximal::WeightedL2Ball<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::l2ball_proximal () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 185 of file imaging_padmm.h.
 { return l2ball_proximal_; }
Referenced by TEST_CASE().
objective_convergence()
template<class SCALAR > ImagingProximalADMM<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 235 of file imaging_padmm.h.
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
operator()() [1/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() () const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 160 of file imaging_padmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x,
                                                    PADMM::initial_guess(target(), Phi(), nu()));
     return result;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), sopt::algorithm::ImagingProximalADMM< SCALAR >::Phi(), sopt::algorithm::ImagingProximalADMM< SCALAR >::target(), and sopt::algorithm::ImagingProximalADMM< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()().
operator()() [2/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PADMM.
Definition at line 167 of file imaging_padmm.h.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::Diagnostic::residual, and sopt::algorithm::ImagingProximalADMM< SCALAR >::DiagnosticAndResult::x.
operator()() [3/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 152 of file imaging_padmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::DiagnosticAndResult::x.
operator()() [4/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 147 of file imaging_padmm.h.
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()().
operator()() [5/7]
template<class SCALAR > Diagnostic sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (t_Vector & out) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
Definition at line 129 of file imaging_padmm.h.
{
     return operator()(out, PADMM::initial_guess(target(), Phi(), nu()));
   }
References sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()(), sopt::algorithm::ImagingProximalADMM< SCALAR >::Phi(), and sopt::algorithm::ImagingProximalADMM< SCALAR >::target().
operator()() [6/7]
template<class SCALAR > Diagnostic sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 141 of file imaging_padmm.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()().
operator()() [7/7]
template<class SCALAR > Diagnostic sopt::algorithm::ImagingProximalADMM< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 135 of file imaging_padmm.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()().
Phi()
template<class SCALAR > ImagingProximalADMM& ::type sopt::algorithm::ImagingProximalADMM< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 175 of file imaging_padmm.h.
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()(), and TEST_CASE().
Psi() [1/2]
template<class SCALAR > const t_LinearTransform& sopt::algorithm::ImagingProximalADMM< SCALAR >::Psi () const inline
Analysis operator Ψ
Under-the-hood, the object is actually owned by the L1 proximal.
Definition at line 189 of file imaging_padmm.h.
 { return l1_proximal().Psi(); }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::l1_proximal(), and sopt::proximal::L1< SCALAR >::Psi().
Referenced by TEST_CASE().
Psi() [2/2]
template<class SCALAR > ImagingProximalADMM<Scalar>& ::type sopt::algorithm::ImagingProximalADMM< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 192 of file imaging_padmm.h.
{
     l1_proximal().Psi(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::l1_proximal(), and sopt::proximal::L1< SCALAR >::Psi().
residual_convergence()
template<class SCALAR > ImagingProximalADMM<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 231 of file imaging_padmm.h.
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
Referenced by create_admm(), main(), and TEST_CASE().
SOPT_MACRO() [1/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (epsilon , l2ball , WeightedL2Ball)
SOPT_MACRO() [2/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (fista_mixing , l1 , L1)
SOPT_MACRO() [3/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [4/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [5/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (itermax , l1 , L1)
SOPT_MACRO() [6/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [7/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (l1_proximal , proximal::L1< Scalar >)
Maximum number of iterations.
SOPT_MACRO() [8/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (l2ball_proximal , proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO() [9/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (lagrange_update_scale , Real)
Lagrange update scale β
SOPT_MACRO() [10/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (nu , l1 , L1)
SOPT_MACRO() [11/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [12/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [13/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [14/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (positivity_constraint , l1 , L1)
SOPT_MACRO() [15/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (real_constraint , l1 , L1)
SOPT_MACRO() [16/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [17/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [18/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [19/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (tight_frame , bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO() [20/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (tolerance , l1 , L1)
SOPT_MACRO() [21/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (weights , l1 , L1)
SOPT_MACRO() [22/22]
template<class SCALAR > sopt::algorithm::ImagingProximalADMM< SCALAR >::SOPT_MACRO (weights , l2ball , WeightedL2Ball)
target() [1/2]
template<class SCALAR > const t_Vector& sopt::algorithm::ImagingProximalADMM< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 119 of file imaging_padmm.h.
 { return target_; }
Referenced by sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()(), sopt::algorithm::ImagingProximalADMM< SCALAR >::target(), and TEST_CASE().
target() [2/2]
template<class SCALAR > template<class DERIVED > ImagingProximalADMM<Scalar>& sopt::algorithm::ImagingProximalADMM< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 122 of file imaging_padmm.h.
{
     target_ = target;
     return *this;
   }
References sopt::algorithm::ImagingProximalADMM< SCALAR >::target().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/imaging_padmm.h