SOPT: sopt::algorithm::L2ForwardBackward< SCALAR > Class Template Reference
sopt::algorithm::L2ForwardBackward< SCALAR > Class Template Reference
#include <l2_forward_backward.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
using value_type = typename FB::value_type
using Scalar = typename FB::Scalar
using Real = typename FB::Real
using t_Vector = typename FB::t_Vector
using t_LinearTransform = typename FB::t_LinearTransform
template<typename T >
using t_Proximal = std::function< void(t_Vector &, const T &, const t_Vector &)>
using t_Gradient = typename FB::t_Gradient
using t_IsConverged = typename FB::t_IsConverged
Public Member Functions
template<typename DERIVED >
L2ForwardBackward (Eigen::MatrixBase< DERIVED > const &target)
virtual ~L2ForwardBackward ()
SOPT_MACRO (l2_proximal, t_Proximal< Real >)
l2 proximal for regularizaiton
SOPT_MACRO (l2_proximal_weighted, t_Proximal< Vector< Real >>)
l2 proximal for regularizaiton with weights
SOPT_MACRO (l2_proximal_weights, Vector< Real >)
l2 proximal weights
SOPT_MACRO (l2_gradient, t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO (tight_frame, bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (beta, Real)
γ parameter.
SOPT_MACRO (sigma, Real)
γ parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
t_Vector const & target () const
Vector of target measurements.
Real objmin () const
Minimun of objective_function.
template<typename DERIVED >
L2ForwardBackward< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() () const
Calls Forward Backward.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to FB.
L2ForwardBackward &::type Phi (ARGS &&... args)
t_Proximal< Real > & l2_proximal ()
L1 proximal used during calculation.
t_Proximal< Vector< Real > > & l2_proximal_weighted ()
t_Gradient & l2_gradient ()
Proximal of the L2 ball.
L2ForwardBackward< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
L2ForwardBackward< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
L2ForwardBackward< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
Detailed Description
template<typename SCALAR>
class sopt::algorithm::L2ForwardBackward< SCALAR >
Definition at line 24 of file l2_forward_backward.h.
Member Typedef Documentation
Real
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::Real = typename FB::Real
Definition at line 31 of file l2_forward_backward.h.
Scalar
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::Scalar = typename FB::Scalar
Definition at line 30 of file l2_forward_backward.h.
t_Gradient
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::t_Gradient = typename FB::t_Gradient
Definition at line 36 of file l2_forward_backward.h.
t_IsConverged
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::t_IsConverged = typename FB::t_IsConverged
Definition at line 37 of file l2_forward_backward.h.
t_LinearTransform
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::t_LinearTransform = typename FB::t_LinearTransform
Definition at line 33 of file l2_forward_backward.h.
t_Proximal
template<typename SCALAR > template<typename T > using sopt::algorithm::L2ForwardBackward< SCALAR >::t_Proximal = std::function<void(t_Vector &, const T &, const t_Vector &)>
Definition at line 35 of file l2_forward_backward.h.
t_Vector
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::t_Vector = typename FB::t_Vector
Definition at line 32 of file l2_forward_backward.h.
value_type
template<typename SCALAR > using sopt::algorithm::L2ForwardBackward< SCALAR >::value_type = typename FB::value_type
Definition at line 29 of file l2_forward_backward.h.
Constructor & Destructor Documentation
L2ForwardBackward()
template<typename SCALAR > template<typename DERIVED > sopt::algorithm::L2ForwardBackward< SCALAR >::L2ForwardBackward (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for ForwardBackward
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 55 of file l2_forward_backward.h.
       : l2_proximal_([](t_Vector &output, const t_real &gamma, const t_Vector &x) -> void {
           proximal::l2_norm(output, gamma, x);
         }),
         l2_proximal_weighted_(
             [](t_Vector &output, const Vector<Real> &gamma, const t_Vector &x) -> void {
               proximal::l2_norm(output, gamma, x);
             }),
         l2_proximal_weights_(Vector<Real>::Ones(1)),
         l2_gradient_([](t_Vector &output, const t_Vector &x) -> void {
           output = x;
         }),  // gradient of 1/2 * x^2 = x;
         tight_frame_(false),
         residual_tolerance_(0.),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         beta_(1),
         sigma_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         target_(target) {}
~L2ForwardBackward()
template<typename SCALAR > virtual sopt::algorithm::L2ForwardBackward< SCALAR >::~L2ForwardBackward () inline virtual
Definition at line 80 of file l2_forward_backward.h.
 {}
Member Function Documentation
is_converged()
template<typename SCALAR > L2ForwardBackward<Scalar>& sopt::algorithm::L2ForwardBackward< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 220 of file l2_forward_backward.h.
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
l2_gradient()
template<typename SCALAR > t_Gradient& sopt::algorithm::L2ForwardBackward< SCALAR >::l2_gradient () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 209 of file l2_forward_backward.h.
 { return l2_gradient_; }
l2_proximal()
template<typename SCALAR > t_Proximal<Real>& sopt::algorithm::L2ForwardBackward< SCALAR >::l2_proximal () inline
L1 proximal used during calculation.
Non-const version to setup the object.
Definition at line 205 of file l2_forward_backward.h.
 { return l2_proximal_; }
l2_proximal_weighted()
template<typename SCALAR > t_Proximal<Vector<Real> >& sopt::algorithm::L2ForwardBackward< SCALAR >::l2_proximal_weighted () inline
Definition at line 206 of file l2_forward_backward.h.
 { return l2_proximal_weighted_; }
objective_convergence()
template<typename SCALAR > L2ForwardBackward<Scalar>& sopt::algorithm::L2ForwardBackward< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 216 of file l2_forward_backward.h.
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
objmin()
template<typename SCALAR > Real sopt::algorithm::L2ForwardBackward< SCALAR >::objmin () const inline
Minimun of objective_function.
Definition at line 141 of file l2_forward_backward.h.
 { return objmin_; }
operator()() [1/7]
template<typename SCALAR > DiagnosticAndResult sopt::algorithm::L2ForwardBackward< SCALAR >::operator() () const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 182 of file l2_forward_backward.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(
         result.x, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
     return result;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), sopt::target(), and sopt::algorithm::L2ForwardBackward< SCALAR >::DiagnosticAndResult::x.
operator()() [2/7]
template<typename SCALAR > DiagnosticAndResult sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to FB.
Definition at line 189 of file l2_forward_backward.h.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, and sopt::algorithm::L2ForwardBackward< SCALAR >::DiagnosticAndResult::x.
operator()() [3/7]
template<typename SCALAR > DiagnosticAndResult sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 174 of file l2_forward_backward.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
References sopt::algorithm::L2ForwardBackward< SCALAR >::DiagnosticAndResult::x.
operator()() [4/7]
template<typename SCALAR > DiagnosticAndResult sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 169 of file l2_forward_backward.h.
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [5/7]
template<typename SCALAR > Diagnostic sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (t_Vector & out) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
Definition at line 151 of file l2_forward_backward.h.
{
     return operator()(out, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
   }
References sopt::target().
operator()() [6/7]
template<typename SCALAR > Diagnostic sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 163 of file l2_forward_backward.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [7/7]
template<typename SCALAR > Diagnostic sopt::algorithm::L2ForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 157 of file l2_forward_backward.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
Phi()
template<typename SCALAR > L2ForwardBackward& ::type sopt::algorithm::L2ForwardBackward< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 197 of file l2_forward_backward.h.
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by main().
residual_convergence()
template<typename SCALAR > L2ForwardBackward<Scalar>& sopt::algorithm::L2ForwardBackward< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 212 of file l2_forward_backward.h.
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
SOPT_MACRO() [1/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (beta , Real)
γ parameter.
SOPT_MACRO() [2/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [3/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [4/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [5/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (l2_gradient , t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO() [6/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal , t_Proximal< Real >)
l2 proximal for regularizaiton
SOPT_MACRO() [7/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal_weighted , t_Proximal< Vector< Real >>)
l2 proximal for regularizaiton with weights
SOPT_MACRO() [8/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal_weights , Vector< Real >)
l2 proximal weights
SOPT_MACRO() [9/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [10/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [11/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [12/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [13/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [14/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [15/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (sigma , Real)
γ parameter.
SOPT_MACRO() [16/16]
template<typename SCALAR > sopt::algorithm::L2ForwardBackward< SCALAR >::SOPT_MACRO (tight_frame , bool)
Whether Ψ is a tight-frame or not.
target() [1/2]
template<typename SCALAR > t_Vector const& sopt::algorithm::L2ForwardBackward< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 139 of file l2_forward_backward.h.
 { return target_; }
target() [2/2]
template<typename SCALAR > template<typename DERIVED > L2ForwardBackward<Scalar>& sopt::algorithm::L2ForwardBackward< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 144 of file l2_forward_backward.h.
{
     target_ = target;
     return *this;
   }
References sopt::target().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/l2_forward_backward.h