SOPT: sopt::RelativeVariation< TYPE > Class Template Reference
sopt::RelativeVariation< TYPE > Class Template Reference
#include <relative_variation.h>
Public Types
typedef TYPE Scalar
Underlying scalar type.
typedef real_type< Scalar >::type Real
Underlying scalar type.
Public Member Functions
RelativeVariation (Real tolerance=1e-12, std::string const &name="")
Maximum variation from one step to the next.
RelativeVariation (RelativeVariation const &c)
Copy constructor.
template<class T >
bool operator() (Eigen::MatrixBase< T > const &input)
True if object has changed by less than tolerance.
template<class T >
bool operator() (Eigen::ArrayBase< T > const &input)
True if object has changed by less than tolerance.
Real tolerance () const
Allowed variation.
RelativeVariation & tolerance (Real &e) const
Allowed variation.
std::string const & name () const
Name that gets interpolated into the log's output.
RelativeVariation const & name (std::string const &name) const
Detailed Description
template<class TYPE>
class sopt::RelativeVariation< TYPE >
Definition at line 13 of file relative_variation.h.
Member Typedef Documentation
Real
template<class TYPE> typedef real_type<Scalar>::type sopt::RelativeVariation< TYPE >::Real
Underlying scalar type.
Definition at line 18 of file relative_variation.h.
Scalar
template<class TYPE> typedef TYPE sopt::RelativeVariation< TYPE >::Scalar
Underlying scalar type.
Definition at line 16 of file relative_variation.h.
Constructor & Destructor Documentation
RelativeVariation() [1/2]
template<class TYPE> sopt::RelativeVariation< TYPE >::RelativeVariation (Real tolerance = 1e-12, std::string const & name = "") inline
Maximum variation from one step to the next.
Definition at line 20 of file relative_variation.h.
       : tolerance_(tolerance), previous_(typename Array<Scalar>::Index(0)), name_(name){};
RelativeVariation() [2/2]
template<class TYPE> sopt::RelativeVariation< TYPE >::RelativeVariation (RelativeVariation< TYPE > const & c) inline
Copy constructor.
Definition at line 23 of file relative_variation.h.
       : tolerance_(c.tolerance_), previous_(c.previous_){};
Member Function Documentation
name() [1/2]
template<class TYPE> std::string const& sopt::RelativeVariation< TYPE >::name () const inline
Name that gets interpolated into the log's output.
Definition at line 42 of file relative_variation.h.
Referenced by sopt::RelativeVariation< TYPE >::name(), sopt::ScalarRelativeVariation< TYPE >::name(), sopt::RelativeVariation< TYPE >::operator()(), and sopt::ScalarRelativeVariation< TYPE >::operator()().
 { return name_; }
name() [2/2]
template<class TYPE> RelativeVariation const& sopt::RelativeVariation< TYPE >::name (std::string const & name) const inline
Definition at line 43 of file relative_variation.h.
References sopt::RelativeVariation< TYPE >::name().
{
     name_ = name;
     return *this;
   }
operator()() [1/2]
template<class TYPE> template<class T > bool sopt::RelativeVariation< TYPE >::operator() (Eigen::MatrixBase< T > const & input) inline
True if object has changed by less than tolerance.
Definition at line 28 of file relative_variation.h.
Referenced by sopt::ScalarRelativeVariation< TYPE >::ScalarRelativeVariation().
{
     return operator()(input.array());
   }
operator()() [2/2]
template<class SCALAR > template<class T > bool sopt::RelativeVariation< SCALAR >::operator() (Eigen::ArrayBase< T > const & input)
True if object has changed by less than tolerance.
Definition at line 112 of file relative_variation.h.
References sopt::RelativeVariation< TYPE >::name(), SOPT_LOW_LOG, and sopt::RelativeVariation< TYPE >::tolerance().
{
   if (previous_.size() != input.size()) {
     previous_ = input;
     return false;
   }
   auto const norm = (input - previous_).matrix().squaredNorm();
   previous_ = input;
   SOPT_LOW_LOG("    - {} relative variation: {} <? {}", name(), std::sqrt(norm), tolerance());
   return norm < tolerance() * tolerance();
 }
tolerance() [1/2]
template<class TYPE> Real sopt::RelativeVariation< TYPE >::tolerance () const inline
Allowed variation.
Definition at line 35 of file relative_variation.h.
Referenced by sopt::RelativeVariation< TYPE >::operator()(), and TEST_CASE().
 { return tolerance_; }
tolerance() [2/2]
template<class TYPE> RelativeVariation& sopt::RelativeVariation< TYPE >::tolerance (Real & e) const inline
Allowed variation.
Definition at line 37 of file relative_variation.h.
{
     tolerance_ = e;
     return *this;
   }
The documentation for this class was generated from the following file:
/mydata/cpp/sopt/relative_variation.h