SOPT: sopt::details::WrapFunction< VECTOR > Class Template Reference
sopt::details::WrapFunction< VECTOR > Class Template Reference
Wraps an std::function to return an expression.
#include <wrapper.h>
Public Types
using t_Function = OperatorFunction< VECTOR >
Type of function wrapped here.
Public Member Functions
WrapFunction (t_Function const &func, std::array< t_int, 3 > sizes={{1, 1, 0}})
WrapFunction (WrapFunction const &c)
WrapFunction (WrapFunction const &&c)
void operator= (WrapFunction const &c)
void operator= (WrapFunction &&c)
template<class T0 >
AppliedFunction< t_Function const &, Eigen::ArrayBase< T0 > > operator() (Eigen::ArrayBase< T0 > const &x) const
Function application form.
template<class T0 >
AppliedFunction< t_Function const &, Eigen::ArrayBase< T0 > > operator* (Eigen::ArrayBase< T0 > const &x) const
Multiplication application form.
template<class T0 >
AppliedFunction< t_Function const &, Eigen::MatrixBase< T0 > > operator() (Eigen::MatrixBase< T0 > const &x) const
Function application form.
template<class T0 >
AppliedFunction< t_Function const &, Eigen::MatrixBase< T0 > > operator* (Eigen::MatrixBase< T0 > const &x) const
Multiplication application form.
const std::array< t_int, 3 > & sizes () const
Defines relation-ship between input and output sizes.
template<class T >
std::enable_if< std::is_integral< T >::value, T >::type rows (T xsize) const
Output vector size for a input with xsize elements.
Detailed Description
template<class VECTOR>
class sopt::details::WrapFunction< VECTOR >
Wraps an std::function to return an expression.
This makes writing the application of a function more beautiful on the eye. A function call func(output, input) can be made to look like output = func(input) or output = func * input.
Definition at line 45 of file wrapper.h.
Member Typedef Documentation
t_Function
template<class VECTOR > using sopt::details::WrapFunction< VECTOR >::t_Function = OperatorFunction<VECTOR>
Type of function wrapped here.
Definition at line 48 of file wrapper.h.
Constructor & Destructor Documentation
WrapFunction() [1/3]
template<class VECTOR > sopt::details::WrapFunction< VECTOR >::WrapFunction (t_Function const & func, std::array< t_int, 3 > sizes = {{1, 1, 0}}) inline
Initializes the wrapper
Parameters
[in] func function to wrap
[in] sizes three integer vector (a, b, c) if N is the size of the input, then (N * a) / b + c is the output b cannot be zero.
Definition at line 55 of file wrapper.h.
                                                                   {{1, 1, 0}})
       : func(func), sizes_(sizes) {
     // cannot devide by zero
     assert(sizes_[1] != 0);
   }
WrapFunction() [2/3]
template<class VECTOR > sopt::details::WrapFunction< VECTOR >::WrapFunction (WrapFunction< VECTOR > const & c) inline
Definition at line 60 of file wrapper.h.
 : func(c.func), sizes_(c.sizes_) {}
WrapFunction() [3/3]
template<class VECTOR > sopt::details::WrapFunction< VECTOR >::WrapFunction (WrapFunction< VECTOR > const && c) inline
Definition at line 61 of file wrapper.h.
 : func(std::move(c.func)), sizes_(std::move(c.sizes_)) {}
Member Function Documentation
operator()() [1/2]
template<class VECTOR > template<class T0 > AppliedFunction<t_Function const &, Eigen::ArrayBase<T0> > sopt::details::WrapFunction< VECTOR >::operator() (Eigen::ArrayBase< T0 > const & x) const inline
Function application form.
Definition at line 73 of file wrapper.h.
{
     return AppliedFunction<t_Function const &, Eigen::ArrayBase<T0>>(func, x, rows(x));
   }
operator()() [2/2]
template<class VECTOR > template<class T0 > AppliedFunction<t_Function const &, Eigen::MatrixBase<T0> > sopt::details::WrapFunction< VECTOR >::operator() (Eigen::MatrixBase< T0 > const & x) const inline
Function application form.
Definition at line 87 of file wrapper.h.
{
     return AppliedFunction<t_Function const &, Eigen::MatrixBase<T0>>(func, x, rows(x));
   }
operator*() [1/2]
template<class VECTOR > template<class T0 > AppliedFunction<t_Function const &, Eigen::ArrayBase<T0> > sopt::details::WrapFunction< VECTOR >::operator* (Eigen::ArrayBase< T0 > const & x) const inline
Multiplication application form.
Definition at line 80 of file wrapper.h.
{
     return AppliedFunction<t_Function const &, Eigen::ArrayBase<T0>>(func, x, rows(x));
   }
operator*() [2/2]
template<class VECTOR > template<class T0 > AppliedFunction<t_Function const &, Eigen::MatrixBase<T0> > sopt::details::WrapFunction< VECTOR >::operator* (Eigen::MatrixBase< T0 > const & x) const inline
Multiplication application form.
Definition at line 94 of file wrapper.h.
{
     return AppliedFunction<t_Function const &, Eigen::MatrixBase<T0>>(func, x, rows(x));
   }
operator=() [1/2]
template<class VECTOR > void sopt::details::WrapFunction< VECTOR >::operator= (WrapFunction< VECTOR > && c) inline
Definition at line 66 of file wrapper.h.
{
     func = std::move(c.func);
     sizes_ = std::move(c.sizes_);
   }
operator=() [2/2]
template<class VECTOR > void sopt::details::WrapFunction< VECTOR >::operator= (WrapFunction< VECTOR > const & c) inline
Definition at line 62 of file wrapper.h.
{
     func = c.func;
     sizes_ = c.sizes_;
   }
Referenced by sopt::LinearTransform< t_Vector >::operator=().
rows()
template<class VECTOR > template<class T > std::enable_if<std::is_integral<T>::value, T>::type sopt::details::WrapFunction< VECTOR >::rows (T xsize) const inline
Output vector size for a input with xsize elements.
Definition at line 109 of file wrapper.h.
{
     auto const result = (static_cast<t_int>(xsize) * sizes_[0]) / sizes_[1] + sizes_[2];
     assert(result >= 0);
     return static_cast<T>(result);
   }
Referenced by sopt::details::WrapFunction< t_Vector >::operator()(), and sopt::details::WrapFunction< t_Vector >::operator*().
sizes()
template<class VECTOR > const std::array<t_int, 3>& sopt::details::WrapFunction< VECTOR >::sizes () const inline
Defines relation-ship between input and output sizes.
An integer tuple (a, b, c) where, if N is the size of the input, then \((N * a) / b + c\) is the output. \(b\) cannot be zero. In the simplest case where this objects wraps a square matrix, then the sizes are (1, 1, 0). If this objects wraps a rectangular matrix which halves the number of elements, then the sizes would be (1, 2, 0).
Definition at line 105 of file wrapper.h.
 { return sizes_; }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/wrapper.h