SOPT: sopt::algorithm::ProximalADMM< SCALAR > Class Template Reference
sopt::algorithm::ProximalADMM< SCALAR > Class Template Reference
Proximal Alternate Direction method of mutltipliers.
#include <padmm.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
using value_type = SCALAR
Scalar type.
using Scalar = value_type
Scalar type.
using Real = typename real_type< Scalar >::type
Real type.
using t_Vector = Vector< Scalar >
Type of then underlying vectors.
using t_LinearTransform = LinearTransform< t_Vector >
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
using t_IsConverged = std::function< bool(const t_Vector &, const t_Vector &)>
Type of the convergence function.
using t_Proximal = ProximalFunction< Scalar >
Type of the convergence function.
Public Member Functions
template<class DERIVED >
ProximalADMM (t_Proximal const &f_proximal, t_Proximal const &g_proximal, Eigen::MatrixBase< DERIVED > const &target)
virtual ~ProximalADMM ()
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (lagrange_update_scale, Real)
Lagrange update scale β
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (f_proximal, t_Proximal)
First proximal.
SOPT_MACRO (g_proximal, t_Proximal)
Second proximal.
void f_proximal (t_Vector &out, Real gamma, t_Vector const &x) const
Simplifies calling the proximal of f.
void g_proximal (t_Vector &out, Real gamma, t_Vector const &x) const
Simplifies calling the proximal of f.
ProximalADMM< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
const t_Vector & target () const
Vector of target measurements.
template<class DERIVED >
ProximalADMM< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
bool is_converged (t_Vector const &x, t_Vector const &residual) const
Facilitates call to user-provided convergence function.
Diagnostic operator() (t_Vector &out) const
Calls Proximal ADMM.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Proximal ADMM.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Proximal ADMM.
DiagnosticAndResult operator() () const
Calls Proximal ADMM.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PADMM.
ProximalADMM &::type Phi (ARGS &&... args)
std::tuple< t_Vector, t_Vector > initial_guess () const
Computes initial guess for x and the residual using the targets.
Static Public Member Functions
static std::tuple< t_Vector, t_Vector > initial_guess (t_Vector const &target, t_LinearTransform const &phi, Real nu)
Computes initial guess for x and the residual using the targets.
Detailed Description
template<class SCALAR>
class sopt::algorithm::ProximalADMM< SCALAR >
Proximal Alternate Direction method of mutltipliers.
\(\min_{x, z} f(x) + h(z)\) subject to \(Φx + z = y\). \(y\) is a target vector.
Definition at line 17 of file padmm.h.
Member Typedef Documentation
Real
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::Real = typename real_type<Scalar>::type
Real type.
Definition at line 24 of file padmm.h.
Scalar
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::Scalar = value_type
Scalar type.
Definition at line 22 of file padmm.h.
t_IsConverged
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::t_IsConverged = std::function<bool (const t_Vector &, const t_Vector &)>
Type of the convergence function.
Definition at line 30 of file padmm.h.
t_LinearTransform
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::t_LinearTransform = LinearTransform<t_Vector>
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
Definition at line 28 of file padmm.h.
t_Proximal
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::t_Proximal = ProximalFunction<Scalar>
Type of the convergence function.
Definition at line 32 of file padmm.h.
t_Vector
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::t_Vector = Vector<Scalar>
Type of then underlying vectors.
Definition at line 26 of file padmm.h.
value_type
template<class SCALAR > using sopt::algorithm::ProximalADMM< SCALAR >::value_type = SCALAR
Scalar type.
Definition at line 20 of file padmm.h.
Constructor & Destructor Documentation
ProximalADMM()
template<class SCALAR > template<class DERIVED > sopt::algorithm::ProximalADMM< SCALAR >::ProximalADMM (t_Proximal const & f_proximal, t_Proximal const & g_proximal, Eigen::MatrixBase< DERIVED > const & target) inline
Setups ProximalADMM
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 58 of file padmm.h.
       : itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         nu_(1),
         lagrange_update_scale_(0.9),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         f_proximal_(f_proximal),
         g_proximal_(g_proximal),
         target_(target) {}
~ProximalADMM()
template<class SCALAR > virtual sopt::algorithm::ProximalADMM< SCALAR >::~ProximalADMM () inline virtual
Definition at line 69 of file padmm.h.
 {}
Member Function Documentation
f_proximal()
template<class SCALAR > void sopt::algorithm::ProximalADMM< SCALAR >::f_proximal (t_Vector & out, Real gamma, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 104 of file padmm.h.
{
     f_proximal()(out, gamma, x);
   }
g_proximal()
template<class SCALAR > void sopt::algorithm::ProximalADMM< SCALAR >::g_proximal (t_Vector & out, Real gamma, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 108 of file padmm.h.
{
     g_proximal()(out, gamma, x);
   }
initial_guess() [1/2]
template<class SCALAR > std::tuple<t_Vector, t_Vector> sopt::algorithm::ProximalADMM< SCALAR >::initial_guess () const inline
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
Definition at line 184 of file padmm.h.
{
     return ProximalADMM<SCALAR>::initial_guess(target(), Phi(), nu());
   }
References sopt::algorithm::ProximalADMM< SCALAR >::Phi(), and sopt::algorithm::ProximalADMM< SCALAR >::target().
Referenced by sopt::algorithm::ImagingProximalADMM< SCALAR >::operator()(), and sopt::algorithm::ProximalADMM< SCALAR >::operator()().
initial_guess() [2/2]
template<class SCALAR > static std::tuple<t_Vector, t_Vector> sopt::algorithm::ProximalADMM< SCALAR >::initial_guess (t_Vector const & target, t_LinearTransform const & phi, Real nu) inline static
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
This function simplifies creating overloads for operator() in PADMM wrappers.
Definition at line 194 of file padmm.h.
{
     std::tuple<t_Vector, t_Vector> guess;
     std::get<0>(guess) = static_cast<t_Vector>(phi.adjoint() * target) / nu;
     std::get<1>(guess) = phi * std::get<0>(guess) - target;
     return guess;
   }
References sopt::LinearTransform< VECTOR >::adjoint(), and sopt::algorithm::ProximalADMM< SCALAR >::target().
is_converged() [1/2]
template<class SCALAR > ProximalADMM<Scalar>& sopt::algorithm::ProximalADMM< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 113 of file padmm.h.
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
Referenced by sopt::algorithm::ProximalADMM< SCALAR >::is_converged(), main(), and SCENARIO().
is_converged() [2/2]
template<class SCALAR > bool sopt::algorithm::ProximalADMM< SCALAR >::is_converged (t_Vector const & x, t_Vector const & residual) const inline
Facilitates call to user-provided convergence function.
Definition at line 127 of file padmm.h.
{
     return static_cast<bool>(is_converged()) and is_converged()(x, residual);
   }
References sopt::algorithm::ProximalADMM< SCALAR >::is_converged().
operator()() [1/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ProximalADMM< SCALAR >::operator() () const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 162 of file padmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, initial_guess());
     return result;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), and sopt::algorithm::ProximalADMM< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::ProximalADMM< SCALAR >::operator()().
operator()() [2/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ProximalADMM< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PADMM.
Definition at line 168 of file padmm.h.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::Diagnostic::residual, and sopt::algorithm::ProximalADMM< SCALAR >::DiagnosticAndResult::x.
operator()() [3/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ProximalADMM< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 154 of file padmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::DiagnosticAndResult::x.
operator()() [4/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ProximalADMM< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Proximal ADMM.
Parameters
[in] guess initial guess
Definition at line 149 of file padmm.h.
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
References sopt::algorithm::ProximalADMM< SCALAR >::operator()().
operator()() [5/7]
template<class SCALAR > Diagnostic sopt::algorithm::ProximalADMM< SCALAR >::operator() (t_Vector & out) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
Definition at line 133 of file padmm.h.
 { return operator()(out, initial_guess()); }
References sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), and sopt::algorithm::ProximalADMM< SCALAR >::operator()().
Referenced by sopt::algorithm::ProximalADMM< SCALAR >::operator()().
operator()() [6/7]
template<class SCALAR > Diagnostic sopt::algorithm::ProximalADMM< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 143 of file padmm.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ProximalADMM< SCALAR >::operator()().
operator()() [7/7]
template<class SCALAR > Diagnostic sopt::algorithm::ProximalADMM< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Proximal ADMM.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 137 of file padmm.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ProximalADMM< SCALAR >::operator()().
Phi()
template<class SCALAR > ProximalADMM& ::type sopt::algorithm::ProximalADMM< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 175 of file padmm.h.
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), SCENARIO(), and TEST_CASE().
SOPT_MACRO() [1/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (f_proximal , t_Proximal)
First proximal.
SOPT_MACRO() [2/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (g_proximal , t_Proximal)
Second proximal.
SOPT_MACRO() [3/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [4/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
It takes as input two arguments: the current solution x and the current residual.
SOPT_MACRO() [5/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [6/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (lagrange_update_scale , Real)
Lagrange update scale β
SOPT_MACRO() [7/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [8/8]
template<class SCALAR > sopt::algorithm::ProximalADMM< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
target() [1/2]
template<class SCALAR > const t_Vector& sopt::algorithm::ProximalADMM< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 118 of file padmm.h.
 { return target_; }
Referenced by sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), and sopt::algorithm::ProximalADMM< SCALAR >::target().
target() [2/2]
template<class SCALAR > template<class DERIVED > ProximalADMM<Scalar>& sopt::algorithm::ProximalADMM< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 121 of file padmm.h.
{
     target_ = target;
     return *this;
   }
References sopt::algorithm::ProximalADMM< SCALAR >::target().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/padmm.h