SOPT: sopt::ONNXDifferentiableFunc< SCALAR > Class Template Reference
sopt::ONNXDifferentiableFunc< SCALAR > Class Template Reference
#include <onnx_differentiable_func.h>
Public Member Functions
ONNXDifferentiableFunc (const std::string &function_model_path, const std::string &gradient_model_path, const Real sigma, const Real mu, const Real lambda, const LinearTransform &Phi, const std::vector< int64_t > dimensions={})
void log_message () const override
void gradient (Vector &output, const Vector &image, const Vector &residual, const LinearTransform &Phi) override
void infer_dimensions (const size_t image_size)
void set_dimensions (const std::vector< int64_t > &dims)
Real function (Vector const &image, Vector const &y, LinearTransform const &Phi) override
Public Member Functions inherited from DifferentiableFunc< SCALAR >
virtual t_Gradient gradient ()
Additional Inherited Members
Public Types inherited from DifferentiableFunc< SCALAR >
using FB = sopt::algorithm::ForwardBackward< SCALAR >
using Real = typename FB::Real
using t_Vector = typename FB::t_Vector
using t_Gradient = typename FB::t_Gradient
using t_LinearTransform = typename FB::t_LinearTransform
Detailed Description
template<typename SCALAR>
class sopt::ONNXDifferentiableFunc< SCALAR >
Definition at line 54 of file onnx_differentiable_func.h.
Constructor & Destructor Documentation
ONNXDifferentiableFunc()
template<typename SCALAR > sopt::ONNXDifferentiableFunc< SCALAR >::ONNXDifferentiableFunc (const std::string & function_model_path, const std::string & gradient_model_path, const Real sigma, const Real mu, const Real lambda, const LinearTransform & Phi, const std::vector< int64_t > dimensions = {}) inline
Definition at line 62 of file onnx_differentiable_func.h.
                                                                  {}): LT(Phi), sigma(sigma), mu(mu), lambda(lambda),
                                                               function_model(function_model_path),
                                                               gradient_model(gradient_model_path)
     {
         if(dimensions.empty()) infer_square_dimensions = true;
     }
Member Function Documentation
function()
template<typename SCALAR > Real sopt::ONNXDifferentiableFunc< SCALAR >::function (Vector const & image, Vector const & y, LinearTransform const & Phi) inline override virtual
Implements DifferentiableFunc< SCALAR >.
Definition at line 107 of file onnx_differentiable_func.h.
     {
         if(infer_square_dimensions) infer_dimensions(image.size());
         // Does this need to be modified to take into account MPI?
         Real Likelihood = 0.5 * ((Phi*image) - y).squaredNorm() / (sigma * sigma);
         Vector scaled_image = image * mu;
         std::vector<float> float_image = imageToFloat(scaled_image);
         Real Prior = (lambda / mu) * (function_model.compute(float_image, dimensions)[0]); // Is this correct?
         return Likelihood + Prior;
     }
References sopt::ORTsession::compute(), sopt::imageToFloat(), sopt::ONNXDifferentiableFunc< SCALAR >::infer_dimensions(), and sopt::sigma().
gradient()
template<typename SCALAR > void sopt::ONNXDifferentiableFunc< SCALAR >::gradient (Vector & output, const Vector & image, const Vector & residual, const LinearTransform & Phi) inline override virtual
Implements DifferentiableFunc< SCALAR >.
Definition at line 80 of file onnx_differentiable_func.h.
     {
       if(infer_square_dimensions) infer_dimensions(image.size());
       output = Phi.adjoint() * (residual / (sigma * sigma));  // L2 norm
       Vector scaled_image = image * mu;
       std::vector<float> float_image = imageToFloat(scaled_image);
       Vector ANN_gradient = floatToImage<SCALAR>(gradient_model.compute(float_image, dimensions));  // regulariser
       output += (ANN_gradient * lambda);
     }
References sopt::ORTsession::compute(), sopt::imageToFloat(), sopt::ONNXDifferentiableFunc< SCALAR >::infer_dimensions(), and sopt::sigma().
infer_dimensions()
template<typename SCALAR > void sopt::ONNXDifferentiableFunc< SCALAR >::infer_dimensions (const size_t image_size) inline
Definition at line 92 of file onnx_differentiable_func.h.
     {
         set_dimensions({1, static_cast<int64_t>(sqrt(image_size)), static_cast<int64_t>(sqrt(image_size))});
         if(dimensions[1] * dimensions[2] != image_size)
         {
           throw std::runtime_error("Image dimensions are not provided and image size is not compatible with a square image.");
         }
         infer_square_dimensions = false;
     }
References sopt::ONNXDifferentiableFunc< SCALAR >::set_dimensions().
Referenced by sopt::ONNXDifferentiableFunc< SCALAR >::function(), and sopt::ONNXDifferentiableFunc< SCALAR >::gradient().
log_message()
template<typename SCALAR > void sopt::ONNXDifferentiableFunc< SCALAR >::log_message () const inline override virtual
Implements DifferentiableFunc< SCALAR >.
Definition at line 75 of file onnx_differentiable_func.h.
     {
         SOPT_HIGH_LOG("Using ONNX model differentiable function f(x)");
     }
References SOPT_HIGH_LOG.
set_dimensions()
template<typename SCALAR > void sopt::ONNXDifferentiableFunc< SCALAR >::set_dimensions (const std::vector< int64_t > & dims) inline
Definition at line 102 of file onnx_differentiable_func.h.
     {
         dimensions = dims;
     }
Referenced by sopt::ONNXDifferentiableFunc< SCALAR >::infer_dimensions().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/onnx_differentiable_func.h