SOPT: sopt::proximal::WeightedL2Ball< T > Class Template Reference
sopt::proximal::WeightedL2Ball< T > Class Template Reference
#include <proximal.h>
Public Types
typedef L2Ball< T >::Real Real
typedef Vector< Real > t_Vector
Public Types inherited from sopt::proximal::L2Ball< T >
typedef real_type< T >::type Real
Public Member Functions
template<class T0 >
WeightedL2Ball (Real epsilon, Eigen::DenseBase< T0 > const &w)
Constructs an L2 ball proximal of size epsilon with given weights.
WeightedL2Ball (Real epsilon)
Constructs an L2 ball proximal of size epsilon.
void operator() (Vector< T > &out, typename real_type< T >::type, Vector< T > const &x) const
Calls proximal function.
void operator() (Vector< T > &out, Vector< T > const &x) const
Calls proximal function.
template<class T0 >
EnveloppeExpression< WeightedL2Ball, T0 > operator() (Real const &, Eigen::MatrixBase< T0 > const &x) const
Lazy version.
template<class T0 >
EnveloppeExpression< WeightedL2Ball, T0 > operator() (Eigen::MatrixBase< T0 > const &x) const
Lazy version.
const t_Vector & weights () const
Weights associated with each dimension.
template<class T0 >
WeightedL2Ball< T > & weights (Eigen::MatrixBase< T0 > const &w)
Weights associated with each dimension.
Real epsilon () const
Size of the ball.
WeightedL2Ball< T > & epsilon (Real const &eps)
Size of the ball.
Public Member Functions inherited from sopt::proximal::L2Ball< T >
L2Ball (Real epsilon)
Constructs an L2 ball proximal of size epsilon.
void operator() (Vector< T > &out, typename real_type< T >::type, Vector< T > const &x) const
Calls proximal function.
void operator() (Vector< T > &out, Vector< T > const &x) const
Calls proximal function.
template<class T0 >
EnveloppeExpression< L2Ball, T0 > operator() (Real const &, Eigen::MatrixBase< T0 > const &x) const
Lazy version.
template<class T0 >
EnveloppeExpression< L2Ball, T0 > operator() (Eigen::MatrixBase< T0 > const &x) const
Lazy version.
Real epsilon () const
Size of the ball.
L2Ball< T > & epsilon (Real eps)
Size of the ball.
Detailed Description
template<class T>
class sopt::proximal::WeightedL2Ball< T >
Definition at line 246 of file proximal.h.
Member Typedef Documentation
Real
template<class T > typedef L2Ball<T>::Real sopt::proximal::WeightedL2Ball< T >::Real
Definition at line 248 of file proximal.h.
t_Vector
template<class T > typedef Vector<Real> sopt::proximal::WeightedL2Ball< T >::t_Vector
Definition at line 249 of file proximal.h.
Constructor & Destructor Documentation
WeightedL2Ball() [1/2]
template<class T > template<class T0 > sopt::proximal::WeightedL2Ball< T >::WeightedL2Ball (Real epsilon, Eigen::DenseBase< T0 > const & w) inline
Constructs an L2 ball proximal of size epsilon with given weights.
Definition at line 267 of file proximal.h.
 : L2Ball<T>(epsilon), weights_(w) {}
WeightedL2Ball() [2/2]
template<class T > sopt::proximal::WeightedL2Ball< T >::WeightedL2Ball (Real epsilon) inline
Constructs an L2 ball proximal of size epsilon.
Definition at line 269 of file proximal.h.
 : WeightedL2Ball(epsilon, t_Vector::Ones(1)) {}
Member Function Documentation
epsilon() [1/2]
template<class T > Real sopt::proximal::WeightedL2Ball< T >::epsilon () const inline
Size of the ball.
Definition at line 312 of file proximal.h.
 { return L2Ball<T>::epsilon(); }
References sopt::proximal::L2Ball< T >::epsilon().
Referenced by sopt::proximal::WeightedL2Ball< T >::operator()(), and TEST_CASE().
epsilon() [2/2]
template<class T > WeightedL2Ball<T>& sopt::proximal::WeightedL2Ball< T >::epsilon (Real const & eps) inline
Size of the ball.
Definition at line 314 of file proximal.h.
{
     L2Ball<T>::epsilon(eps);
     return *this;
   }
References sopt::proximal::L2Ball< T >::epsilon().
operator()() [1/4]
template<class T > template<class T0 > EnveloppeExpression<WeightedL2Ball, T0> sopt::proximal::WeightedL2Ball< T >::operator() (Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 297 of file proximal.h.
{
     return {*this, x};
   }
operator()() [2/4]
template<class T > template<class T0 > EnveloppeExpression<WeightedL2Ball, T0> sopt::proximal::WeightedL2Ball< T >::operator() (Real const & , Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 291 of file proximal.h.
{
     return {*this, x};
   }
operator()() [3/4]
template<class T > void sopt::proximal::WeightedL2Ball< T >::operator() (Vector< T > & out, typename real_type< T >::type , Vector< T > const & x) const inline
Calls proximal function.
Definition at line 273 of file proximal.h.
{
     return operator()(out, x);
   }
operator()() [4/4]
template<class T > void sopt::proximal::WeightedL2Ball< T >::operator() (Vector< T > & out, Vector< T > const & x) const inline
Calls proximal function.
Definition at line 277 of file proximal.h.
{
 #ifdef SOPT_MPI
     auto const norm = mpi::l2_norm(x.array(), weights().array(), communicator());
 #else
     auto const norm = weights().size() == 1 ? x.stableNorm() * std::abs(weights()(0))
                                             : (x.array() * weights().array()).matrix().stableNorm();
 #endif
     if (norm > epsilon())
       out = x * (epsilon() / norm);
     else
       out = x;
   }
References sopt::proximal::WeightedL2Ball< T >::epsilon(), sopt::proximal::l2_norm(), and sopt::proximal::WeightedL2Ball< T >::weights().
weights() [1/2]
template<class T > const t_Vector& sopt::proximal::WeightedL2Ball< T >::weights () const inline
Weights associated with each dimension.
Definition at line 302 of file proximal.h.
 { return weights_; }
Referenced by sopt::proximal::WeightedL2Ball< T >::operator()().
weights() [2/2]
template<class T > template<class T0 > WeightedL2Ball<T>& sopt::proximal::WeightedL2Ball< T >::weights (Eigen::MatrixBase< T0 > const & w) inline
Weights associated with each dimension.
Definition at line 305 of file proximal.h.
{
     if ((w.array() < 0e0).any()) SOPT_THROW("Weights cannot be negative");
     if (w.stableNorm() < 1e-12) SOPT_THROW("Weights cannot be null");
     weights_ = w;
     return *this;
   }
References SOPT_THROW.
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/proximal.h