SOPT: sopt::Sampling Class Reference
sopt::Sampling Class Reference
An operator that samples a set of measurements.
#include <sampling.h>
Public Member Functions
Sampling (t_uint size, std::vector< t_uint > const &indices)
Constructs from a vector.
template<class RNG >
Sampling (t_uint size, t_uint samples, RNG &&rng)
Constructs from the size and the number of samples to pick.
Sampling (t_uint size, t_uint samples)
Constructs from the size and the number of samples to pick.
template<class T0 , class T1 >
void operator() (Eigen::DenseBase< T0 > &out, Eigen::DenseBase< T1 > const &x) const
template<class T0 , class T1 >
void operator() (Eigen::DenseBase< T0 > &&out, Eigen::DenseBase< T1 > const &x) const
template<class T0 , class T1 >
void adjoint (Eigen::DenseBase< T0 > &out, Eigen::DenseBase< T1 > const &x) const
template<class T0 , class T1 >
void adjoint (Eigen::DenseBase< T0 > &&out, Eigen::DenseBase< T1 > const &x) const
t_uint cols () const
Size of the vector returned by the adjoint operation.
t_uint rows () const
Number of measurements.
const std::vector< t_uint > & indices () const
Indices of sampled points.
Detailed Description
An operator that samples a set of measurements.
Picks some elements from a vector
Definition at line 16 of file sampling.h.
Constructor & Destructor Documentation
Sampling() [1/3]
sopt::Sampling::Sampling (t_uint size, std::vector< t_uint > const & indices) inline
Constructs from a vector.
Definition at line 19 of file sampling.h.
 : indices_(indices), size(size) {}
Sampling() [2/3]
template<class RNG > sopt::Sampling::Sampling (t_uint size, t_uint samples, RNG && rng)
Constructs from the size and the number of samples to pick.
Definition at line 90 of file sampling.h.
                                                          : indices_(size), size(size) {
   std::iota(indices_.begin(), indices_.end(), 0);
   std::shuffle(indices_.begin(), indices_.end(), rng);
   indices_.resize(samples);
 }
Sampling() [3/3]
sopt::Sampling::Sampling (t_uint size, t_uint samples) inline
Constructs from the size and the number of samples to pick.
Definition at line 24 of file sampling.h.
       : Sampling(size, samples, std::mt19937_64(std::random_device()())) {}
Member Function Documentation
adjoint() [1/2]
template<class T0 , class T1 > void sopt::Sampling::adjoint (Eigen::DenseBase< T0 > && out, Eigen::DenseBase< T1 > const & x) const inline
Definition at line 40 of file sampling.h.
{
     adjoint(out, x);
   }
References adjoint().
adjoint() [2/2]
template<class T0 , class T1 > void sopt::Sampling::adjoint (Eigen::DenseBase< T0 > & out, Eigen::DenseBase< T1 > const & x) const
Definition at line 69 of file sampling.h.
{
   assert(static_cast<t_uint>(x.size()) == indices_.size());
   out.resize(out.size());
   out.fill(0);
   for (decltype(indices_.size()) i(0); i < indices_.size(); ++i) {
     assert(indices_[i] < static_cast<t_uint>(out.size()));
     out[indices_[i]] = x[i];
   }
 }
Referenced by adjoint(), and sopt::linear_transform().
cols()
t_uint sopt::Sampling::cols () const inline
Size of the vector returned by the adjoint operation.
Definition at line 45 of file sampling.h.
 { return size; }
Referenced by sopt::linear_transform().
indices()
const std::vector<t_uint>& sopt::Sampling::indices () const inline
Indices of sampled points.
Definition at line 50 of file sampling.h.
 { return indices_; }
Referenced by TEST_CASE().
operator()() [1/2]
template<class T0 , class T1 > void sopt::Sampling::operator() (Eigen::DenseBase< T0 > && out, Eigen::DenseBase< T1 > const & x) const inline
Definition at line 32 of file sampling.h.
{
     operator()(out, x);
   }
References operator()().
operator()() [2/2]
template<class T0 , class T1 > void sopt::Sampling::operator() (Eigen::DenseBase< T0 > & out, Eigen::DenseBase< T1 > const & x) const
Definition at line 60 of file sampling.h.
{
   out.resize(indices_.size());
   for (decltype(indices_.size()) i(0); i < indices_.size(); ++i) {
     assert(indices_[i] < static_cast<t_uint>(x.size()));
     out[i] = x[indices_[i]];
   }
 }
Referenced by operator()().
rows()
t_uint sopt::Sampling::rows () const inline
Number of measurements.
Definition at line 47 of file sampling.h.
 { return indices_.size(); }
Referenced by sopt::linear_transform().
The documentation for this class was generated from the following files:
/home/runner/work/sopt/sopt/cpp/sopt/sampling.h
/home/runner/work/sopt/sopt/cpp/sopt/sampling.cc