SOPT: sopt::proximal::L2Ball< T > Class Template Reference
sopt::proximal::L2Ball< T > Class Template Reference
Proximal for indicator function of L2 ball.
#include <proximal.h>
Public Types
using Real = typename real_type< T >::type
Public Member Functions
L2Ball (Real epsilon)
Constructs an L2 ball proximal of size epsilon.
void operator() (Vector< T > &out, typename real_type< T >::type, Vector< T > const &x) const
Calls proximal function.
void operator() (Vector< T > &out, Vector< T > const &x) const
Calls proximal function.
template<class T0 >
EnveloppeExpression< L2Ball, T0 > operator() (Real const &, Eigen::MatrixBase< T0 > const &x) const
Lazy version.
template<class T0 >
EnveloppeExpression< L2Ball, T0 > operator() (Eigen::MatrixBase< T0 > const &x) const
Lazy version.
Real epsilon () const
Size of the ball.
L2Ball< T > & epsilon (Real eps)
Size of the ball.
Detailed Description
template<class T>
class sopt::proximal::L2Ball< T >
Proximal for indicator function of L2 ball.
Definition at line 182 of file proximal.h.
Member Typedef Documentation
Real
template<class T > using sopt::proximal::L2Ball< T >::Real = typename real_type<T>::type
Definition at line 184 of file proximal.h.
Constructor & Destructor Documentation
L2Ball()
template<class T > sopt::proximal::L2Ball< T >::L2Ball (Real epsilon) inline
Constructs an L2 ball proximal of size epsilon.
Definition at line 190 of file proximal.h.
 : epsilon_(epsilon) {}
Member Function Documentation
epsilon() [1/2]
template<class T > Real sopt::proximal::L2Ball< T >::epsilon () const inline
Size of the ball.
Definition at line 222 of file proximal.h.
 { return epsilon_; }
Referenced by sopt::proximal::WeightedL2Ball< T >::epsilon(), sopt::proximal::L2Ball< T >::operator()(), and TEST_CASE().
epsilon() [2/2]
template<class T > L2Ball<T>& sopt::proximal::L2Ball< T >::epsilon (Real eps) inline
Size of the ball.
Definition at line 224 of file proximal.h.
{
     epsilon_ = eps;
     return *this;
   }
operator()() [1/4]
template<class T > template<class T0 > EnveloppeExpression<L2Ball, T0> sopt::proximal::L2Ball< T >::operator() (Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 217 of file proximal.h.
{
     return {*this, x};
   }
operator()() [2/4]
template<class T > template<class T0 > EnveloppeExpression<L2Ball, T0> sopt::proximal::L2Ball< T >::operator() (Real const & , Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 211 of file proximal.h.
{
     return {*this, x};
   }
operator()() [3/4]
template<class T > void sopt::proximal::L2Ball< T >::operator() (Vector< T > & out, typename real_type< T >::type , Vector< T > const & x) const inline
Calls proximal function.
Definition at line 194 of file proximal.h.
{
     return operator()(out, x);
   }
operator()() [4/4]
template<class T > void sopt::proximal::L2Ball< T >::operator() (Vector< T > & out, Vector< T > const & x) const inline
Calls proximal function.
Definition at line 198 of file proximal.h.
{
 #ifdef SOPT_MPI
     auto const norm = mpi::l2_norm(x, comm_);
 #else
     auto const norm = x.stableNorm();
 #endif
     if (norm > epsilon())
       out = x * (epsilon() / norm);
     else
       out = x;
   }
References sopt::proximal::L2Ball< T >::epsilon(), and sopt::proximal::l2_norm().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/proximal.h