SOPT: sopt::proximal::L1< SCALAR >::Breaker Class Reference
sopt::proximal::L1< SCALAR >::Breaker Class Reference
#include <l1_proximal.h>
Public Types
using Real = typename real_type< SCALAR >::type
Public Member Functions
Breaker (Real objective, Real tolerance=1e-8, bool do_two_cycle=true)
bool operator() (Real objective)
True if we should break out of loop.
Real current () const
Current objective.
Real previous () const
Current objective.
Real relative_variation () const
Variation in the objective function.
bool two_cycle () const
Whether we have a cycle of period two.
bool converged () const
True if relative variation smaller than tolerance.
Real tolerance () const
Tolerance criteria.
L1< SCALAR >::Breaker & tolerance (Real tol) const
Tolerance criteria.
Detailed Description
template<class SCALAR>
class sopt::proximal::L1< SCALAR >::Breaker
Definition at line 425 of file l1_proximal.h.
Member Typedef Documentation
Real
template<class SCALAR > using sopt::proximal::L1< SCALAR >::Breaker::Real = typename real_type<SCALAR>::type
Definition at line 427 of file l1_proximal.h.
Constructor & Destructor Documentation
Breaker()
template<class SCALAR > sopt::proximal::L1< SCALAR >::Breaker::Breaker (Real objective, Real tolerance = 1e-8, bool do_two_cycle = true) inline
Constructs a breaker object
Parameters
[in] objective the first objective function
[in] tolerance Convergence criteria for convergence
[in] do_two_cycle Whether to enable two cycle detections. Only necessary when mixing is not enabled.
Definition at line 433 of file l1_proximal.h.
       : tolerance_(tolerance),
         iter(0),
         objectives({{objective, 0, 0, 0}}),
         do_two_cycle(do_two_cycle) {}
References sopt::proximal::L1TightFrame< SCALAR >::objective().
Member Function Documentation
converged()
template<class SCALAR > bool sopt::proximal::L1< SCALAR >::Breaker::converged () const inline
True if relative variation smaller than tolerance.
Definition at line 458 of file l1_proximal.h.
{
     // If current ~ 0, then defaults to absolute convergence
     // This is mainly to avoid a division by zero
     if (std::abs(current() * 1000) < tolerance()) return std::abs(previous() * 1000) < tolerance();
     return relative_variation() < tolerance();
   }
Referenced by TEST_CASE().
current()
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::Breaker::current () const inline
Current objective.
Definition at line 445 of file l1_proximal.h.
 { return objectives[0]; }
Referenced by TEST_CASE().
operator()()
template<class SCALAR > bool sopt::proximal::L1< SCALAR >::Breaker::operator() (Real objective) inline
True if we should break out of loop.
Definition at line 439 of file l1_proximal.h.
{
     ++iter;
     objectives = {{objective, objectives[0], objectives[1], objectives[2]}};
     return converged() or two_cycle();
   }
References sopt::proximal::L1TightFrame< SCALAR >::objective().
previous()
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::Breaker::previous () const inline
Current objective.
Definition at line 447 of file l1_proximal.h.
 { return objectives[1]; }
relative_variation()
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::Breaker::relative_variation () const inline
Variation in the objective function.
Definition at line 449 of file l1_proximal.h.
 { return std::abs((current() - previous()) / current()); }
tolerance() [1/2]
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::Breaker::tolerance () const inline
Tolerance criteria.
Definition at line 465 of file l1_proximal.h.
 { return tolerance_; }
tolerance() [2/2]
template<class SCALAR > L1<SCALAR>::Breaker& sopt::proximal::L1< SCALAR >::Breaker::tolerance (Real tol) const inline
Tolerance criteria.
Definition at line 467 of file l1_proximal.h.
{
     tolerance_ = tol;
     return *this;
   }
References tol.
two_cycle()
template<class SCALAR > bool sopt::proximal::L1< SCALAR >::Breaker::two_cycle () const inline
Whether we have a cycle of period two.
Cycling is prone to happen without mixing, it seems.
Definition at line 452 of file l1_proximal.h.
{
     return do_two_cycle and iter > 3 and std::abs(objectives[0] - objectives[2]) < tolerance() and
            std::abs(objectives[1] - objectives[3]) < tolerance();
   }
Referenced by TEST_CASE().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/l1_proximal.h