SOPT: sopt::algorithm::PowerMethod< SCALAR > Class Template Reference
sopt::algorithm::PowerMethod< SCALAR > Class Template Reference
Eigenvalue and eigenvector for eigenvalue with largest magnitude.
#include <power_method.h>
Classes
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef SCALAR value_type
Scalar type.
typedef value_type Scalar
Scalar type.
typedef real_type< Scalar >::type Real
Real type.
typedef Vector< Scalar > t_Vector
Type of then underlying vectors.
typedef LinearTransform< t_Vector > t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
Public Member Functions
PowerMethod ()
Setups ProximalADMM.
virtual ~PowerMethod ()
DiagnosticAndResult AtA (t_LinearTransform const &A, t_Vector const &input) const
Maximum number of iterations.
template<class DERIVED >
DiagnosticAndResult operator() (Eigen::DenseBase< DERIVED > const &A, t_Vector const &input) const
Calls the power method for A, with A a matrix.
DiagnosticAndResult operator() (OperatorFunction< t_Vector > const &op, t_Vector const &input) const
Calls the power method for a given matrix-vector multiplication function.
Detailed Description
template<class SCALAR>
class sopt::algorithm::PowerMethod< SCALAR >
Eigenvalue and eigenvector for eigenvalue with largest magnitude.
Definition at line 132 of file power_method.h.
Member Typedef Documentation
Real
template<class SCALAR > typedef real_type<Scalar>::type sopt::algorithm::PowerMethod< SCALAR >::Real
Real type.
Definition at line 139 of file power_method.h.
Scalar
template<class SCALAR > typedef value_type sopt::algorithm::PowerMethod< SCALAR >::Scalar
Scalar type.
Definition at line 137 of file power_method.h.
t_LinearTransform
template<class SCALAR > typedef LinearTransform<t_Vector> sopt::algorithm::PowerMethod< SCALAR >::t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
Definition at line 143 of file power_method.h.
t_Vector
template<class SCALAR > typedef Vector<Scalar> sopt::algorithm::PowerMethod< SCALAR >::t_Vector
Type of then underlying vectors.
Definition at line 141 of file power_method.h.
value_type
template<class SCALAR > typedef SCALAR sopt::algorithm::PowerMethod< SCALAR >::value_type
Scalar type.
Definition at line 135 of file power_method.h.
Constructor & Destructor Documentation
PowerMethod()
template<class SCALAR > sopt::algorithm::PowerMethod< SCALAR >::PowerMethod () inline
Setups ProximalADMM.
Definition at line 158 of file power_method.h.
 : itermax_(std::numeric_limits<t_uint>::max()), tolerance_(1e-8) {}
~PowerMethod()
template<class SCALAR > virtual sopt::algorithm::PowerMethod< SCALAR >::~PowerMethod () inline virtual
Definition at line 159 of file power_method.h.
 {}
Member Function Documentation
AtA()
template<class SCALAR > PowerMethod< SCALAR >::DiagnosticAndResult sopt::algorithm::PowerMethod< SCALAR >::AtA (t_LinearTransform const & A, t_Vector const & input) const
Maximum number of iterations.
Convergence criteria Calls the power method for A.adjoint() * A
Definition at line 194 of file power_method.h.
References sopt::LinearTransform< VECTOR >::adjoint(), and sopt::algorithm::PowerMethod< SCALAR >::operator()().
{
   auto const op = [&A](t_Vector &out, t_Vector const &input) -> void {
     out = A.adjoint() * (A * input).eval();
   };
   return operator()(op, input);
 }
operator()() [1/2]
template<class SCALAR > template<class DERIVED > PowerMethod< SCALAR >::DiagnosticAndResult sopt::algorithm::PowerMethod< SCALAR >::operator() (Eigen::DenseBase< DERIVED > const & A, t_Vector const & input) const
Calls the power method for A, with A a matrix.
Definition at line 204 of file power_method.h.
Referenced by sopt::algorithm::PowerMethod< SCALAR >::AtA().
{
   Matrix<Scalar> const Ad = A.derived();
   auto const op = [&Ad](t_Vector &out, t_Vector const &input) -> void { out = Ad * input; };
   return operator()(op, input);
 }
operator()() [2/2]
template<class SCALAR > PowerMethod< SCALAR >::DiagnosticAndResult sopt::algorithm::PowerMethod< SCALAR >::operator() (OperatorFunction< t_Vector > const & op, t_Vector const & input) const
Calls the power method for a given matrix-vector multiplication function.
Definition at line 212 of file power_method.h.
References sopt::algorithm::PowerMethod< SCALAR >::DiagnosticAndResult::eigenvector, sopt::algorithm::PowerMethod< SCALAR >::DiagnosticAndResult::magnitude, sopt::algorithm::PowerMethod< SCALAR >::DiagnosticAndResult::niters, SOPT_INFO, and SOPT_WARN.
{
   SOPT_INFO("Computing the upper bound of a given operator");
   SOPT_INFO("    - input vector {}", input.transpose());
   t_Vector eigenvector = input.normalized();
   SOPT_INFO("    - eigenvector norm {}", eigenvector.stableNorm());
   typename t_Vector::Scalar previous_magnitude = 1;
   bool converged = false;
   t_uint niters = 0;
   for (; niters < itermax() and converged == false; ++niters) {
     op(eigenvector, eigenvector);
     typename t_Vector::Scalar const magnitude =
         eigenvector.stableNorm() / static_cast<Real>(eigenvector.size());
     auto const rel_val = std::abs((magnitude - previous_magnitude) / previous_magnitude);
     converged = rel_val < tolerance();
     SOPT_INFO("    - [PM] iteration {}/{} -- norm: {}", niters, itermax(), magnitude);
     eigenvector /= magnitude;
     previous_magnitude = magnitude;
   }
   // check function exists, otherwise, don't know if convergence is meaningful
   if (not converged) {
     SOPT_WARN("    - [PM] did not converge within {} iterations", itermax());
   } else {
     SOPT_INFO("    - [PM] converged in {} of {} iterations", niters, itermax());
   }
   return DiagnosticAndResult{itermax(), converged, previous_magnitude, eigenvector.normalized()};
 }
The documentation for this class was generated from the following file:
/mydata/cpp/sopt/power_method.h