SOPT: sopt::LinearTransform< VECTOR > Class Template Reference
sopt::LinearTransform< VECTOR > Class Template Reference
Joins together direct and indirect operators.
#include <linear_transform.h>
Public Types
using t_Function = OperatorFunction< VECTOR >
Type of the wrapped functions.
Public Types inherited from sopt::details::WrapFunction< VECTOR >
using t_Function = OperatorFunction< VECTOR >
Type of function wrapped here.
Public Member Functions
LinearTransform (t_Function const &direct, t_Function const &indirect, std::array< t_int, 3 > sizes={{1, 1, 0}})
LinearTransform (t_Function const &direct, std::array< t_int, 3 > dsizes, t_Function const &indirect, std::array< t_int, 3 > isizes)
LinearTransform (details::WrapFunction< VECTOR > const &direct, details::WrapFunction< VECTOR > const &indirect)
LinearTransform (LinearTransform const &c)
LinearTransform (LinearTransform &&c)
void operator= (LinearTransform const &c)
void operator= (LinearTransform &&c)
LinearTransform< VECTOR > adjoint () const
Indirect transform.
Public Member Functions inherited from sopt::details::WrapFunction< VECTOR >
WrapFunction (t_Function const &func, std::array< t_int, 3 > sizes={{1, 1, 0}})
WrapFunction (WrapFunction const &c)
WrapFunction (WrapFunction const &&c)
void operator= (WrapFunction const &c)
void operator= (WrapFunction &&c)
template<typename T0 >
AppliedFunction< t_Function const &, Eigen::ArrayBase< T0 > > operator() (Eigen::ArrayBase< T0 > const &x) const
Function application form.
template<typename T0 >
AppliedFunction< t_Function const &, Eigen::ArrayBase< T0 > > operator* (Eigen::ArrayBase< T0 > const &x) const
Multiplication application form.
template<typename T0 >
AppliedFunction< t_Function const &, Eigen::MatrixBase< T0 > > operator() (Eigen::MatrixBase< T0 > const &x) const
Function application form.
template<typename T0 >
AppliedFunction< t_Function const &, Eigen::MatrixBase< T0 > > operator* (Eigen::MatrixBase< T0 > const &x) const
Multiplication application form.
std::array< t_int, 3 > const & sizes () const
Defines relation-ship between input and output sizes.
template<typename T >
std::enable_if< std::is_integral< T >::value, T >::type rows (T xsize) const
Output vector size for a input with xsize elements.
Detailed Description
template<typename VECTOR>
class sopt::LinearTransform< VECTOR >
Joins together direct and indirect operators.
Definition at line 30 of file linear_transform.h.
Member Typedef Documentation
t_Function
template<typename VECTOR > using sopt::LinearTransform< VECTOR >::t_Function = OperatorFunction<VECTOR>
Type of the wrapped functions.
Definition at line 33 of file linear_transform.h.
Constructor & Destructor Documentation
LinearTransform() [1/5]
template<typename VECTOR > sopt::LinearTransform< VECTOR >::LinearTransform (t_Function const & direct, t_Function const & indirect, std::array< t_int, 3 > sizes = {{1, 1, 0}}) inline
Constructor
Parameters
[in] direct function with signature void(VECTOR&, VECTOR const&) which applies a linear operator to a vector.
[in] indirect function with signature void(VECTOR&, VECTOR const&) which applies a the conjugate transpose linear operator to a vector.
[in] sizes 3 integer elements (a, b, c) such that if the input to linear operator is of size N, then the output is of size (a * N) / b + c. A similar quantity is deduced for the indirect operator.
Definition at line 43 of file linear_transform.h.
                                              {{1, 1, 0}})
       : LinearTransform(
             direct, sizes, indirect,
             {{sizes[1], sizes[0], sizes[0] == 0 ? 0 : -(sizes[2] * sizes[1]) / sizes[0]}}) {
     assert(sizes[0] != 0);
   }
LinearTransform() [2/5]
template<typename VECTOR > sopt::LinearTransform< VECTOR >::LinearTransform (t_Function const & direct, std::array< t_int, 3 > dsizes, t_Function const & indirect, std::array< t_int, 3 > isizes) inline
Constructor
Parameters
[in] direct function with signature void(VECTOR&, VECTOR const&) which applies a linear operator to a vector.
[in] dsizes 3 integer elements (a, b, c) such that if the input to the linear operator is of size N, then the output is of size (a * N) / b + c.
[in] indirect function with signature void(VECTOR&, VECTOR const&) which applies a the conjugate transpose linear operator to a vector.
[in] dsizes 3 integer elements (a, b, c) such that if the input to the indirect linear operator is of size N, then the output is of size (a * N) / b + c.
Definition at line 59 of file linear_transform.h.
       : LinearTransform(details::wrap(direct, dsizes), details::wrap(indirect, isizes)) {}
LinearTransform() [3/5]
template<typename VECTOR > sopt::LinearTransform< VECTOR >::LinearTransform (details::WrapFunction< VECTOR > const & direct, details::WrapFunction< VECTOR > const & indirect) inline
Definition at line 62 of file linear_transform.h.
       : details::WrapFunction<VECTOR>(direct), indirect_(indirect) {}
LinearTransform() [4/5]
template<typename VECTOR > sopt::LinearTransform< VECTOR >::LinearTransform (LinearTransform< VECTOR > const & c) inline
Definition at line 65 of file linear_transform.h.
       : details::WrapFunction<VECTOR>(c), indirect_(c.indirect_) {}
LinearTransform() [5/5]
template<typename VECTOR > sopt::LinearTransform< VECTOR >::LinearTransform (LinearTransform< VECTOR > && c) inline
Definition at line 67 of file linear_transform.h.
       : details::WrapFunction<VECTOR>(std::move(c)), indirect_(std::move(c.indirect_)) {}
Member Function Documentation
adjoint()
template<typename VECTOR > LinearTransform<VECTOR> sopt::LinearTransform< VECTOR >::adjoint () const inline
Indirect transform.
Definition at line 79 of file linear_transform.h.
{
     return LinearTransform<VECTOR>(indirect_, static_cast<details::WrapFunction<VECTOR> const &>(*this));
   }
Referenced by sopt::adjoint_transform(), sopt::algorithm::PowerMethod< SCALAR >::AtA(), sopt::algorithm::ProximalADMM< SCALAR >::initial_guess(), sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), main(), sopt::algorithm::power_method(), TEST_CASE(), and sopt::objective_functions::unconstrained_l1_regularisation().
operator=() [1/2]
template<typename VECTOR > void sopt::LinearTransform< VECTOR >::operator= (LinearTransform< VECTOR > && c) inline
Definition at line 73 of file linear_transform.h.
{
     details::WrapFunction<VECTOR>::operator=(std::move(c));
     indirect_ = std::move(c.indirect_);
   }
References sopt::details::WrapFunction< VECTOR >::operator=().
operator=() [2/2]
template<typename VECTOR > void sopt::LinearTransform< VECTOR >::operator= (LinearTransform< VECTOR > const & c) inline
Definition at line 69 of file linear_transform.h.
{
     details::WrapFunction<VECTOR>::operator=(c);
     indirect_ = c.indirect_;
   }
References sopt::details::WrapFunction< VECTOR >::operator=().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/linear_transform.h