SOPT: sopt::algorithm::ImagingForwardBackward< SCALAR > Class Template Reference
sopt::algorithm::ImagingForwardBackward< SCALAR > Class Template Reference
#include <imaging_forward_backward.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef FB::value_type value_type
typedef FB::Scalar Scalar
typedef FB::Real Real
typedef FB::t_Vector t_Vector
typedef FB::t_LinearTransform t_LinearTransform
typedef FB::t_Proximal t_Proximal
typedef FB::t_Gradient t_Gradient
typedef FB::t_IsConverged t_IsConverged
typedef FB::value_type value_type
typedef FB::Scalar Scalar
typedef FB::Real Real
typedef FB::t_Vector t_Vector
typedef FB::t_LinearTransform t_LinearTransform
template<class T >
using t_Proximal = std::function< void(t_Vector &, const T &, const t_Vector &)>
typedef FB::t_Gradient t_Gradient
typedef FB::t_IsConverged t_IsConverged
Public Member Functions
template<class DERIVED >
ImagingForwardBackward (Eigen::MatrixBase< DERIVED > const &target)
virtual ~ImagingForwardBackward ()
SOPT_MACRO (l1_proximal, proximal::L1< Scalar >)
Maximum number of iterations.
SOPT_MACRO (l2_gradient, t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO (tight_frame, bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (beta, Real)
γ parameter.
SOPT_MACRO (sigma, Real)
γ parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
t_Vector const & target () const
Vector of target measurements.
Real objmin () const
Minimun of objective_function.
template<class DERIVED >
ImagingForwardBackward< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() () const
Calls Forward Backward.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to FB.
template<class... ARGS>
ImagingForwardBackward &::type Phi (ARGS &&... args)
proximal::L1< Scalar > & l1_proximal ()
L1 proximal used during calculation.
t_Gradient & l2_graident ()
Proximal of the L2 ball.
t_LinearTransform const & Psi () const
Analysis operator Ψ
template<class... ARGS>
ImagingForwardBackward< Scalar > &::type Psi (ARGS &&... args)
SOPT_MACRO (itermax, l1, L1)
SOPT_MACRO (tolerance, l1, L1)
SOPT_MACRO (positivity_constraint, l1, L1)
SOPT_MACRO (real_constraint, l1, L1)
SOPT_MACRO (fista_mixing, l1, L1)
SOPT_MACRO (nu, l1, L1)
SOPT_MACRO (weights, l1, L1)
ImagingForwardBackward< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingForwardBackward< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingForwardBackward< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
template<class DERIVED >
ImagingForwardBackward (Eigen::MatrixBase< DERIVED > const &target)
virtual ~ImagingForwardBackward ()
SOPT_MACRO (l2_proximal, t_Proximal< Real >)
l2 proximal for regularizaiton
SOPT_MACRO (l2_proximal, t_Proximal< Vector< Real >>)
l2 proximal for regularizaiton with weights
SOPT_MACRO (l2_proximal_weights, Vector< Real >)
l2 proximal weights
SOPT_MACRO (l2_gradient, t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO (tight_frame, bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (beta, Real)
γ parameter.
SOPT_MACRO (sigma, Real)
γ parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
t_Vector const & target () const
Vector of target measurements.
Real objmin () const
Minimun of objective_function.
template<class DERIVED >
ImagingForwardBackward< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() () const
Calls Forward Backward.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to FB.
template<class... ARGS>
ImagingForwardBackward &::type Phi (ARGS &&... args)
t_Proximal & l1_proximal ()
L1 proximal used during calculation.
t_Gradient & l2_graident ()
Proximal of the L2 ball.
ImagingForwardBackward< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingForwardBackward< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingForwardBackward< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
Detailed Description
template<class SCALAR>
class sopt::algorithm::ImagingForwardBackward< SCALAR >
Definition at line 25 of file imaging_forward_backward.h.
Member Typedef Documentation
Real [1/2]
template<class SCALAR> typedef FB::Real sopt::algorithm::ImagingForwardBackward< SCALAR >::Real
Definition at line 32 of file imaging_forward_backward.h.
Real [2/2]
template<class SCALAR> typedef FB::Real sopt::algorithm::ImagingForwardBackward< SCALAR >::Real
Definition at line 32 of file l2_forward_backward.h.
Scalar [1/2]
template<class SCALAR> typedef FB::Scalar sopt::algorithm::ImagingForwardBackward< SCALAR >::Scalar
Definition at line 31 of file l2_forward_backward.h.
Scalar [2/2]
template<class SCALAR> typedef FB::Scalar sopt::algorithm::ImagingForwardBackward< SCALAR >::Scalar
Definition at line 31 of file imaging_forward_backward.h.
t_Gradient [1/2]
template<class SCALAR> typedef FB::t_Gradient sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Gradient
Definition at line 36 of file imaging_forward_backward.h.
t_Gradient [2/2]
template<class SCALAR> typedef FB::t_Gradient sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Gradient
Definition at line 37 of file l2_forward_backward.h.
t_IsConverged [1/2]
template<class SCALAR> typedef FB::t_IsConverged sopt::algorithm::ImagingForwardBackward< SCALAR >::t_IsConverged
Definition at line 37 of file imaging_forward_backward.h.
t_IsConverged [2/2]
template<class SCALAR> typedef FB::t_IsConverged sopt::algorithm::ImagingForwardBackward< SCALAR >::t_IsConverged
Definition at line 38 of file l2_forward_backward.h.
t_LinearTransform [1/2]
template<class SCALAR> typedef FB::t_LinearTransform sopt::algorithm::ImagingForwardBackward< SCALAR >::t_LinearTransform
Definition at line 34 of file imaging_forward_backward.h.
t_LinearTransform [2/2]
template<class SCALAR> typedef FB::t_LinearTransform sopt::algorithm::ImagingForwardBackward< SCALAR >::t_LinearTransform
Definition at line 34 of file l2_forward_backward.h.
t_Proximal [1/2]
template<class SCALAR> typedef FB::t_Proximal sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Proximal
Definition at line 35 of file imaging_forward_backward.h.
t_Proximal [2/2]
template<class SCALAR> template<class T > using sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Proximal = std::function<void(t_Vector &, const T &, const t_Vector &)>
Definition at line 36 of file l2_forward_backward.h.
t_Vector [1/2]
template<class SCALAR> typedef FB::t_Vector sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Vector
Definition at line 33 of file l2_forward_backward.h.
t_Vector [2/2]
template<class SCALAR> typedef FB::t_Vector sopt::algorithm::ImagingForwardBackward< SCALAR >::t_Vector
Definition at line 33 of file imaging_forward_backward.h.
value_type [1/2]
template<class SCALAR> typedef FB::value_type sopt::algorithm::ImagingForwardBackward< SCALAR >::value_type
Definition at line 30 of file imaging_forward_backward.h.
value_type [2/2]
template<class SCALAR> typedef FB::value_type sopt::algorithm::ImagingForwardBackward< SCALAR >::value_type
Definition at line 30 of file l2_forward_backward.h.
Constructor & Destructor Documentation
ImagingForwardBackward() [1/2]
template<class SCALAR> template<class DERIVED > sopt::algorithm::ImagingForwardBackward< SCALAR >::ImagingForwardBackward (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for ForwardBackward
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 62 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
       : l1_proximal_(),
         l2_gradient_([](t_Vector &output, const t_Vector &x) -> void {
           output = x;
         }),  // gradient of 1/2 * x^2 = x;
         tight_frame_(false),
         residual_tolerance_(0.),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         beta_(1),
         sigma_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         target_(target) {}
~ImagingForwardBackward() [1/2]
template<class SCALAR> virtual sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward () inline virtual
Definition at line 80 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal(), sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence(), sopt::sigma(), sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
 {}
ImagingForwardBackward() [2/2]
template<class SCALAR> template<class DERIVED > sopt::algorithm::ImagingForwardBackward< SCALAR >::ImagingForwardBackward (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for ForwardBackward
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 56 of file l2_forward_backward.h.
References sopt::proximal::l2_norm(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
       : l2_proximal_([](t_Vector &output, const t_real &gamma, const t_Vector &x) -> void {
           proximal::l2_norm(output, gamma, x);
         }),
         l2_proximal_weighted_(
             [](t_Vector &output, const Vector<Real> &gamma, const t_Vector &x) -> void {
               proximal::l2_norm(output, gamma, x);
             }),
         l2_proximal_weights_(Vector<Real>::Ones(1)),
         l2_gradient_([](t_Vector &output, const t_Vector &x) -> void {
           output = x;
         }),  // gradient of 1/2 * x^2 = x;
         tight_frame_(false),
         residual_tolerance_(0.),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         beta_(1),
         sigma_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         target_(target) {}
~ImagingForwardBackward() [2/2]
template<class SCALAR> virtual sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward () inline virtual
Definition at line 81 of file l2_forward_backward.h.
 {}
Member Function Documentation
is_converged() [1/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 220 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::l2_norm(), sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence(), sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), sopt::ScalarRelativeVariation< TYPE >::previous(), sopt::ScalarRelativeVariation< TYPE >::relative_tolerance(), sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence(), sopt::sigma(), SOPT_HIGH_LOG, SOPT_LOW_LOG, and sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
is_converged() [2/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 255 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::Diagnostic::l1_diagnostic, sopt::l1_norm(), sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal(), sopt::l2_norm(), sopt::proximal::L1TightFrame< SCALAR >::objective(), sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence(), sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), sopt::ScalarRelativeVariation< TYPE >::previous(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Psi(), sopt::ScalarRelativeVariation< TYPE >::relative_tolerance(), sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence(), sopt::sigma(), SOPT_HIGH_LOG, SOPT_LOW_LOG, sopt::algorithm::ImagingForwardBackward< SCALAR >::target(), and sopt::proximal::L1< SCALAR >::tight_frame().
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), TEST_CASE(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
l1_proximal() [1/2]
template<class SCALAR> proximal::L1<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal () inline
L1 proximal used during calculation.
Non-const version to setup the object.
Definition at line 201 of file imaging_forward_backward.h.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Psi(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
 { return l1_proximal_; }
l1_proximal() [2/2]
template<class SCALAR> t_Proximal& sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal () inline
L1 proximal used during calculation.
Non-const version to setup the object.
Definition at line 206 of file l2_forward_backward.h.
 { return l1_proximal_; }
l2_graident() [1/2]
template<class SCALAR> t_Gradient& sopt::algorithm::ImagingForwardBackward< SCALAR >::l2_graident () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 204 of file imaging_forward_backward.h.
 { return l2_gradient_; }
l2_graident() [2/2]
template<class SCALAR> t_Gradient& sopt::algorithm::ImagingForwardBackward< SCALAR >::l2_graident () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 209 of file l2_forward_backward.h.
 { return l2_gradient_; }
objective_convergence() [1/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 216 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence().
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
objective_convergence() [2/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 251 of file imaging_forward_backward.h.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::objective_convergence(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
objmin() [1/2]
template<class SCALAR> Real sopt::algorithm::ImagingForwardBackward< SCALAR >::objmin () const inline
Minimun of objective_function.
Definition at line 137 of file imaging_forward_backward.h.
 { return objmin_; };
objmin() [2/2]
template<class SCALAR> Real sopt::algorithm::ImagingForwardBackward< SCALAR >::objmin () const inline
Minimun of objective_function.
Definition at line 142 of file l2_forward_backward.h.
 { return objmin_; };
operator()() [1/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
Definition at line 147 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
{
     return operator()(out, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
   }
operator()() [2/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
Definition at line 152 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
{
     return operator()(out, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
   }
operator()() [3/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 153 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [4/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 158 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [5/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 159 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [6/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 164 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [7/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 165 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [8/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 170 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
operator()() [9/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 170 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [10/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 175 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
operator()() [11/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() () const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 178 of file imaging_forward_backward.h.
References sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), sopt::algorithm::ImagingForwardBackward< SCALAR >::target(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(
         result.x, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
     return result;
   }
operator()() [12/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() () const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 183 of file l2_forward_backward.h.
References sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi(), sopt::algorithm::ImagingForwardBackward< SCALAR >::target(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(
         result.x, ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu()));
     return result;
   }
operator()() [13/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to FB.
Definition at line 185 of file imaging_forward_backward.h.
References sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, and sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
operator()() [14/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingForwardBackward< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to FB.
Definition at line 190 of file l2_forward_backward.h.
References sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, and sopt::algorithm::ImagingForwardBackward< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
Phi() [1/2]
template<class SCALAR> template<class... ARGS> ImagingForwardBackward& ::type sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 193 of file imaging_forward_backward.h.
References sopt::linear_transform().
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Phi() [2/2]
template<class SCALAR> template<class... ARGS> ImagingForwardBackward& ::type sopt::algorithm::ImagingForwardBackward< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 198 of file l2_forward_backward.h.
References sopt::linear_transform().
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Psi() [1/2]
template<class SCALAR> t_LinearTransform const& sopt::algorithm::ImagingForwardBackward< SCALAR >::Psi () const inline
Analysis operator Ψ
Under-the-hood, the object is actually owned by the L1 proximal.
Definition at line 208 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal(), and sopt::proximal::L1< SCALAR >::Psi().
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), main(), and TEST_CASE().
 { return l1_proximal().Psi(); }
Psi() [2/2]
template<class SCALAR> template<class... ARGS> ImagingForwardBackward<Scalar>& ::type sopt::algorithm::ImagingForwardBackward< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 211 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::l1_proximal(), and sopt::proximal::L1< SCALAR >::Psi().
{
     l1_proximal().Psi(std::forward<ARGS>(args)...);
     return *this;
   }
residual_convergence() [1/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 212 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence().
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
residual_convergence() [2/2]
template<class SCALAR> ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 247 of file imaging_forward_backward.h.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::residual_convergence(), TEST_CASE(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
SOPT_MACRO() [1/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l1_proximal , proximal::L1< Scalar >)
Maximum number of iterations.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
SOPT_MACRO() [2/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal , t_Proximal< Real >)
l2 proximal for regularizaiton
SOPT_MACRO() [3/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l2_gradient , t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO() [4/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal , t_Proximal< Vector< Real >>)
l2 proximal for regularizaiton with weights
SOPT_MACRO() [5/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (tight_frame , bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO() [6/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l2_proximal_weights , Vector< Real >)
l2 proximal weights
SOPT_MACRO() [7/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [8/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (l2_gradient , t_Gradient)
Gradient of the l2 norm.
SOPT_MACRO() [9/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (tight_frame , bool)
Whether Ψ is a tight-frame or not.
SOPT_MACRO() [10/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [11/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [12/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [13/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [14/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [15/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [16/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [17/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [18/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [19/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (beta , Real)
γ parameter.
SOPT_MACRO() [20/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [21/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (sigma , Real)
γ parameter.
SOPT_MACRO() [22/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [23/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [24/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (beta , Real)
γ parameter.
SOPT_MACRO() [25/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [26/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (sigma , Real)
γ parameter.
SOPT_MACRO() [27/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [28/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [29/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [30/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [31/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (itermax , l1 , L1)
SOPT_MACRO() [32/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (tolerance , l1 , L1)
SOPT_MACRO() [33/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (positivity_constraint , l1 , L1)
SOPT_MACRO() [34/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (real_constraint , l1 , L1)
SOPT_MACRO() [35/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (fista_mixing , l1 , L1)
SOPT_MACRO() [36/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (nu , l1 , L1)
SOPT_MACRO() [37/37]
template<class SCALAR> sopt::algorithm::ImagingForwardBackward< SCALAR >::SOPT_MACRO (weights , l1 , L1)
target() [1/4]
template<class SCALAR> t_Vector const& sopt::algorithm::ImagingForwardBackward< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 135 of file imaging_forward_backward.h.
Referenced by sopt::algorithm::ImagingForwardBackward< SCALAR >::ImagingForwardBackward(), sopt::algorithm::ImagingForwardBackward< SCALAR >::is_converged(), sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()(), sopt::algorithm::ImagingForwardBackward< SCALAR >::target(), TEST_CASE(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::~ImagingForwardBackward().
 { return target_; }
target() [2/4]
template<class SCALAR> t_Vector const& sopt::algorithm::ImagingForwardBackward< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 140 of file l2_forward_backward.h.
 { return target_; }
target() [3/4]
template<class SCALAR> template<class DERIVED > ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 140 of file imaging_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
{
     target_ = target;
     return *this;
   }
target() [4/4]
template<class SCALAR> template<class DERIVED > ImagingForwardBackward<Scalar>& sopt::algorithm::ImagingForwardBackward< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 145 of file l2_forward_backward.h.
References sopt::algorithm::ImagingForwardBackward< SCALAR >::target().
{
     target_ = target;
     return *this;
   }
The documentation for this class was generated from the following files:
/mydata/cpp/sopt/imaging_forward_backward.h
/mydata/cpp/sopt/l2_forward_backward.h