SOPT: sopt::algorithm::TVPrimalDual< SCALAR > Class Template Reference
sopt::algorithm::TVPrimalDual< SCALAR > Class Template Reference
#include <tv_primal_dual.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
using value_type = typename PD::value_type
using Scalar = typename PD::Scalar
using Real = typename PD::Real
using t_Vector = typename PD::t_Vector
using t_LinearTransform = typename PD::t_LinearTransform
template<class T >
using t_Proximal = std::function< void(t_Vector &, const T &, const t_Vector &)>
using t_IsConverged = typename PD::t_IsConverged
using t_Constraint = typename PD::t_Constraint
using t_Random_Updater = typename PD::t_Random_Updater
Public Member Functions
template<class DERIVED >
TVPrimalDual (Eigen::MatrixBase< DERIVED > const &target)
virtual ~TVPrimalDual ()
SOPT_MACRO (tv_proximal, t_Proximal< Real >)
The tv prox functioning as f.
SOPT_MACRO (tv_proximal_weighted, t_Proximal< Vector< Real >>)
The tv prox with weights functioning as f.
SOPT_MACRO (tv_proximal_weights, Vector< Real >)
The tv prox weights functioning.
SOPT_MACRO (l2ball_proximal, proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
gamma parameter
SOPT_MACRO (update_scale, Real)
update parameter
SOPT_MACRO (positivity_constraint, bool)
Apply positivity constraint.
SOPT_MACRO (real_constraint, bool)
Apply real constraint.
SOPT_MACRO (sigma, Real)
sigma parameter
SOPT_MACRO (tau, Real)
tau parameter
SOPT_MACRO (xi, Real)
xi parameter
SOPT_MACRO (rho, Real)
rho parameter
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (precondition_stepsize, Real)
precondtion step size parameter
SOPT_MACRO (precondition_weights, t_Vector)
precondition weights parameter
SOPT_MACRO (precondition_iters, t_uint)
precondition iterations parameter
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (Psi, t_LinearTransform)
Wavelet operator.
SOPT_MACRO (random_measurement_updater, t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO (random_wavelet_updater, t_Random_Updater)
lambda that determines if to update wavelets
const t_Vector & target () const
Vector of target measurements.
template<class DERIVED >
TVPrimalDual< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() () const
Calls Primal Dual.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PD.
TVPrimalDual &::type Phi (ARGS &&... args)
proximal::WeightedL2Ball< Scalar > & l2ball_proximal ()
Proximal of the L2 ball.
TVPrimalDual &::type Psi (ARGS &&... args)
SOPT_MACRO (epsilon, l2ball, WeightedL2Ball)
SOPT_MACRO (weights, l2ball, WeightedL2Ball)
TVPrimalDual< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
TVPrimalDual< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
TVPrimalDual< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
Detailed Description
template<class SCALAR>
class sopt::algorithm::TVPrimalDual< SCALAR >
Definition at line 19 of file tv_primal_dual.h.
Member Typedef Documentation
Real
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::Real = typename PD::Real
Definition at line 26 of file tv_primal_dual.h.
Scalar
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::Scalar = typename PD::Scalar
Definition at line 25 of file tv_primal_dual.h.
t_Constraint
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::t_Constraint = typename PD::t_Constraint
Definition at line 32 of file tv_primal_dual.h.
t_IsConverged
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::t_IsConverged = typename PD::t_IsConverged
Definition at line 31 of file tv_primal_dual.h.
t_LinearTransform
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::t_LinearTransform = typename PD::t_LinearTransform
Definition at line 28 of file tv_primal_dual.h.
t_Proximal
template<class SCALAR > template<class T > using sopt::algorithm::TVPrimalDual< SCALAR >::t_Proximal = std::function<void(t_Vector &, const T &, const t_Vector &)>
Definition at line 30 of file tv_primal_dual.h.
t_Random_Updater
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::t_Random_Updater = typename PD::t_Random_Updater
Definition at line 33 of file tv_primal_dual.h.
t_Vector
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::t_Vector = typename PD::t_Vector
Definition at line 27 of file tv_primal_dual.h.
value_type
template<class SCALAR > using sopt::algorithm::TVPrimalDual< SCALAR >::value_type = typename PD::value_type
Definition at line 24 of file tv_primal_dual.h.
Constructor & Destructor Documentation
TVPrimalDual()
template<class SCALAR > template<class DERIVED > sopt::algorithm::TVPrimalDual< SCALAR >::TVPrimalDual (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for PD
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 51 of file tv_primal_dual.h.
       : tv_proximal_([](t_Vector &out, const Real &gamma, const t_Vector &x) {
           proximal::tv_norm<t_Vector, t_Vector>(out, gamma, x);
         }),
         tv_proximal_weighted_([](t_Vector &out, const Vector<Real> &gamma, const t_Vector &x) {
           proximal::tv_norm<t_Vector, t_Vector, Vector<Real>>(out, gamma, x);
         }),
         tv_proximal_weights_(Vector<Real>::Ones(1)),
         l2ball_proximal_(1e0),
         residual_tolerance_(1e-4),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         sigma_(1),
         tau_(0.5),
         gamma_(0.5),
         update_scale_(1),
         precondition_stepsize_(0.5),
         precondition_weights_(t_Vector::Ones(target.size())),
         precondition_iters_(0),
         xi_(1),
         rho_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         Psi_(linear_transform_identity<Scalar>()),
         random_measurement_updater_([]() { return true; }),
         random_wavelet_updater_([]() { return true; }),
         target_(target) {}
~TVPrimalDual()
template<class SCALAR > virtual sopt::algorithm::TVPrimalDual< SCALAR >::~TVPrimalDual () inline virtual
Definition at line 81 of file tv_primal_dual.h.
 {}
Member Function Documentation
is_converged()
template<class SCALAR > TVPrimalDual<Scalar>& sopt::algorithm::TVPrimalDual< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 265 of file tv_primal_dual.h.
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
l2ball_proximal()
template<class SCALAR > proximal::WeightedL2Ball<Scalar>& sopt::algorithm::TVPrimalDual< SCALAR >::l2ball_proximal () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 224 of file tv_primal_dual.h.
 { return l2ball_proximal_; }
objective_convergence()
template<class SCALAR > TVPrimalDual<Scalar>& sopt::algorithm::TVPrimalDual< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 261 of file tv_primal_dual.h.
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
operator()() [1/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::TVPrimalDual< SCALAR >::operator() () const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 202 of file tv_primal_dual.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x,
                                                    PD::initial_guess(target(), Phi(), nu()));
     return result;
   }
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::TVPrimalDual< SCALAR >::Phi(), sopt::algorithm::TVPrimalDual< SCALAR >::target(), and sopt::algorithm::TVPrimalDual< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::TVPrimalDual< SCALAR >::operator()().
operator()() [2/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::TVPrimalDual< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PD.
Definition at line 209 of file tv_primal_dual.h.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
References sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, and sopt::algorithm::TVPrimalDual< SCALAR >::DiagnosticAndResult::x.
operator()() [3/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::TVPrimalDual< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 194 of file tv_primal_dual.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
References sopt::algorithm::TVPrimalDual< SCALAR >::DiagnosticAndResult::x.
operator()() [4/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::TVPrimalDual< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 189 of file tv_primal_dual.h.
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
References sopt::algorithm::TVPrimalDual< SCALAR >::operator()().
operator()() [5/7]
template<class SCALAR > Diagnostic sopt::algorithm::TVPrimalDual< SCALAR >::operator() (t_Vector & out) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
Definition at line 171 of file tv_primal_dual.h.
{
     return operator()(out, PD::initial_guess(target(), Phi(), nu()));
   }
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::TVPrimalDual< SCALAR >::operator()(), sopt::algorithm::TVPrimalDual< SCALAR >::Phi(), and sopt::algorithm::TVPrimalDual< SCALAR >::target().
operator()() [6/7]
template<class SCALAR > Diagnostic sopt::algorithm::TVPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 183 of file tv_primal_dual.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::TVPrimalDual< SCALAR >::operator()().
operator()() [7/7]
template<class SCALAR > Diagnostic sopt::algorithm::TVPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 177 of file tv_primal_dual.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::TVPrimalDual< SCALAR >::operator()().
Phi()
template<class SCALAR > TVPrimalDual& ::type sopt::algorithm::TVPrimalDual< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 217 of file tv_primal_dual.h.
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by main(), and sopt::algorithm::TVPrimalDual< SCALAR >::operator()().
Psi()
template<class SCALAR > TVPrimalDual& ::type sopt::algorithm::TVPrimalDual< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 228 of file tv_primal_dual.h.
{
     Psi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by main().
residual_convergence()
template<class SCALAR > TVPrimalDual<Scalar>& sopt::algorithm::TVPrimalDual< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 257 of file tv_primal_dual.h.
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
Referenced by main().
SOPT_MACRO() [1/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (epsilon , l2ball , WeightedL2Ball)
SOPT_MACRO() [2/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (gamma , Real)
gamma parameter
SOPT_MACRO() [3/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [4/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [5/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (l2ball_proximal , proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO() [6/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [7/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [8/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [9/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (positivity_constraint , bool)
Apply positivity constraint.
SOPT_MACRO() [10/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (precondition_iters , t_uint)
precondition iterations parameter
SOPT_MACRO() [11/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (precondition_stepsize , Real)
precondtion step size parameter
SOPT_MACRO() [12/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (precondition_weights , t_Vector)
precondition weights parameter
SOPT_MACRO() [13/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (Psi , t_LinearTransform)
Wavelet operator.
SOPT_MACRO() [14/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (random_measurement_updater , t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO() [15/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (random_wavelet_updater , t_Random_Updater)
lambda that determines if to update wavelets
SOPT_MACRO() [16/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (real_constraint , bool)
Apply real constraint.
SOPT_MACRO() [17/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [18/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [19/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [20/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (rho , Real)
rho parameter
SOPT_MACRO() [21/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (sigma , Real)
sigma parameter
SOPT_MACRO() [22/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (tau , Real)
tau parameter
SOPT_MACRO() [23/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (tv_proximal , t_Proximal< Real >)
The tv prox functioning as f.
SOPT_MACRO() [24/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (tv_proximal_weighted , t_Proximal< Vector< Real >>)
The tv prox with weights functioning as f.
SOPT_MACRO() [25/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (tv_proximal_weights , Vector< Real >)
The tv prox weights functioning.
SOPT_MACRO() [26/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (update_scale , Real)
update parameter
SOPT_MACRO() [27/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (weights , l2ball , WeightedL2Ball)
SOPT_MACRO() [28/28]
template<class SCALAR > sopt::algorithm::TVPrimalDual< SCALAR >::SOPT_MACRO (xi , Real)
xi parameter
target() [1/2]
template<class SCALAR > const t_Vector& sopt::algorithm::TVPrimalDual< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 161 of file tv_primal_dual.h.
 { return target_; }
Referenced by sopt::algorithm::TVPrimalDual< SCALAR >::operator()(), and sopt::algorithm::TVPrimalDual< SCALAR >::target().
target() [2/2]
template<class SCALAR > template<class DERIVED > TVPrimalDual<Scalar>& sopt::algorithm::TVPrimalDual< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 164 of file tv_primal_dual.h.
{
     target_ = target;
     return *this;
   }
References sopt::algorithm::TVPrimalDual< SCALAR >::target().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/tv_primal_dual.h