SOPT: sopt::wavelets::Wavelet Class Reference
sopt::wavelets::Wavelet Class Reference
Performs direct and indirect wavelet transforms.
#include <wavelets.h>
Public Member Functions
virtual ~Wavelet ()
Destructor.
template<class T0 >
auto direct (Eigen::ArrayBase< T0 > const &signal) const -> decltype(direct_transform(signal, 1, *this))
Direct transform.
template<class T0 , class T1 >
auto direct (Eigen::ArrayBase< T1 > &coefficients, Eigen::ArrayBase< T0 > const &signal) const -> decltype(direct_transform(coefficients, signal, 1, *this))
Direct transform.
template<class T0 , class T1 >
auto direct (Eigen::ArrayBase< T1 > &&coefficients, Eigen::ArrayBase< T0 > const &signal) const -> decltype(direct_transform(coefficients, signal, 1, *this))
Direct transform.
template<class T0 >
auto indirect (Eigen::ArrayBase< T0 > const &coefficients) const -> decltype(indirect_transform(coefficients, 1, *this))
Indirect transform.
template<class T0 , class T1 >
auto indirect (Eigen::ArrayBase< T1 > const &coefficients, Eigen::ArrayBase< T0 > &signal) const -> decltype(indirect_transform(coefficients, signal, 1, *this))
Indirect transform.
template<class T0 , class T1 >
auto indirect (Eigen::ArrayBase< T1 > const &coeffs, Eigen::ArrayBase< T0 > &&signal) const -> decltype(indirect_transform(coeffs, signal, 1, *this))
Indirect transform.
t_uint levels () const
Number of levels over which to do transform.
void levels (t_uint l)
Sets number of levels over which to do transform.
Public Member Functions inherited from sopt::wavelets::WaveletData
WaveletData (std::initializer_list< t_scalar > const &coefs)
Constructs from initializers.
WaveletData (t_vector const &coefs)
Constructs from vector.
Friends
Wavelet factory (const std::string &name, t_uint nlevels)
Creates a wavelet transform object.
Additional Inherited Members
Public Types inherited from sopt::wavelets::WaveletData
using t_scalar = t_real
Type of the underlying scalar.
using t_vector = Array< t_real >
Type of the underlying vector.
Public Attributes inherited from sopt::wavelets::WaveletData
const t_vector coefficients
Wavelet coefficient per-se.
struct sopt::wavelets::WaveletData::DirectFilter direct_filter
struct {
t_vector low_even
High-pass filter for direct transform.
t_vector low_odd
t_vector high_even
t_vector high_odd
} indirect_filter
Holds filters for indirect transform.
Detailed Description
Performs direct and indirect wavelet transforms.
Definition at line 21 of file wavelets.h.
Constructor & Destructor Documentation
~Wavelet()
virtual sopt::wavelets::Wavelet::~Wavelet () inline virtual
Destructor.
Definition at line 30 of file wavelets.h.
 {}
Member Function Documentation
direct() [1/3]
template<class T0 > auto sopt::wavelets::Wavelet::direct (Eigen::ArrayBase< T0 > const & signal) const -> decltype(direct_transform(signal, 1, *this)) inline
Direct transform.
Parameters
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Returns
wavelet coefficients
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 52 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(signal);
     return direct_transform(signal, levels(), *this);
   }
References sopt::wavelets::direct_transform(), levels(), and SOPT_WAVELET_MACRO_MULTIPLE.
direct() [2/3]
template<class T0 , class T1 > auto sopt::wavelets::Wavelet::direct (Eigen::ArrayBase< T1 > && coefficients, Eigen::ArrayBase< T0 > const & signal) const -> decltype(direct_transform(coefficients, signal, 1, *this)) inline
Direct transform.
Parameters
[in,out] coefficients Output wavelet coefficients. Must be of the same size and type as the input.
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data. This version allows non-constant Eigen expressions to be passe on without the ugly const_cast of the cannonical approach.
Definition at line 83 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(signal);
     SOPT_WAVELET_MACRO_EQUAL_SIZE(coefficients, signal);
     return direct_transform(coefficients, signal, levels(), *this);
   }
References sopt::wavelets::WaveletData::coefficients, sopt::wavelets::direct_transform(), levels(), SOPT_WAVELET_MACRO_EQUAL_SIZE, and SOPT_WAVELET_MACRO_MULTIPLE.
direct() [3/3]
template<class T0 , class T1 > auto sopt::wavelets::Wavelet::direct (Eigen::ArrayBase< T1 > & coefficients, Eigen::ArrayBase< T0 > const & signal) const -> decltype(direct_transform(coefficients, signal, 1, *this)) inline
Direct transform.
Parameters
[in,out] coefficients Output wavelet coefficients. Must be of the same size and type as the input.
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 66 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(signal);
     SOPT_WAVELET_MACRO_EQUAL_SIZE(coefficients, signal);
     return direct_transform(coefficients, signal, levels(), *this);
   }
References sopt::wavelets::WaveletData::coefficients, sopt::wavelets::direct_transform(), levels(), SOPT_WAVELET_MACRO_EQUAL_SIZE, and SOPT_WAVELET_MACRO_MULTIPLE.
indirect() [1/3]
template<class T0 > auto sopt::wavelets::Wavelet::indirect (Eigen::ArrayBase< T0 > const & coefficients) const -> decltype(indirect_transform(coefficients, 1, *this)) inline
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 95 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(coefficients);
     return indirect_transform(coefficients, levels(), *this);
   }
References sopt::wavelets::WaveletData::coefficients, sopt::wavelets::indirect_transform(), levels(), and SOPT_WAVELET_MACRO_MULTIPLE.
indirect() [2/3]
template<class T0 , class T1 > auto sopt::wavelets::Wavelet::indirect (Eigen::ArrayBase< T1 > const & coefficients, Eigen::ArrayBase< T0 > & signal) const -> decltype(indirect_transform(coefficients, signal, 1, *this)) inline
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d
[in,out] signal Reconstructed signal. Must be of the same size and type as the input.
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 106 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(coefficients);
     SOPT_WAVELET_MACRO_EQUAL_SIZE(signal, coefficients);
     return indirect_transform(coefficients, signal, levels(), *this);
   }
References sopt::wavelets::WaveletData::coefficients, sopt::wavelets::indirect_transform(), levels(), SOPT_WAVELET_MACRO_EQUAL_SIZE, and SOPT_WAVELET_MACRO_MULTIPLE.
indirect() [3/3]
template<class T0 , class T1 > auto sopt::wavelets::Wavelet::indirect (Eigen::ArrayBase< T1 > const & coeffs, Eigen::ArrayBase< T0 > && signal) const -> decltype(indirect_transform(coeffs, signal, 1, *this)) inline
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d
[in,out] signal Reconstructed signal. Must be of the same size and type as the input.
Supports 1 and 2 dimensional tranforms for real and complex data. This version allows non-constant Eigen expressions to be passe on without the ugly const_cast of the cannonical approach.
Definition at line 120 of file wavelets.h.
{
     SOPT_WAVELET_MACRO_MULTIPLE(coeffs);
     SOPT_WAVELET_MACRO_EQUAL_SIZE(signal, coeffs);
     return indirect_transform(coeffs, signal, levels(), *this);
   }
References sopt::wavelets::indirect_transform(), levels(), SOPT_WAVELET_MACRO_EQUAL_SIZE, and SOPT_WAVELET_MACRO_MULTIPLE.
levels() [1/2]
t_uint sopt::wavelets::Wavelet::levels () const inline
Number of levels over which to do transform.
Definition at line 129 of file wavelets.h.
 { return levels_; }
Referenced by direct(), and indirect().
levels() [2/2]
void sopt::wavelets::Wavelet::levels (t_uint l) inline
Sets number of levels over which to do transform.
Definition at line 131 of file wavelets.h.
 { levels_ = l; }
Friends And Related Function Documentation
factory
Wavelet factory (const std::string & name, t_uint nlevels) friend
Creates a wavelet transform object.
Definition at line 8 of file wavelets.cc.
{
   if (name == "dirac" or name == "Dirac") {
     SOPT_MEDIUM_LOG("Creating Dirac Wavelet");
     return Wavelet(daubechies_data(1), 0);
   }
   if (name.substr(0, 2) == "DB" or name.substr(0, 2) == "db") {
     std::istringstream sstr(name.substr(2, name.size() - 2));
     t_uint l(0);
     sstr >> l;
     SOPT_MEDIUM_LOG("Creating Daubechies Wavelet {}, level {}", l, nlevels);
     return Wavelet(daubechies_data(l), nlevels);
   }
   // Unknown input wavelet
   throw std::exception();
 }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/wavelets/wavelets.h