SOPT: sopt::proximal::L1TightFrame< SCALAR > Class Template Reference
sopt::proximal::L1TightFrame< SCALAR > Class Template Reference
L1 proximal, including linear transform.
#include <l1_proximal.h>
Public Types
typedef SCALAR Scalar
Underlying scalar type.
typedef real_type< Scalar >::type Real
Underlying real scalar type.
Public Member Functions
L1TightFrame ()
SOPT_MACRO (Psi, LinearTransform< Vector< Scalar >>)
Linear transform applied to input prior to L1 norm.
SOPT_MACRO (nu, Real)
Bound on the squared norm of the operator Ψ
const Vector< Real > & weights () const
Weights of the l1 norm.
template<class T >
L1TightFrame< Scalar > & weights (Eigen::MatrixBase< T > const &w)
Weights of the l1 norm.
L1TightFrame< Scalar > & weights (Real const &value)
Set weights to a single value.
L1TightFrame &::type Psi (ARGS &&... args)
template<class T0 , class T1 >
std::enable_if< is_complex< Scalar >::value==is_complex< typename T0::Scalar >::value and is_complex< Scalar >::value==is_complex< typename T1::Scalar >::value >::type operator() (Eigen::MatrixBase< T0 > &out, Real gamma, Eigen::MatrixBase< T1 > const &x) const
Computes proximal for given γ
template<class T0 >
ProximalExpression< L1TightFrame< Scalar > const &, T0 > operator() (Real const &gamma, Eigen::MatrixBase< T0 > const &x) const
Lazy version.
template<class T0 , class T1 >
std::enable_if< is_complex< Scalar >::value==is_complex< typename T0::Scalar >::value and is_complex< Scalar >::value==is_complex< typename T1::Scalar >::value, Real >::type objective (Eigen::MatrixBase< T0 > const &x, Eigen::MatrixBase< T1 > const &z, Real const &gamma) const
Detailed Description
template<class SCALAR>
class sopt::proximal::L1TightFrame< SCALAR >
L1 proximal, including linear transform.
This function computes the prox operator of the l1 norm for the input vector \(x\). It solves the problem:
\[ min_{z} 0.5||x - z||_2^2 + γ ||Ψ^† z||_w1 \]
where \(Ψ \in C^{N_x \times N_r} \) is the sparsifying operator, and
\[|| ||_w1\]
is the weighted L1 norm.
Definition at line 26 of file l1_proximal.h.
Member Typedef Documentation
Real
template<class SCALAR > typedef real_type<Scalar>::type sopt::proximal::L1TightFrame< SCALAR >::Real
Underlying real scalar type.
Definition at line 31 of file l1_proximal.h.
Scalar
template<class SCALAR > typedef SCALAR sopt::proximal::L1TightFrame< SCALAR >::Scalar
Underlying scalar type.
Definition at line 29 of file l1_proximal.h.
Constructor & Destructor Documentation
L1TightFrame()
template<class SCALAR > sopt::proximal::L1TightFrame< SCALAR >::L1TightFrame () inline
Definition at line 47 of file l1_proximal.h.
       : Psi_(linear_transform_identity<Scalar>()), nu_(1e0), weights_(Vector<Real>::Ones(1)) {}
Member Function Documentation
objective()
template<class SCALAR > template<class T0 , class T1 > std::enable_if< is_complex< SCALAR >::value==is_complex< typename T0::Scalar >::value and is_complex< SCALAR >::value==is_complex< typename T1::Scalar >::value, typename real_type< SCALAR >::type >::type sopt::proximal::L1TightFrame< SCALAR >::objective (Eigen::MatrixBase< T0 > const & x, Eigen::MatrixBase< T1 > const & z, Real const & gamma) const
\[ 0.5||x - z||_2^2 + γ||Ψ^† z||_w1 \]
Definition at line 143 of file l1_proximal.h.
{
 #ifdef SOPT_MPI
   auto const adj =
       gamma * sopt::mpi::l1_norm((Psi().adjoint() * z).eval(), weights(), adjoint_space_comm());
   auto const dir = direct_space_comm().all_sum_all(0.5 * (x - z).squaredNorm());
   return adj + dir;
 #else
   return 0.5 * (x - z).squaredNorm() +
          gamma * sopt::l1_norm((Psi().adjoint() * z).eval(), weights());
 #endif
 }
Referenced by sopt::proximal::L1< SCALAR >::Breaker::Breaker(), and sopt::proximal::L1< SCALAR >::Breaker::operator()().
operator()() [1/2]
template<class SCALAR > template<class T0 , class T1 > std::enable_if< is_complex< SCALAR >::value==is_complex< typename T0::Scalar >::value and is_complex< SCALAR >::value==is_complex< typename T1::Scalar >::value >::type sopt::proximal::L1TightFrame< SCALAR >::operator() (Eigen::MatrixBase< T0 > & out, Real gamma, Eigen::MatrixBase< T1 > const & x) const
Computes proximal for given γ
Definition at line 128 of file l1_proximal.h.
{
   Vector<Scalar> const psit_x = Psi().adjoint() * x;
   if (weights().size() == 1)
     out = Psi() * (soft_threshhold(psit_x, nu() * gamma * weights()(0)) - psit_x) / nu() + x;
   else
     out = Psi() * (soft_threshhold(psit_x, nu() * gamma * weights()) - psit_x) / nu() + x;
   SOPT_LOW_LOG("Prox L1: objective = {}", objective(x, out, gamma));
 }
Referenced by sopt::proximal::L1< Scalar >::tight_frame().
operator()() [2/2]
template<class SCALAR > template<class T0 > ProximalExpression<L1TightFrame<Scalar> const &, T0> sopt::proximal::L1TightFrame< SCALAR >::operator() (Real const & gamma, Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 106 of file l1_proximal.h.
{
     return {*this, gamma, x};
   }
Psi()
template<class SCALAR > L1TightFrame& ::type sopt::proximal::L1TightFrame< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 93 of file l1_proximal.h.
{
     Psi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Referenced by sopt::proximal::L1< Scalar >::Psi().
SOPT_MACRO() [1/2]
template<class SCALAR > sopt::proximal::L1TightFrame< SCALAR >::SOPT_MACRO (nu , Real)
Bound on the squared norm of the operator Ψ
SOPT_MACRO() [2/2]
template<class SCALAR > sopt::proximal::L1TightFrame< SCALAR >::SOPT_MACRO (Psi , LinearTransform< Vector< Scalar >>)
Linear transform applied to input prior to L1 norm.
weights() [1/3]
template<class SCALAR > const Vector<Real>& sopt::proximal::L1TightFrame< SCALAR >::weights () const inline
Weights of the l1 norm.
Definition at line 74 of file l1_proximal.h.
 { return weights_; }
Referenced by sopt::proximal::L1< Scalar >::weights().
weights() [2/3]
template<class SCALAR > template<class T > L1TightFrame<Scalar>& sopt::proximal::L1TightFrame< SCALAR >::weights (Eigen::MatrixBase< T > const & w) inline
Weights of the l1 norm.
Definition at line 77 of file l1_proximal.h.
{
     if ((w.array() < 0e0).any()) SOPT_THROW("Weights cannot be negative");
     if (w.stableNorm() < 1e-12) SOPT_THROW("Weights cannot be null");
     weights_ = w;
     return *this;
   }
weights() [3/3]
template<class SCALAR > L1TightFrame<Scalar>& sopt::proximal::L1TightFrame< SCALAR >::weights (Real const & value) inline
Set weights to a single value.
Definition at line 85 of file l1_proximal.h.
{
     if (value <= 0e0) SOPT_THROW("Weight cannot be negative or null");
     weights_ = Vector<Real>::Ones(1) * value;
     return *this;
   }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/l1_proximal.h