SOPT: sopt::algorithm::Reweighted< ALGORITHM > Class Template Reference
sopt::algorithm::Reweighted< ALGORITHM > Class Template Reference
L0-approximation algorithm, through reweighting.
#include <reweighted.h>
Classes
struct ReweightedResult
output from running reweighting scheme
Public Types
typedef ALGORITHM Algorithm
Inner-loop algorithm.
typedef Algorithm::Scalar Scalar
Scalar type.
typedef real_type< Scalar >::type Real
Real type.
typedef Vector< Real > WeightVector
Weight vector type.
typedef Algorithm::t_Vector XVector
Type of then underlying vectors.
typedef ConvergenceFunction< Scalar > t_IsConverged
Type of the convergence function.
typedef std::function< XVector(Algorithm const &, XVector const &)> t_Reweightee
Type of the function that is subject to reweighting.
typedef std::function< void(Algorithm &, WeightVector const &)> t_SetWeights
Type of the function to set weights.
typedef std::function< Real(Real)> t_DeltaUpdate
Function to update delta at each turn.
Public Member Functions
Reweighted (Algorithm const &algo, t_SetWeights const &setweights, t_Reweightee const &reweightee)
Algorithm & algorithm ()
Underlying "inner-loop" algorithm.
Algorithm const & algorithm () const
Underlying "inner-loop" algorithm.
Reweighted< Algorithm > & algorithm (Algorithm const &algo)
Sets the underlying "inner-loop" algorithm.
Reweighted< Algorithm > & algorithm (Algorithm &&algo)
Sets the underlying "inner-loop" algorithm.
t_SetWeights const & set_weights () const
Function to reset the weights in the algorithm.
Reweighted< Algorithm > & set_weights (t_SetWeights const &setweights) const
Function to reset the weights in the algorithm.
void set_weights (Algorithm &algo, WeightVector const &weights) const
Sets the weights on the underlying algorithm.
Reweighted< Algorithm > & reweightee (t_Reweightee const &rw)
t_Reweightee const & reweightee () const
Function that needs to be reweighted.
XVector reweightee (XVector const &x) const
Forwards to the reweightee function.
t_uint itermax () const
Maximum number of reweighted iterations.
Reweighted & itermax (t_uint i)
Real min_delta () const
Lower limit for delta.
Reweighted & min_delta (Real min_delta)
t_IsConverged const & is_converged () const
Checks convergence of the reweighting scheme.
Reweighted & is_converged (t_IsConverged const &convergence)
bool is_converged (XVector const &x) const
template<class INPUT >
std::enable_if< not(std::is_same< INPUT, typename Algorithm::DiagnosticAndResult >::value or std::is_same< INPUT, ReweightedResult >::value), ReweightedResult >::type operator() (INPUT const &input) const
Performs reweighting.
ReweightedResult operator() () const
Performs reweighting.
ReweightedResult operator() (typename Algorithm::DiagnosticAndResult const &warm) const
Reweighted algorithm, from prior call to inner-algorithm.
ReweightedResult operator() (ReweightedResult const &warm) const
Reweighted algorithm, from prior call to reweighting algorithm.
Real update_delta (Real delta) const
Updates delta.
t_DeltaUpdate const & update_delta () const
Updates delta.
Reweighted< Algorithm > update_delta (t_DeltaUpdate const &ud) const
Updates delta.
Detailed Description
template<class ALGORITHM>
class sopt::algorithm::Reweighted< ALGORITHM >
L0-approximation algorithm, through reweighting.
This algorithm approximates \(min_x ||Ψ^Tx||_0 + f(x)\) by solving the set of problems \(j\), \(min_x ||W_jΨ^Tx||_1 + f(x)\) where the diagonal matrix \(W_j\) is set using the results from \(j-1\): \(δ_j W_j^{-1} = δ_j + ||W_{j-1}Ψ^T||_1\). \(δ_j\) prevents division by zero. It is a series which converges to zero. By default, \(δ_{j+1}=0.1δ_j\).
The algorithm proceeds needs three forms of input:
the inner algorithm, e.g. ImagingProximalADMM
a function returning Ψ^Tx given x
a function to modify the inner algorithm with new weights
Definition at line 10 of file reweighted.h.
Member Typedef Documentation
Algorithm
template<class ALGORITHM> typedef ALGORITHM sopt::algorithm::Reweighted< ALGORITHM >::Algorithm
Inner-loop algorithm.
Definition at line 33 of file reweighted.h.
Real
template<class ALGORITHM> typedef real_type<Scalar>::type sopt::algorithm::Reweighted< ALGORITHM >::Real
Real type.
Definition at line 37 of file reweighted.h.
Scalar
template<class ALGORITHM> typedef Algorithm::Scalar sopt::algorithm::Reweighted< ALGORITHM >::Scalar
Scalar type.
Definition at line 35 of file reweighted.h.
t_DeltaUpdate
template<class ALGORITHM> typedef std::function<Real(Real)> sopt::algorithm::Reweighted< ALGORITHM >::t_DeltaUpdate
Function to update delta at each turn.
Definition at line 50 of file reweighted.h.
t_IsConverged
template<class ALGORITHM> typedef ConvergenceFunction<Scalar> sopt::algorithm::Reweighted< ALGORITHM >::t_IsConverged
Type of the convergence function.
Definition at line 43 of file reweighted.h.
t_Reweightee
template<class ALGORITHM> typedef std::function<XVector(Algorithm const &, XVector const &)> sopt::algorithm::Reweighted< ALGORITHM >::t_Reweightee
Type of the function that is subject to reweighting.
E.g. \(Ψ^Tx\). Note that l1-norm is not applied here.
Definition at line 46 of file reweighted.h.
t_SetWeights
template<class ALGORITHM> typedef std::function<void(Algorithm &, WeightVector const &)> sopt::algorithm::Reweighted< ALGORITHM >::t_SetWeights
Type of the function to set weights.
Definition at line 48 of file reweighted.h.
WeightVector
template<class ALGORITHM> typedef Vector<Real> sopt::algorithm::Reweighted< ALGORITHM >::WeightVector
Weight vector type.
Definition at line 39 of file reweighted.h.
XVector
template<class ALGORITHM> typedef Algorithm::t_Vector sopt::algorithm::Reweighted< ALGORITHM >::XVector
Type of then underlying vectors.
Definition at line 41 of file reweighted.h.
Constructor & Destructor Documentation
Reweighted()
template<class ALGORITHM> sopt::algorithm::Reweighted< ALGORITHM >::Reweighted (Algorithm const & algo, t_SetWeights const & setweights, t_Reweightee const & reweightee) inline
Definition at line 66 of file reweighted.h.
       : algo_(algo),
         setweights_(setweights),
         reweightee_(reweightee),
         itermax_(std::numeric_limits<t_uint>::max()),
         min_delta_(0e0),
         is_converged_(),
         update_delta_([](Real delta) { return 1e-1 * delta; }) {}
Member Function Documentation
algorithm() [1/4]
template<class ALGORITHM> Algorithm& sopt::algorithm::Reweighted< ALGORITHM >::algorithm () inline
Underlying "inner-loop" algorithm.
Definition at line 76 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()(), and sopt::algorithm::Reweighted< ALGORITHM >::reweightee().
 { return algo_; }
algorithm() [2/4]
template<class ALGORITHM> Algorithm const& sopt::algorithm::Reweighted< ALGORITHM >::algorithm () const inline
Underlying "inner-loop" algorithm.
Definition at line 78 of file reweighted.h.
 { return algo_; }
algorithm() [3/4]
template<class ALGORITHM> Reweighted<Algorithm>& sopt::algorithm::Reweighted< ALGORITHM >::algorithm (Algorithm const & algo) inline
Sets the underlying "inner-loop" algorithm.
Definition at line 80 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo.
{
     algo_ = algo;
     return *this;
   }
algorithm() [4/4]
template<class ALGORITHM> Reweighted<Algorithm>& sopt::algorithm::Reweighted< ALGORITHM >::algorithm (Algorithm && algo) inline
Sets the underlying "inner-loop" algorithm.
Definition at line 85 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo.
{
     algo_ = std::move(algo);
     return *this;
   }
is_converged() [1/3]
template<class ALGORITHM> t_IsConverged const& sopt::algorithm::Reweighted< ALGORITHM >::is_converged () const inline
Checks convergence of the reweighting scheme.
Definition at line 126 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()().
 { return is_converged_; }
is_converged() [2/3]
template<class ALGORITHM> Reweighted& sopt::algorithm::Reweighted< ALGORITHM >::is_converged (t_IsConverged const & convergence) inline
Definition at line 127 of file reweighted.h.
{
     is_converged_ = convergence;
     return *this;
   }
is_converged() [3/3]
template<class ALGORITHM> bool sopt::algorithm::Reweighted< ALGORITHM >::is_converged (XVector const & x) const inline
Definition at line 131 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::is_converged(), and sopt::algorithm::Reweighted< ALGORITHM >::operator()().
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::is_converged().
 { return is_converged() ? is_converged()(x) : false; }
itermax() [1/2]
template<class ALGORITHM> t_uint sopt::algorithm::Reweighted< ALGORITHM >::itermax () const inline
Maximum number of reweighted iterations.
Definition at line 114 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()().
 { return itermax_; }
itermax() [2/2]
template<class ALGORITHM> Reweighted& sopt::algorithm::Reweighted< ALGORITHM >::itermax (t_uint i) inline
Definition at line 115 of file reweighted.h.
{
     itermax_ = i;
     return *this;
   }
min_delta() [1/2]
template<class ALGORITHM> Real sopt::algorithm::Reweighted< ALGORITHM >::min_delta () const inline
Lower limit for delta.
Definition at line 120 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::min_delta(), and sopt::algorithm::Reweighted< ALGORITHM >::operator()().
 { return min_delta_; }
min_delta() [2/2]
template<class ALGORITHM> Reweighted& sopt::algorithm::Reweighted< ALGORITHM >::min_delta (Real min_delta) inline
Definition at line 121 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::min_delta().
{
     min_delta_ = min_delta;
     return *this;
   }
operator()() [1/4]
template<class ALGORITHM > template<class INPUT > std::enable_if< not(std::is_same< INPUT, typename ALGORITHM::DiagnosticAndResult >::value or std::is_same< INPUT, typename Reweighted< ALGORITHM >::ReweightedResult >::value), typename Reweighted< ALGORITHM >::ReweightedResult >::type sopt::algorithm::Reweighted< ALGORITHM >::operator() (INPUT const & input) const
Performs reweighting.
This overload will compute an initial result without initial weights set to one.
Definition at line 179 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo, sopt::algorithm::Reweighted< ALGORITHM >::algorithm(), sopt::algorithm::Reweighted< ALGORITHM >::operator()(), and sopt::algorithm::Reweighted< ALGORITHM >::set_weights().
{
   Algorithm algo = algorithm();
   set_weights(algo, WeightVector::Ones(1));
   return operator()(algo(input));
 }
operator()() [2/4]
template<class ALGORITHM > Reweighted< ALGORITHM >::ReweightedResult sopt::algorithm::Reweighted< ALGORITHM >::operator() () const
Performs reweighting.
This overload will compute an initial result without initial weights set to one.
Definition at line 186 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo, sopt::algorithm::Reweighted< ALGORITHM >::algorithm(), and sopt::algorithm::Reweighted< ALGORITHM >::set_weights().
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::is_converged(), and sopt::algorithm::Reweighted< ALGORITHM >::operator()().
{
   Algorithm algo = algorithm();
   set_weights(algo, WeightVector::Ones(1));
   return operator()(algo());
 }
operator()() [3/4]
template<class ALGORITHM > Reweighted< ALGORITHM >::ReweightedResult sopt::algorithm::Reweighted< ALGORITHM >::operator() (typename Algorithm::DiagnosticAndResult const & warm) const
Reweighted algorithm, from prior call to inner-algorithm.
Definition at line 193 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo, sopt::algorithm::Reweighted< ALGORITHM >::operator()(), and sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::weights.
{
   ReweightedResult result;
   result.algo = warm;
   result.weights = WeightVector::Ones(1);
   return operator()(result);
 }
operator()() [4/4]
template<class ALGORITHM > Reweighted< ALGORITHM >::ReweightedResult sopt::algorithm::Reweighted< ALGORITHM >::operator() (ReweightedResult const & warm) const
Reweighted algorithm, from prior call to reweighting algorithm.
Definition at line 202 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo, sopt::algorithm::Reweighted< ALGORITHM >::algorithm(), sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::good, sopt::algorithm::Reweighted< ALGORITHM >::is_converged(), sopt::algorithm::Reweighted< ALGORITHM >::itermax(), sopt::algorithm::Reweighted< ALGORITHM >::min_delta(), sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::niters, sopt::algorithm::Reweighted< ALGORITHM >::reweightee(), sopt::algorithm::Reweighted< ALGORITHM >::set_weights(), SOPT_ERROR, SOPT_HIGH_LOG, SOPT_LOW_LOG, SOPT_MEDIUM_LOG, sopt::standard_deviation(), sopt::algorithm::Reweighted< ALGORITHM >::update_delta(), and sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::weights.
{
   SOPT_HIGH_LOG("Starting reweighted scheme");
   // Copies inner algorithm, so that operator() can be constant
   Algorithm algo(algorithm());
   ReweightedResult result(warm);
   auto delta = std::max(standard_deviation(reweightee(warm.algo.x)), min_delta());
   SOPT_LOW_LOG("-   Initial delta: {}", delta);
   for (result.niters = 0; result.niters < itermax(); ++result.niters) {
     SOPT_LOW_LOG("Reweigting iteration {}/{} ", result.niters, itermax());
     SOPT_LOW_LOG("  - delta: {}", delta);
     result.weights = delta / (delta + reweightee(result.algo.x).array().abs());
     set_weights(algo, result.weights);
     result.algo = algo(result.algo);
     if (is_converged(result.algo.x)) {
       SOPT_MEDIUM_LOG("Reweighting scheme did converge in {} iterations", result.niters);
       result.good = true;
       break;
     }
     delta = std::max(min_delta(), update_delta(delta));
   }
   // result is always good if no convergence function is defined
   if (not is_converged())
     result.good = true;
   else if (not result.good)
     SOPT_ERROR("Reweighting scheme did *not* converge in {} iterations", itermax());
   return result;
 }
reweightee() [1/3]
template<class ALGORITHM> Reweighted<Algorithm>& sopt::algorithm::Reweighted< ALGORITHM >::reweightee (t_Reweightee const & rw) inline
Function that needs to be reweighted
E.g. \(Ψ^Tx\). Note that l1-norm is not applied here.
Definition at line 104 of file reweighted.h.
{
     reweightee_ = rw;
     return *this;
   }
reweightee() [2/3]
template<class ALGORITHM> t_Reweightee const& sopt::algorithm::Reweighted< ALGORITHM >::reweightee () const inline
Function that needs to be reweighted.
Definition at line 109 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()(), and sopt::algorithm::reweighted().
 { return reweightee_; }
reweightee() [3/3]
template<class ALGORITHM> XVector sopt::algorithm::Reweighted< ALGORITHM >::reweightee (XVector const & x) const inline
Forwards to the reweightee function.
Definition at line 111 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::algorithm(), and sopt::algorithm::Reweighted< ALGORITHM >::reweightee().
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::reweightee().
 { return reweightee()(algorithm(), x); }
set_weights() [1/3]
template<class ALGORITHM> t_SetWeights const& sopt::algorithm::Reweighted< ALGORITHM >::set_weights () const inline
Function to reset the weights in the algorithm.
Definition at line 91 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()(), sopt::algorithm::reweighted(), and sopt::algorithm::Reweighted< ALGORITHM >::set_weights().
 { return setweights_; }
set_weights() [2/3]
template<class ALGORITHM> Reweighted<Algorithm>& sopt::algorithm::Reweighted< ALGORITHM >::set_weights (t_SetWeights const & setweights) const inline
Function to reset the weights in the algorithm.
Definition at line 93 of file reweighted.h.
{
     setweights_ = setweights;
     return *this;
   }
set_weights() [3/3]
template<class ALGORITHM> void sopt::algorithm::Reweighted< ALGORITHM >::set_weights (Algorithm & algo, WeightVector const & weights) const inline
Sets the weights on the underlying algorithm.
Definition at line 98 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::algo, sopt::algorithm::Reweighted< ALGORITHM >::set_weights(), and sopt::algorithm::Reweighted< ALGORITHM >::ReweightedResult::weights.
{
     return set_weights()(algo, weights);
   }
update_delta() [1/3]
template<class ALGORITHM> Real sopt::algorithm::Reweighted< ALGORITHM >::update_delta (Real delta) const inline
Updates delta.
Definition at line 149 of file reweighted.h.
References sopt::algorithm::Reweighted< ALGORITHM >::update_delta().
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::update_delta().
 { return update_delta()(delta); }
update_delta() [2/3]
template<class ALGORITHM> t_DeltaUpdate const& sopt::algorithm::Reweighted< ALGORITHM >::update_delta () const inline
Updates delta.
Definition at line 151 of file reweighted.h.
Referenced by sopt::algorithm::Reweighted< ALGORITHM >::operator()().
 { return update_delta_; }
update_delta() [3/3]
template<class ALGORITHM> Reweighted<Algorithm> sopt::algorithm::Reweighted< ALGORITHM >::update_delta (t_DeltaUpdate const & ud) const inline
Updates delta.
Definition at line 153 of file reweighted.h.
 { return update_delta_ = ud; }
The documentation for this class was generated from the following file:
/mydata/cpp/sopt/reweighted.h