SOPT: sopt::algorithm::SDMM< SCALAR > Class Template Reference
sopt::algorithm::SDMM< SCALAR > Class Template Reference
Simultaneous-direction method of the multipliers.
#include <sdmm.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Public Types
using value_type = SCALAR
Scalar type.
using Scalar = value_type
Scalar type.
using Real = typename real_type< Scalar >::type
Real type.
using t_Vector = Vector< SCALAR >
Type of then underlying vectors.
using t_LinearTransform = LinearTransform< t_Vector >
Type of the A and A^H operations.
using t_Proximal = ProximalFunction< SCALAR >
Type of the proximal functions.
using t_IsConverged = ConvergenceFunction< SCALAR >
Type of the convergence function.
Public Member Functions
SDMM ()
virtual ~SDMM ()
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
Gamma.
SOPT_MACRO (conjugate_gradient, ConjugateGradient)
Conjugate gradient.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SDMM< SCALAR > & conjugate_gradient (t_uint itermax, t_real tolerance)
Helps setup conjugate gradient.
template<class PROXIMAL , class T >
SDMM< SCALAR > & append (PROXIMAL proximal, T args)
Appends a proximal and linear transform.
template<class PROXIMAL >
SDMM< SCALAR > & append (PROXIMAL proximal)
Appends a proximal with identity as the linear transform.
template<class PROXIMAL , class L , class LADJOINT >
SDMM< SCALAR > & append (PROXIMAL proximal, L l, LADJOINT ladjoint)
Appends a proximal with the linear transform as pair of functions.
template<class PROXIMAL , class L , class LADJOINT >
SDMM< SCALAR > & append (PROXIMAL proximal, L l, LADJOINT ladjoint, std::array< t_int, 3 > sizes)
Appends a proximal with the linear transform as pair of functions.
template<class PROXIMAL , class L , class LADJOINT >
SDMM< SCALAR > & append (PROXIMAL proximal, L l, std::array< t_int, 3 > dsizes, LADJOINT ladjoint, std::array< t_int, 3 > isizes)
Appends a proximal with the linear transform as pair of functions.
Diagnostic operator() (t_Vector &out, t_Vector const &input) const
Implements SDMM.
DiagnosticAndResult operator() (t_Vector const &input) const
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to SDMM.
const std::vector< t_LinearTransform > & transforms () const
Linear transforms associated with each objective function.
std::vector< t_LinearTransform > & transforms ()
Linear transforms associated with each objective function.
const t_LinearTransform & transforms (t_uint i) const
Linear transform associated with a given objective function.
t_LinearTransform & transforms (t_uint i)
Linear transform associated with a given objective function.
const std::vector< t_Proximal > & proximals () const
Proximal of each objective function.
std::vector< t_Proximal > & proximals ()
Linear transforms associated with each objective function.
const t_Proximal & proximals (t_uint i) const
Proximal associated with a given objective function.
t_Proximal & proximals (t_uint i)
Proximal associated with a given objective function.
template<class T0 >
proximal::ProximalExpression< t_Proximal const &, T0 > proximals (t_uint i, Eigen::MatrixBase< T0 > const &x) const
Lazy call to specific proximal function.
t_uint size () const
Number of terms.
template<class T0 , class... T>
auto conjugate_gradient (T0 &&t0, T &&... args) const -> decltype(this->conjugate_gradient()(std::forward< T0 >(t0), std::forward< T >(args)...))
Forwards to internal conjugage gradient object.
bool is_converged (t_Vector const &x) const
Forwards to convergence function parameter.
Detailed Description
template<class SCALAR>
class sopt::algorithm::SDMM< SCALAR >
Simultaneous-direction method of the multipliers.
The algorithm is detailed in (doi) 10.1093/mnras/stu202.
Definition at line 23 of file sdmm.h.
Member Typedef Documentation
Real
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::Real = typename real_type<Scalar>::type
Real type.
Definition at line 43 of file sdmm.h.
Scalar
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::Scalar = value_type
Scalar type.
Definition at line 41 of file sdmm.h.
t_IsConverged
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::t_IsConverged = ConvergenceFunction<SCALAR>
Type of the convergence function.
Definition at line 51 of file sdmm.h.
t_LinearTransform
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::t_LinearTransform = LinearTransform<t_Vector>
Type of the A and A^H operations.
Definition at line 47 of file sdmm.h.
t_Proximal
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::t_Proximal = ProximalFunction<SCALAR>
Type of the proximal functions.
Definition at line 49 of file sdmm.h.
t_Vector
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::t_Vector = Vector<SCALAR>
Type of then underlying vectors.
Definition at line 45 of file sdmm.h.
value_type
template<class SCALAR > using sopt::algorithm::SDMM< SCALAR >::value_type = SCALAR
Scalar type.
Definition at line 39 of file sdmm.h.
Constructor & Destructor Documentation
SDMM()
template<class SCALAR > sopt::algorithm::SDMM< SCALAR >::SDMM () inline
Definition at line 53 of file sdmm.h.
       : itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         conjugate_gradient_(std::numeric_limits<t_uint>::max(), 1e-6),
         is_converged_([](t_Vector const &) { return false; }) {}
~SDMM()
template<class SCALAR > virtual sopt::algorithm::SDMM< SCALAR >::~SDMM () inline virtual
Definition at line 58 of file sdmm.h.
 {}
Member Function Documentation
append() [1/5]
template<class SCALAR > template<class PROXIMAL > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::append (PROXIMAL proximal) inline
Appends a proximal with identity as the linear transform.
Definition at line 97 of file sdmm.h.
{
     return append(proximal, linear_transform_identity<Scalar>());
   }
append() [2/5]
template<class SCALAR > template<class PROXIMAL , class L , class LADJOINT > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::append (PROXIMAL proximal, L l, LADJOINT ladjoint) inline
Appends a proximal with the linear transform as pair of functions.
Definition at line 102 of file sdmm.h.
{
     return append(proximal, linear_transform<t_Vector>(l, ladjoint));
   }
append() [3/5]
template<class SCALAR > template<class PROXIMAL , class L , class LADJOINT > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::append (PROXIMAL proximal, L l, LADJOINT ladjoint, std::array< t_int, 3 > sizes) inline
Appends a proximal with the linear transform as pair of functions.
Definition at line 107 of file sdmm.h.
{
     return append(proximal, linear_transform<t_Vector>(l, ladjoint, sizes));
   }
append() [4/5]
template<class SCALAR > template<class PROXIMAL , class L , class LADJOINT > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::append (PROXIMAL proximal, L l, std::array< t_int, 3 > dsizes, LADJOINT ladjoint, std::array< t_int, 3 > isizes) inline
Appends a proximal with the linear transform as pair of functions.
Definition at line 112 of file sdmm.h.
{
     return append(proximal, linear_transform<t_Vector>(l, dsizes, ladjoint, isizes));
   }
append() [5/5]
template<class SCALAR > template<class PROXIMAL , class T > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::append (PROXIMAL proximal, T args) inline
Appends a proximal and linear transform.
Definition at line 90 of file sdmm.h.
{
     proximals().emplace_back(proximal);
     transforms().emplace_back(linear_transform(args));
     return *this;
   }
Referenced by sopt::algorithm::SDMM< Scalar >::append(), and TEST_CASE().
conjugate_gradient() [1/2]
template<class SCALAR > template<class T0 , class... T> auto sopt::algorithm::SDMM< SCALAR >::conjugate_gradient (T0 && t0, T &&... args) const -> decltype(this->conjugate_gradient()(std::forward<T0>(t0), std::forward<T>(args)...)) inline
Forwards to internal conjugage gradient object.
Removes the need for ugly extra brackets.
Definition at line 166 of file sdmm.h.
{
     return conjugate_gradient()(std::forward<T0>(t0), std::forward<T>(args)...);
   }
conjugate_gradient() [2/2]
template<class SCALAR > SDMM<SCALAR>& sopt::algorithm::SDMM< SCALAR >::conjugate_gradient (t_uint itermax, t_real tolerance) inline
Helps setup conjugate gradient.
Definition at line 83 of file sdmm.h.
{
     conjugate_gradient_.itermax(itermax);
     conjugate_gradient_.tolerance(tolerance);
     return *this;
   }
Referenced by sopt::algorithm::SDMM< Scalar >::conjugate_gradient(), main(), and TEST_CASE().
is_converged()
template<class SCALAR > bool sopt::algorithm::SDMM< SCALAR >::is_converged (t_Vector const & x) const inline
Forwards to convergence function parameter.
Definition at line 172 of file sdmm.h.
 { return is_converged()(x); }
Referenced by sopt::algorithm::SDMM< Scalar >::is_converged(), main(), and SCENARIO().
operator()() [1/3]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::SDMM< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to SDMM.
Definition at line 128 of file sdmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x);
     return result;
   }
operator()() [2/3]
template<class SCALAR > SDMM< SCALAR >::Diagnostic sopt::algorithm::SDMM< SCALAR >::operator() (t_Vector & out, t_Vector const & input) const
Implements SDMM.
Follows Combettes and Pesquet "Proximal Splitting Methods in Signal Processing", arXiv:0912.3522v4 [math.OC] (2010), equation 65. See therein for notation
Definition at line 196 of file sdmm.h.
{
   sanity_check(input);
   bool convergence = false;
   t_uint niters(0);
   // Figures out where itermax or convergence reached
   auto const has_finished = [&convergence, &niters, this](t_Vector const &out) {
     convergence = is_converged(out);
     return niters >= itermax() or convergence;
   };
   SOPT_HIGH_LOG("Performing SDMM ");
   out = input;
   t_Vectors y(transforms().size());
   t_Vectors z(transforms().size());
   // Initial step replaces iteration update with initialization
   initialization(y, z, input);
   auto cg_diagnostic = solve_for_xn(out, y, z);
   while (not has_finished(out)) {
     SOPT_LOW_LOG("Iteration {}/{}. ", niters, itermax());
     // computes y and z from out and transforms
     update_directions(y, z, out);
     SOPT_LOW_LOG("   - sum z_ij = {}",
                  std::accumulate(z.begin(), z.end(), Scalar(0e0),
                                  [](Scalar const &a, t_Vector const &z) { return a + z.sum(); }));
     // computes x = L^-1 y
     cg_diagnostic = solve_for_xn(out, y, z);
     SOPT_LOW_LOG("   - CG Residual = {} in {}/{} iterations", cg_diagnostic.residual,
                  cg_diagnostic.niters, conjugate_gradient().itermax());
     ++niters;
   }
   return {niters, convergence, cg_diagnostic};
 }
operator()() [3/3]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::SDMM< SCALAR >::operator() (t_Vector const & input) const inline
Definition at line 122 of file sdmm.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, input);
     return result;
   }
proximals() [1/5]
template<class SCALAR > std::vector<t_Proximal>& sopt::algorithm::SDMM< SCALAR >::proximals () inline
Linear transforms associated with each objective function.
Definition at line 146 of file sdmm.h.
 { return proximals_; }
proximals() [2/5]
template<class SCALAR > const std::vector<t_Proximal>& sopt::algorithm::SDMM< SCALAR >::proximals () const inline
Proximal of each objective function.
Definition at line 144 of file sdmm.h.
 { return proximals_; }
Referenced by sopt::algorithm::SDMM< Scalar >::append(), sopt::algorithm::SDMM< Scalar >::proximals(), and sopt::algorithm::SDMM< Scalar >::size().
proximals() [3/5]
template<class SCALAR > t_Proximal& sopt::algorithm::SDMM< SCALAR >::proximals (t_uint i) inline
Proximal associated with a given objective function.
Definition at line 150 of file sdmm.h.
 { return proximals_[i]; }
proximals() [4/5]
template<class SCALAR > const t_Proximal& sopt::algorithm::SDMM< SCALAR >::proximals (t_uint i) const inline
Proximal associated with a given objective function.
Definition at line 148 of file sdmm.h.
 { return proximals_[i]; }
proximals() [5/5]
template<class SCALAR > template<class T0 > proximal::ProximalExpression<t_Proximal const &, T0> sopt::algorithm::SDMM< SCALAR >::proximals (t_uint i, Eigen::MatrixBase< T0 > const & x) const inline
Lazy call to specific proximal function.
Definition at line 153 of file sdmm.h.
{
     return {proximals()[i], gamma(), x};
   }
size()
template<class SCALAR > t_uint sopt::algorithm::SDMM< SCALAR >::size () const inline
Number of terms.
Definition at line 159 of file sdmm.h.
 { return proximals().size(); }
SOPT_MACRO() [1/4]
template<class SCALAR > sopt::algorithm::SDMM< SCALAR >::SOPT_MACRO (conjugate_gradient , ConjugateGradient)
Conjugate gradient.
SOPT_MACRO() [2/4]
template<class SCALAR > sopt::algorithm::SDMM< SCALAR >::SOPT_MACRO (gamma , Real)
Gamma.
SOPT_MACRO() [3/4]
template<class SCALAR > sopt::algorithm::SDMM< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [4/4]
template<class SCALAR > sopt::algorithm::SDMM< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
transforms() [1/4]
template<class SCALAR > std::vector<t_LinearTransform>& sopt::algorithm::SDMM< SCALAR >::transforms () inline
Linear transforms associated with each objective function.
Definition at line 137 of file sdmm.h.
 { return transforms_; }
transforms() [2/4]
template<class SCALAR > const std::vector<t_LinearTransform>& sopt::algorithm::SDMM< SCALAR >::transforms () const inline
Linear transforms associated with each objective function.
Definition at line 135 of file sdmm.h.
 { return transforms_; }
Referenced by sopt::algorithm::SDMM< Scalar >::append(), and TEST_CASE().
transforms() [3/4]
template<class SCALAR > t_LinearTransform& sopt::algorithm::SDMM< SCALAR >::transforms (t_uint i) inline
Linear transform associated with a given objective function.
Definition at line 141 of file sdmm.h.
 { return transforms_[i]; }
transforms() [4/4]
template<class SCALAR > const t_LinearTransform& sopt::algorithm::SDMM< SCALAR >::transforms (t_uint i) const inline
Linear transform associated with a given objective function.
Definition at line 139 of file sdmm.h.
 { return transforms_[i]; }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/sdmm.h