SOPT: sopt::logging::Log Class Reference
sopt::logging::Log Class Reference
Logging system for controlled & formatted writing to stdout.
#include <logging.h>
Public Types
enum Level {
trace = 0 , debug = 10 , info = 20 , warn = 30 ,
warning = 30 , error = 40 , critical = 50 , always = 50
}
Log priority levels.
using LogMap = std::map< std::string, Log >
Typedef for a collection of named logs.
using LevelMap = std::map< std::string, int >
Typedef for a collection of named log levels.
using ColorCodes = std::map< int, std::string >
Typedef for a collection of shell color codes, accessed by log level.
Public Member Functions
int getLevel () const
Get the priority level of this logger.
Log & setLevel (int level)
Set the priority level of this logger.
std::string getName () const
Get the name of this logger.
Log & setName (const std::string &name)
Set the name of this logger.
bool isActive (int level) const
Will this log level produce output on this logger at the moment?
Static Public Member Functions
static void setLevel (const std::string &name, int level)
Set the log levels.
static void setLevels (const LevelMap &logLevels)
static Log & getLog (const std::string &name)
static Level getLevelFromName (const std::string &level)
Get a log level enum from a string.
static std::string getLevelName (int level)
Get the std::string representation of a log level.
Static Public Attributes
static const int end_color {-10}
Special "level-like" code to end coloring.
Friends
std::ostream & operator<< (Log &log, int level)
The streaming operator can use Log's internals.
Detailed Description
Logging system for controlled & formatted writing to stdout.
Definition at line 14 of file logging.h.
Member Typedef Documentation
ColorCodes
using sopt::logging::Log::ColorCodes = std::map<int, std::string>
Typedef for a collection of shell color codes, accessed by log level.
Definition at line 36 of file logging.h.
LevelMap
using sopt::logging::Log::LevelMap = std::map<std::string, int>
Typedef for a collection of named log levels.
Definition at line 33 of file logging.h.
LogMap
using sopt::logging::Log::LogMap = std::map<std::string, Log>
Typedef for a collection of named logs.
Definition at line 30 of file logging.h.
Member Enumeration Documentation
Level
enum sopt::logging::Log::Level
Log priority levels.
Enumerator
trace
debug
info
warn
warning
error
critical
always
Definition at line 18 of file logging.h.
              {
     trace = 0,
     debug = 10,
     info = 20,
     warn = 30, warning = 30,
     error = 40,
     critical = 50, always = 50
   };
Member Function Documentation
getLevel()
int sopt::logging::Log::getLevel () const inline
Get the priority level of this logger.
Definition at line 90 of file logging.h.
{
     return _level;
   }
Referenced by getLog().
getLevelFromName()
Log::Level sopt::logging::Log::getLevelFromName (const std::string & level) static
Get a log level enum from a string.
Definition at line 138 of file logging.cc.
{
     if (level == "trace") return trace;
     if (level == "debug") return debug;
     if (level == "info") return info;
     if (level == "warn") return warn;
     if (level == "error") return error;
     if (level == "critical") return critical;
     SOPT_THROW("Couldn't create a log level from string '" + level + "'");
   }
References SOPT_THROW.
Referenced by sopt::logging::set_level().
getLevelName()
string sopt::logging::Log::getLevelName (int level) static
Get the std::string representation of a log level.
Definition at line 95 of file logging.cc.
{
     switch(level) {
     case trace:
       return "trace";
     case debug:
       return "debug";
     case info:
       return "info";
     case warn:
       return "warn";
     case error:
       return "error";
     case critical:
       return "critical";
     default:
       return "";
     }
   }
getLog()
Log & sopt::logging::Log::getLog (const std::string & name) static
Get a logger with the given name. The level will be taken from the "requestedLevels" static map or will be INFO by default.
Definition at line 57 of file logging.cc.
{
     auto theLog = existingLogs.find(name);
     if (theLog == existingLogs.end()) {
       int level = info;
       // Try running through all parent classes to find an existing level
       string tmpname = name;
       bool triedAllParents = false;
       while (! triedAllParents) {
         // Is there a default level?
         if (defaultLevels.find(tmpname) != defaultLevels.end()) {
           level = defaultLevels.find(tmpname)->second;
           break;
         }
         // Is there already such a logger? (NB. tmpname != name in later iterations)
         if (existingLogs.find(tmpname) != existingLogs.end()) {
           level = existingLogs.find(tmpname)->second.getLevel();
           break;
         }
         // Crop the string back to the next parent level
         size_t lastDot = tmpname.find_last_of(".");
         if (lastDot != string::npos) {
           tmpname = tmpname.substr(0, lastDot);
         } else {
           triedAllParents = true;
         }
       }
       // for (LevelMap::const_iterator l = defaultLevels.begin(); l != defaultLevels.end(); ++l) {
       //
       // }
       // emplace returns pair<iterator,bool>
       auto result = existingLogs.emplace(name, Log(name, level));
       theLog = result.first;
     }
     return theLog->second;
   }
References getLevel().
Referenced by sopt::logging::getLog().
getName()
std::string sopt::logging::Log::getName () const inline
Get the name of this logger.
Definition at line 107 of file logging.h.
{
     return _name;
   }
isActive()
bool sopt::logging::Log::isActive (int level) const inline
Will this log level produce output on this logger at the moment?
Definition at line 118 of file logging.h.
{
     return (level >= _level);
   }
setLevel() [1/2]
static void sopt::logging::Log::setLevel (const std::string & name, int level) static
Set the log levels.
Referenced by sopt::logging::set_level().
setLevel() [2/2]
Log& sopt::logging::Log::setLevel (int level) inline
Set the priority level of this logger.
Definition at line 95 of file logging.h.
{
     _level = level;
     return *this;
   }
setLevels()
void sopt::logging::Log::setLevels (const LevelMap & logLevels) static
Definition at line 49 of file logging.cc.
{
     for (LevelMap::const_iterator lev = logLevels.begin(); lev != logLevels.end(); ++lev) {
       defaultLevels[lev->first] = lev->second;
     }
     _updateLevels(defaultLevels, existingLogs);
   }
References sopt::logging::_updateLevels().
setName()
Log& sopt::logging::Log::setName (const std::string & name) inline
Set the name of this logger.
Definition at line 112 of file logging.h.
{
     _name = name;
     return *this;
   }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (Log & log, int level) friend
The streaming operator can use Log's internals.
Definition at line 190 of file logging.cc.
{
     if (log.isActive(level)) {
         if (level > Log::warning) {
             cerr << log.formatMessage(level, "");
             return cerr;
         } else {
             cout << log.formatMessage(level, "");
             return cout;
         }
     } else {
       static ostream devNull(nullptr);
       return devNull;
     }
   }
Member Data Documentation
end_color
const int sopt::logging::Log::end_color {-10} static
Special "level-like" code to end coloring.
Definition at line 26 of file logging.h.
The documentation for this class was generated from the following files:
/home/runner/work/sopt/sopt/cpp/sopt/logging.h
/home/runner/work/sopt/sopt/cpp/sopt/logging.cc