SOPT: sopt::proximal::L1< SCALAR > Class Template Reference
sopt::proximal::L1< SCALAR > Class Template Reference
L1 proximal, including linear transform.
#include <l1_proximal.h>
Classes
class Breaker
struct Diagnostic
How did calling L1 go?
struct DiagnosticAndResult
Result from calling L1.
class FistaMixing
class NoMixing
Public Types
typedef L1TightFrame< SCALAR >::Scalar Scalar
Underlying scalar type.
typedef L1TightFrame< SCALAR >::Real Real
Underlying real scalar type.
Public Member Functions
template<class T0 >
Diagnostic operator() (Eigen::MatrixBase< T0 > &out, Real gamma, Vector< Scalar > const &x) const
Computes proximal for given γ
template<class T0 >
DiagnosticAndResult operator() (Real const &gamma, Eigen::MatrixBase< T0 > const &x) const
Lazy version.
L1 ()
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations before bailing out.
SOPT_MACRO (tolerance, Real)
Tolerance criteria.
SOPT_MACRO (positivity_constraint, bool)
Whether to apply positivity constraints.
SOPT_MACRO (real_constraint, bool)
Whether the output should be constrained to be real.
SOPT_MACRO (fista_mixing, bool)
Whether to do fista mixing or not.
const Vector< Real > & weights () const
Weights of the l1 norm.
template<class T >
L1< Scalar > & weights (Eigen::MatrixBase< T > const &w)
Set weights to an array of values.
L1< Scalar > & weights (Real const &w)
Set weights to a single value.
Real nu () const
Bounds on the squared norm of the operator Ψ
L1< Scalar > & nu (Real const &nu)
Sets the bound on the squared norm of the operator Ψ
const LinearTransform< Vector< Scalar > > & Psi () const
Linear transform applied to input prior to L1 norm.
L1< Scalar > &::type Psi (ARGS &&... args)
Real beta () const
Bounds on the squared norm of the operator Ψ
L1< Scalar > & beta (Real const &beta)
Sets the bound on the squared norm of the operator Ψ
const LinearTransform< Vector< Scalar > > & Phi () const
Linear transform applied to input prior to L1 norm.
L1< Scalar > &::type Phi (ARGS &&... args)
template<class... T>
auto tight_frame (T &&... args) const -> decltype(this->L1TightFrame< Scalar >::operator()(std::forward< T >(args)...))
Special case if Ψ ia a tight frame.
Detailed Description
template<class SCALAR>
class sopt::proximal::L1< SCALAR >
L1 proximal, including linear transform.
This function computes the prox operator of the l1 norm for the input vector \(x\). It solves the problem:
\[ min_{z} 0.5||x - z||_2^2 + γ ||Ψ^† z||_w1 \]
where \(Ψ \in C^{N_x \times N_r} \) is the sparsifying operator, and
\[|| ||_w1\]
is the weighted L1 norm.
Definition at line 177 of file l1_proximal.h.
Member Typedef Documentation
Real
template<class SCALAR > typedef L1TightFrame<SCALAR>::Real sopt::proximal::L1< SCALAR >::Real
Underlying real scalar type.
Definition at line 195 of file l1_proximal.h.
Scalar
template<class SCALAR > typedef L1TightFrame<SCALAR>::Scalar sopt::proximal::L1< SCALAR >::Scalar
Underlying scalar type.
Definition at line 193 of file l1_proximal.h.
Constructor & Destructor Documentation
L1()
template<class SCALAR > sopt::proximal::L1< SCALAR >::L1 () inline
Definition at line 254 of file l1_proximal.h.
       : L1TightFrame<SCALAR>(),
         itermax_(0),
         tolerance_(1e-8),
         positivity_constraint_(false),
         real_constraint_(false),
         fista_mixing_(true) {}
Member Function Documentation
beta() [1/2]
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::beta () const inline
Bounds on the squared norm of the operator Ψ
Definition at line 319 of file l1_proximal.h.
 { return L1TightFrame<Scalar>::beta(); }
Referenced by sopt::proximal::L1< Scalar >::beta(), and sopt::algorithm::L1GProximal< SCALAR >::proximal_function().
beta() [2/2]
template<class SCALAR > L1<Scalar>& sopt::proximal::L1< SCALAR >::beta (Real const & beta) inline
Sets the bound on the squared norm of the operator Ψ
Definition at line 321 of file l1_proximal.h.
{
     L1TightFrame<SCALAR>::beta(beta);
     return *this;
   }
nu() [1/2]
template<class SCALAR > Real sopt::proximal::L1< SCALAR >::nu () const inline
Bounds on the squared norm of the operator Ψ
Definition at line 302 of file l1_proximal.h.
 { return L1TightFrame<Scalar>::nu(); }
Referenced by function_l1p(), main(), sopt::proximal::L1< Scalar >::nu(), and sopt::algorithm::L1GProximal< SCALAR >::proximal_function().
nu() [2/2]
template<class SCALAR > L1<Scalar>& sopt::proximal::L1< SCALAR >::nu (Real const & nu) inline
Sets the bound on the squared norm of the operator Ψ
Definition at line 304 of file l1_proximal.h.
{
     L1TightFrame<SCALAR>::nu(nu);
     return *this;
   }
operator()() [1/2]
template<class SCALAR > template<class T0 > Diagnostic sopt::proximal::L1< SCALAR >::operator() (Eigen::MatrixBase< T0 > & out, Real gamma, Vector< Scalar > const & x) const inline
Computes proximal for given γ
Definition at line 223 of file l1_proximal.h.
{
     // Note that we *must* call eval on x, in case it is an expression involving out
     if (gamma <= 0) {
       apply_constraints(out, x);
       return Diagnostic(0, 0, 0.5 * (out - x).squaredNorm(), true);
     }
     if (fista_mixing())
       return operator()(out, gamma, x, FistaMixing());
     else
       return operator()(out, gamma, x, NoMixing());
   }
Referenced by sopt::proximal::L1< Scalar >::operator()().
operator()() [2/2]
template<class SCALAR > template<class T0 > DiagnosticAndResult sopt::proximal::L1< SCALAR >::operator() (Real const & gamma, Eigen::MatrixBase< T0 > const & x) const inline
Lazy version.
Definition at line 238 of file l1_proximal.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.proximal, gamma, x);
     return result;
   }
Phi() [1/2]
template<class SCALAR > const LinearTransform<Vector<Scalar> >& sopt::proximal::L1< SCALAR >::Phi () const inline
Linear transform applied to input prior to L1 norm.
Definition at line 327 of file l1_proximal.h.
 { return L1TightFrame<Scalar>::Phi(); }
Referenced by sopt::algorithm::L1GProximal< SCALAR >::proximal_function().
Phi() [2/2]
template<class SCALAR > L1<Scalar>& ::type sopt::proximal::L1< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 330 of file l1_proximal.h.
{
     L1TightFrame<Scalar>::Phi(std::forward<ARGS>(args)...);
     return *this;
   }
Psi() [1/2]
template<class SCALAR > const LinearTransform<Vector<Scalar> >& sopt::proximal::L1< SCALAR >::Psi () const inline
Linear transform applied to input prior to L1 norm.
Definition at line 310 of file l1_proximal.h.
 { return L1TightFrame<Scalar>::Psi(); }
Referenced by sopt::algorithm::L1GProximal< SCALAR >::Psi(), and sopt::algorithm::ImagingProximalADMM< SCALAR >::Psi().
Psi() [2/2]
template<class SCALAR > L1<Scalar>& ::type sopt::proximal::L1< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 313 of file l1_proximal.h.
{
     L1TightFrame<Scalar>::Psi(std::forward<ARGS>(args)...);
     return *this;
   }
SOPT_MACRO() [1/5]
template<class SCALAR > sopt::proximal::L1< SCALAR >::SOPT_MACRO (fista_mixing , bool)
Whether to do fista mixing or not.
SOPT_MACRO() [2/5]
template<class SCALAR > sopt::proximal::L1< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations before bailing out.
0 means algorithm breaks only if convergence is reached.
SOPT_MACRO() [3/5]
template<class SCALAR > sopt::proximal::L1< SCALAR >::SOPT_MACRO (positivity_constraint , bool)
Whether to apply positivity constraints.
SOPT_MACRO() [4/5]
template<class SCALAR > sopt::proximal::L1< SCALAR >::SOPT_MACRO (real_constraint , bool)
Whether the output should be constrained to be real.
SOPT_MACRO() [5/5]
template<class SCALAR > sopt::proximal::L1< SCALAR >::SOPT_MACRO (tolerance , Real)
Tolerance criteria.
tight_frame()
template<class SCALAR > template<class... T> auto sopt::proximal::L1< SCALAR >::tight_frame (T &&... args) const -> decltype(this->L1TightFrame<Scalar>::operator()(std::forward<T>(args)...)) inline
Special case if Ψ ia a tight frame.
See also
L1TightFrame
Definition at line 339 of file l1_proximal.h.
{
     return this->L1TightFrame<Scalar>::operator()(std::forward<T>(args)...);
   }
weights() [1/3]
template<class SCALAR > const Vector<Real>& sopt::proximal::L1< SCALAR >::weights () const inline
Weights of the l1 norm.
Definition at line 288 of file l1_proximal.h.
 { return L1TightFrame<Scalar>::weights(); }
weights() [2/3]
template<class SCALAR > template<class T > L1<Scalar>& sopt::proximal::L1< SCALAR >::weights (Eigen::MatrixBase< T > const & w) inline
Set weights to an array of values.
Definition at line 291 of file l1_proximal.h.
{
     L1TightFrame<Scalar>::weights(w);
     return *this;
   }
weights() [3/3]
template<class SCALAR > L1<Scalar>& sopt::proximal::L1< SCALAR >::weights (Real const & w) inline
Set weights to a single value.
Definition at line 296 of file l1_proximal.h.
{
     L1TightFrame<Scalar>::weights(w);
     return this;
   }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/l1_proximal.h