SOPT: sopt::algorithm::ForwardBackward< SCALAR > Class Template Reference
sopt::algorithm::ForwardBackward< SCALAR > Class Template Reference
Forward Backward Splitting.
#include <forward_backward.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef SCALAR value_type
Scalar type.
typedef value_type Scalar
Scalar type.
typedef real_type< Scalar >::type Real
Real type.
typedef Vector< Scalar > t_Vector
Type of then underlying vectors.
typedef LinearTransform< t_Vector > t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
typedef std::function< bool(t_Vector const &, t_Vector const &)> t_IsConverged
Type of the convergence function.
typedef ProximalFunction< Scalar > t_Proximal
Type of the proximal operator.
typedef std::function< void(t_Vector &, const t_Vector &)> t_Gradient
Type of the gradient.
Public Member Functions
template<class DERIVED >
ForwardBackward (t_Gradient const &f_gradient, t_Proximal const &g_proximal, Eigen::MatrixBase< DERIVED > const &target)
virtual ~ForwardBackward ()
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (beta, Real)
β parameter.
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (f_gradient, t_Gradient)
First proximal.
SOPT_MACRO (g_proximal, t_Proximal)
Second proximal.
void f_gradient (t_Vector &out, t_Vector const &x) const
Simplifies calling the proximal of f.
void g_proximal (t_Vector &out, Real gamma, t_Vector const &x) const
Simplifies calling the proximal of f.
ForwardBackward< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
const t_Vector & target () const
Vector of target measurements.
template<class DERIVED >
ForwardBackward< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
bool is_converged (t_Vector const &x, t_Vector const &residual) const
Facilitates call to user-provided convergence function.
Diagnostic operator() (t_Vector &out) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const & > const &guess) const
Calls Forward Backward.
DiagnosticAndResult operator() () const
Calls Forward Backward.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to FB.
ForwardBackward &::type Phi (ARGS &&... args)
std::tuple< t_Vector, t_Vector > initial_guess () const
Computes initial guess for x and the residual using the targets.
Static Public Member Functions
static std::tuple< t_Vector, t_Vector > initial_guess (t_Vector const &target, t_LinearTransform const &phi, Real nu)
Computes initial guess for x and the residual using the targets.
Detailed Description
template<class SCALAR>
class sopt::algorithm::ForwardBackward< SCALAR >
Forward Backward Splitting.
\(\min_{x} f(\Phi x - y) + g(z)\). \(y\) is a target vector.
Definition at line 18 of file forward_backward.h.
Member Typedef Documentation
Real
template<class SCALAR > typedef real_type<Scalar>::type sopt::algorithm::ForwardBackward< SCALAR >::Real
Real type.
Definition at line 25 of file forward_backward.h.
Scalar
template<class SCALAR > typedef value_type sopt::algorithm::ForwardBackward< SCALAR >::Scalar
Scalar type.
Definition at line 23 of file forward_backward.h.
t_Gradient
template<class SCALAR > typedef std::function<void(t_Vector &, const t_Vector &)> sopt::algorithm::ForwardBackward< SCALAR >::t_Gradient
Type of the gradient.
Definition at line 35 of file forward_backward.h.
t_IsConverged
template<class SCALAR > typedef std::function<bool(t_Vector const &, t_Vector const &)> sopt::algorithm::ForwardBackward< SCALAR >::t_IsConverged
Type of the convergence function.
Definition at line 31 of file forward_backward.h.
t_LinearTransform
template<class SCALAR > typedef LinearTransform<t_Vector> sopt::algorithm::ForwardBackward< SCALAR >::t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
Definition at line 29 of file forward_backward.h.
t_Proximal
template<class SCALAR > typedef ProximalFunction<Scalar> sopt::algorithm::ForwardBackward< SCALAR >::t_Proximal
Type of the proximal operator.
Definition at line 33 of file forward_backward.h.
t_Vector
template<class SCALAR > typedef Vector<Scalar> sopt::algorithm::ForwardBackward< SCALAR >::t_Vector
Type of then underlying vectors.
Definition at line 27 of file forward_backward.h.
value_type
template<class SCALAR > typedef SCALAR sopt::algorithm::ForwardBackward< SCALAR >::value_type
Scalar type.
Definition at line 21 of file forward_backward.h.
Constructor & Destructor Documentation
ForwardBackward()
template<class SCALAR > template<class DERIVED > sopt::algorithm::ForwardBackward< SCALAR >::ForwardBackward (t_Gradient const & f_gradient, t_Proximal const & g_proximal, Eigen::MatrixBase< DERIVED > const & target) inline
Setups ForwardBackward
Parameters
[in] f_gradient gradient of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 61 of file forward_backward.h.
       : itermax_(std::numeric_limits<t_uint>::max()),
         gamma_(1e-8),
         beta_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         f_gradient_(f_gradient),
         g_proximal_(g_proximal),
         target_(target) {}
~ForwardBackward()
template<class SCALAR > virtual sopt::algorithm::ForwardBackward< SCALAR >::~ForwardBackward () inline virtual
Definition at line 72 of file forward_backward.h.
 {}
Member Function Documentation
f_gradient()
template<class SCALAR > void sopt::algorithm::ForwardBackward< SCALAR >::f_gradient (t_Vector & out, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 107 of file forward_backward.h.
 { f_gradient()(out, x); }
g_proximal()
template<class SCALAR > void sopt::algorithm::ForwardBackward< SCALAR >::g_proximal (t_Vector & out, Real gamma, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 109 of file forward_backward.h.
{
     g_proximal()(out, gamma, x);
   }
initial_guess() [1/2]
template<class SCALAR > std::tuple<t_Vector, t_Vector> sopt::algorithm::ForwardBackward< SCALAR >::initial_guess () const inline
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
Definition at line 185 of file forward_backward.h.
{
     return ForwardBackward<SCALAR>::initial_guess(target(), Phi(), nu());
   }
References sopt::algorithm::ForwardBackward< SCALAR >::Phi(), and sopt::algorithm::ForwardBackward< SCALAR >::target().
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::operator()(), and sopt::algorithm::ImagingForwardBackward< SCALAR >::operator()().
initial_guess() [2/2]
template<class SCALAR > static std::tuple<t_Vector, t_Vector> sopt::algorithm::ForwardBackward< SCALAR >::initial_guess (t_Vector const & target, t_LinearTransform const & phi, Real nu) inline static
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
This function simplifies creating overloads for operator() in FB wrappers.
Definition at line 195 of file forward_backward.h.
{
     std::tuple<t_Vector, t_Vector> guess;
     std::get<0>(guess) = phi.adjoint() * target / nu;
     std::get<1>(guess) = phi * std::get<0>(guess) - target;
     return guess;
   }
References sopt::LinearTransform< VECTOR >::adjoint(), and sopt::algorithm::ForwardBackward< SCALAR >::target().
is_converged() [1/2]
template<class SCALAR > ForwardBackward<Scalar>& sopt::algorithm::ForwardBackward< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 114 of file forward_backward.h.
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::is_converged(), and TEST_CASE().
is_converged() [2/2]
template<class SCALAR > bool sopt::algorithm::ForwardBackward< SCALAR >::is_converged (t_Vector const & x, t_Vector const & residual) const inline
Facilitates call to user-provided convergence function.
Definition at line 128 of file forward_backward.h.
{
     return static_cast<bool>(is_converged()) and is_converged()(x, residual);
   }
References sopt::algorithm::ForwardBackward< SCALAR >::is_converged().
operator()() [1/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ForwardBackward< SCALAR >::operator() () const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 163 of file forward_backward.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, initial_guess());
     return result;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), and sopt::algorithm::ForwardBackward< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::operator()().
operator()() [2/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ForwardBackward< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to FB.
Definition at line 169 of file forward_backward.h.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::Diagnostic::residual, and sopt::algorithm::ForwardBackward< SCALAR >::DiagnosticAndResult::x.
operator()() [3/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ForwardBackward< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 155 of file forward_backward.h.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::DiagnosticAndResult::x.
operator()() [4/7]
template<class SCALAR > DiagnosticAndResult sopt::algorithm::ForwardBackward< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[in] guess initial guess
Definition at line 150 of file forward_backward.h.
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
References sopt::algorithm::ForwardBackward< SCALAR >::operator()().
operator()() [5/7]
template<class SCALAR > Diagnostic sopt::algorithm::ForwardBackward< SCALAR >::operator() (t_Vector & out) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
Definition at line 134 of file forward_backward.h.
 { return operator()(out, initial_guess()); }
References sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), and sopt::algorithm::ForwardBackward< SCALAR >::operator()().
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::operator()().
operator()() [6/7]
template<class SCALAR > Diagnostic sopt::algorithm::ForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const & > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 144 of file forward_backward.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ForwardBackward< SCALAR >::operator()().
operator()() [7/7]
template<class SCALAR > Diagnostic sopt::algorithm::ForwardBackward< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Forward Backward.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 138 of file forward_backward.h.
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
References sopt::algorithm::ForwardBackward< SCALAR >::operator()().
Phi()
template<class SCALAR > ForwardBackward& ::type sopt::algorithm::ForwardBackward< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 176 of file forward_backward.h.
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
References sopt::linear_transform().
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::initial_guess().
SOPT_MACRO() [1/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (beta , Real)
β parameter.
SOPT_MACRO() [2/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (f_gradient , t_Gradient)
First proximal.
SOPT_MACRO() [3/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (g_proximal , t_Proximal)
Second proximal.
SOPT_MACRO() [4/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [5/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
It takes as input two arguments: the current solution x and the current residual.
SOPT_MACRO() [6/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [7/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [8/8]
template<class SCALAR > sopt::algorithm::ForwardBackward< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
target() [1/2]
template<class SCALAR > const t_Vector& sopt::algorithm::ForwardBackward< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 119 of file forward_backward.h.
 { return target_; }
Referenced by sopt::algorithm::ForwardBackward< SCALAR >::initial_guess(), and sopt::algorithm::ForwardBackward< SCALAR >::target().
target() [2/2]
template<class SCALAR > template<class DERIVED > ForwardBackward<Scalar>& sopt::algorithm::ForwardBackward< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 122 of file forward_backward.h.
{
     target_ = target;
     return *this;
   }
References sopt::algorithm::ForwardBackward< SCALAR >::target().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/forward_backward.h