SOPT: sopt::ORTsession Class Reference
sopt::ORTsession Class Reference
Sopt interface class to hold a ONNXrt session.
#include <ort_session.h>
Public Member Functions
ORTsession ()=delete
ORTsession (const std::string &filename, const std::string &runname="soptONNXrt")
Constructor.
std::vector< float > compute (std::vector< float > &inputs) const
template<typename T = t_real>
Vector< T > compute (const Vector< T > &input) const
Variant of compute() using input/output Eigen arrays.
template<typename T = t_real>
Image< T > compute (const Image< T > &input) const
Variant of compute() using input/output Image.
const bool hasKey (const std::string &key) const
Method to check if key exists in network metadata.
template<typename T >
const T retrieve (const std::string &key) const
template<typename T >
const T retrieve (const std::string &key, const T &defaultreturn) const
Detailed Description
Sopt interface class to hold a ONNXrt session.
Definition at line 18 of file ort_session.h.
Constructor & Destructor Documentation
ORTsession() [1/2]
sopt::ORTsession::ORTsession () delete
ORTsession() [2/2]
sopt::ORTsession::ORTsession (const std::string & filename, const std::string & runname = "soptONNXrt") inline
Constructor.
Definition at line 25 of file ort_session.h.
{
     // Set-up ONNXrt session
     _env = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_WARNING, runname.c_str());
     // Load the model
     Ort::SessionOptions sessionopts;
     _session = std::make_unique<Ort::Session>(*_env, filename.c_str(), sessionopts);
     // Store model hyperparameters (input/output shape etc.)
     _retrieveNetworkInfo();
   }
Member Function Documentation
compute() [1/3]
template<typename T = t_real> Image<T> sopt::ORTsession::compute (const Image< T > & input) const inline
Variant of compute() using input/output Image.
Definition at line 85 of file ort_session.h.
{
     // ONNXrt requires floats as input
     const int nrows = input.rows();
     const int ncols = input.cols();
     std::vector<float> flat_input(nrows*ncols);
     for (int i = 0; i < nrows; ++i) {
       for (int j = 0; j < ncols; ++j) {
         flat_input[j*ncols+i] = input(i,j);
       }
     }
     std::vector<float> flat_output = compute(flat_input);
     std::vector<T> tResults(flat_output.begin(), flat_output.end());
     Eigen::Map<Eigen::Array<T, Eigen::Dynamic, Eigen::Dynamic>> rtn(tResults.data(), nrows, ncols);
     return rtn;
   }
References compute().
compute() [2/3]
template<typename T = t_real> Vector<T> sopt::ORTsession::compute (const Vector< T > & input) const inline
Variant of compute() using input/output Eigen arrays.
Definition at line 63 of file ort_session.h.
{
     // require an output node of the form {1, nRows, nCols}
     // in order to be able to map this onto a 2D tensor
     if (_outDims[0].size() < 3) {
       throw std::length_error("Incorrect size for output tensor!");
     }
     // ONNXrt requires floats as input
     std::vector<float> flat_input(input.size());
     for (size_t i=0; i < input.size(); ++i) {
       flat_input[i] = input[i];
     }
     std::vector<float> flat_output = compute(flat_input);
     Vector<T> rtn(flat_output.size());
     for (size_t i = 0; i < flat_output.size(); ++i) {
       rtn[i] = flat_output[i];
     }
     return rtn;
   }
References compute().
compute() [3/3]
std::vector<float> sopt::ORTsession::compute (std::vector< float > & inputs) const inline
Evaluates the network in the forward direction using a flattened tensor as input
Definition at line 40 of file ort_session.h.
{
     if (inputs.size() != _inDimsFlat[0]) {
       throw std::length_error("Incorrect size for input tensor! Expected length: " + std::to_string(_inDimsFlat[0]));
     }
     // reshape flat input vector as tensor and run the model
     auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
     auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, inputs.data(), inputs.size(),
                                                         _inDims[0].data(), _inDims[0].size());
     auto output_tensors = _session->Run(Ort::RunOptions{nullptr}, _inNames.data(),
                                         &input_tensor, _inNames.size(),
                                         _outNames.data(), _outNames.size());
     // retrieve the ouput tensor and return flattened version
     float* floatarr = output_tensors.front().GetTensorMutableData<float>();
     std::vector<float> outputs;
     outputs.assign(floatarr, floatarr + _outDimsFlat[0]);
     return outputs;
   }
Referenced by compute(), and TEST_CASE().
hasKey()
const bool sopt::ORTsession::hasKey (const std::string & key) const inline
Method to check if key exists in network metadata.
Definition at line 104 of file ort_session.h.
{
     Ort::AllocatorWithDefaultOptions allocator;
     return  (bool)_metadata->LookupCustomMetadataMapAllocated(key.c_str(), allocator);
   }
retrieve() [1/2]
template<typename T > const T sopt::ORTsession::retrieve (const std::string & key) const inline
Method to retrieve value associated with key from network metadata and return value as type T
Definition at line 112 of file ort_session.h.
{
     Ort::AllocatorWithDefaultOptions allocator;
     Ort::AllocatedStringPtr res = _metadata->LookupCustomMetadataMapAllocated(key.c_str(), allocator);
     if (!res) {
       throw std::runtime_error("Key '"+key+"' not found in network metadata!");
     }
     if constexpr (std::is_same<T, std::string>::value) {
       return res.get();
     }
     else {
       return utilities::lexical_cast<T>(res.get());
     }
   }
Referenced by TEST_CASE().
retrieve() [2/2]
template<typename T > const T sopt::ORTsession::retrieve (const std::string & key, const T & defaultreturn) const inline
Variation of retrieve method that falls back to defaultreturn if key cannot be found
Definition at line 130 of file ort_session.h.
{
     try {
       return retrieve<T>(key);
     } catch (std::exception& e) {
       return defaultreturn;
     }
   }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/ort_session.h