SOPT: sopt::algorithm::PrimalDual< SCALAR > Class Template Reference
sopt::algorithm::PrimalDual< SCALAR > Class Template Reference
Primal Dual Algorithm.
#include <primal_dual.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef SCALAR value_type
Scalar type.
typedef value_type Scalar
Scalar type.
typedef real_type< Scalar >::type Real
Real type.
typedef Vector< Scalar > t_Vector
Type of then underlying vectors.
typedef LinearTransform< t_Vector > t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
typedef std::function< bool(t_Vector const &, t_Vector const &)> t_IsConverged
Type of the convergence function.
typedef std::function< void(t_Vector &, const t_Vector &)> t_Constraint
Type of the constraint function.
typedef ProximalFunction< Scalar > t_Proximal
Type of the convergence function.
Public Member Functions
template<class DERIVED >
PrimalDual (t_Proximal const &f_proximal, t_Proximal const &g_proximal, Eigen::MatrixBase< DERIVED > const &target)
virtual ~PrimalDual ()
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (update_scale, Real)
Update parameter.
SOPT_MACRO (gamma, Real)
γ parameter.
SOPT_MACRO (sigma, Real)
sigma parameter
SOPT_MACRO (xi, Real)
xi parameter
SOPT_MACRO (rho, Real)
rho parameter
SOPT_MACRO (tau, Real)
tau parameter
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (constraint, t_Constraint)
A function applying a simple constraint.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (Psi, t_LinearTransform)
Wavelet operator.
SOPT_MACRO (f_proximal, t_Proximal)
First proximal.
SOPT_MACRO (g_proximal, t_Proximal)
Second proximal.
void f_proximal (t_Vector &out, Real gamma, t_Vector const &x) const
Simplifies calling the proximal of f.
void g_proximal (t_Vector &out, Real gamma, t_Vector const &x) const
Simplifies calling the proximal of f.
PrimalDual< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
t_Vector const & target () const
Vector of target measurements.
template<class DERIVED >
PrimalDual< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
bool is_converged (t_Vector const &x, t_Vector const &residual) const
Facilitates call to user-provided convergence function.
Diagnostic operator() (t_Vector &out) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() () const
Calls Primal Dual.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PD.
template<class... ARGS>
PrimalDual &::type Phi (ARGS &&... args)
template<class... ARGS>
PrimalDual &::type Psi (ARGS &&... args)
std::tuple< t_Vector, t_Vector > initial_guess () const
Computes initial guess for x and the residual using the targets.
Static Public Member Functions
static std::tuple< t_Vector, t_Vector > initial_guess (t_Vector const &target, t_LinearTransform const &phi, Real nu)
Computes initial guess for x and the residual using the targets.
Detailed Description
template<class SCALAR>
class sopt::algorithm::PrimalDual< SCALAR >
Primal Dual Algorithm.
\(\min_{x, z} f(x) + h(z)\) subject to \(Φx + z = y\). \(y\) is a target vector.
Definition at line 18 of file primal_dual.h.
Member Typedef Documentation
Real
template<class SCALAR> typedef real_type<Scalar>::type sopt::algorithm::PrimalDual< SCALAR >::Real
Real type.
Definition at line 25 of file primal_dual.h.
Scalar
template<class SCALAR> typedef value_type sopt::algorithm::PrimalDual< SCALAR >::Scalar
Scalar type.
Definition at line 23 of file primal_dual.h.
t_Constraint
template<class SCALAR> typedef std::function<void(t_Vector &, const t_Vector &)> sopt::algorithm::PrimalDual< SCALAR >::t_Constraint
Type of the constraint function.
Definition at line 33 of file primal_dual.h.
t_IsConverged
template<class SCALAR> typedef std::function<bool(t_Vector const &, t_Vector const &)> sopt::algorithm::PrimalDual< SCALAR >::t_IsConverged
Type of the convergence function.
Definition at line 31 of file primal_dual.h.
t_LinearTransform
template<class SCALAR> typedef LinearTransform<t_Vector> sopt::algorithm::PrimalDual< SCALAR >::t_LinearTransform
Type of the Ψ and Ψ^H operations, as well as Φ and Φ^H.
Definition at line 29 of file primal_dual.h.
t_Proximal
template<class SCALAR> typedef ProximalFunction<Scalar> sopt::algorithm::PrimalDual< SCALAR >::t_Proximal
Type of the convergence function.
Definition at line 35 of file primal_dual.h.
t_Vector
template<class SCALAR> typedef Vector<Scalar> sopt::algorithm::PrimalDual< SCALAR >::t_Vector
Type of then underlying vectors.
Definition at line 27 of file primal_dual.h.
value_type
template<class SCALAR> typedef SCALAR sopt::algorithm::PrimalDual< SCALAR >::value_type
Scalar type.
Definition at line 21 of file primal_dual.h.
Constructor & Destructor Documentation
PrimalDual()
template<class SCALAR> template<class DERIVED > sopt::algorithm::PrimalDual< SCALAR >::PrimalDual (t_Proximal const & f_proximal, t_Proximal const & g_proximal, Eigen::MatrixBase< DERIVED > const & target) inline
Setups PrimalDual
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 61 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::f_proximal(), sopt::algorithm::PrimalDual< SCALAR >::g_proximal(), and sopt::algorithm::PrimalDual< SCALAR >::target().
       : itermax_(std::numeric_limits<t_uint>::max()),
         sigma_(1),
         tau_(0.5),
         gamma_(0.5),
         update_scale_(1),
         xi_(1),
         rho_(1),
         nu_(1),
         is_converged_(),
         constraint_([](t_Vector &out, t_Vector const &x) { out = x; }),
         Phi_(linear_transform_identity<Scalar>()),
         Psi_(linear_transform_identity<Scalar>()),
         f_proximal_(f_proximal),
         g_proximal_(g_proximal),
         target_(target) {}
~PrimalDual()
template<class SCALAR> virtual sopt::algorithm::PrimalDual< SCALAR >::~PrimalDual () inline virtual
Definition at line 78 of file primal_dual.h.
 {}
Member Function Documentation
f_proximal()
template<class SCALAR> void sopt::algorithm::PrimalDual< SCALAR >::f_proximal (t_Vector & out, Real gamma, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 125 of file primal_dual.h.
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), and sopt::algorithm::PrimalDual< SCALAR >::PrimalDual().
{
     f_proximal()(out, gamma, x);
   }
g_proximal()
template<class SCALAR> void sopt::algorithm::PrimalDual< SCALAR >::g_proximal (t_Vector & out, Real gamma, t_Vector const & x) const inline
Simplifies calling the proximal of f.
Definition at line 129 of file primal_dual.h.
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), and sopt::algorithm::PrimalDual< SCALAR >::PrimalDual().
{
     g_proximal()(out, gamma, x);
   }
initial_guess() [1/2]
template<class SCALAR> std::tuple<t_Vector, t_Vector> sopt::algorithm::PrimalDual< SCALAR >::initial_guess () const inline
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
Definition at line 211 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::Phi(), and sopt::algorithm::PrimalDual< SCALAR >::target().
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), and sopt::algorithm::PrimalDual< SCALAR >::operator()().
{
     return PrimalDual<SCALAR>::initial_guess(target(), Phi(), nu());
   }
initial_guess() [2/2]
template<class SCALAR> static std::tuple<t_Vector, t_Vector> sopt::algorithm::PrimalDual< SCALAR >::initial_guess (t_Vector const & target, t_LinearTransform const & phi, Real nu) inline static
Computes initial guess for x and the residual using the targets.
with y the vector of measurements
x = Φ^T y / ν
residuals = Φ x - y
This function simplifies creating overloads for operator() in PD wrappers.
Definition at line 221 of file primal_dual.h.
References sopt::LinearTransform< VECTOR >::adjoint(), sopt::algorithm::PrimalDual< SCALAR >::f_proximal(), sopt::algorithm::PrimalDual< SCALAR >::g_proximal(), sopt::algorithm::PrimalDual< SCALAR >::is_converged(), sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::niters, sopt::algorithm::PrimalDual< SCALAR >::operator()(), sopt::algorithm::PrimalDual< SCALAR >::Phi(), sopt::algorithm::PrimalDual< SCALAR >::Psi(), sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, sopt::sigma(), SOPT_ERROR, SOPT_HIGH_LOG, SOPT_LOW_LOG, SOPT_MEDIUM_LOG, SOPT_THROW, SOPT_WARN, and sopt::algorithm::PrimalDual< SCALAR >::target().
{
     std::tuple<t_Vector, t_Vector> guess;
     std::get<0>(guess) = phi.adjoint() * target / nu;
     std::get<1>(guess) = phi * std::get<0>(guess) - target;
     return guess;
   }
is_converged() [1/2]
template<class SCALAR> PrimalDual<Scalar>& sopt::algorithm::PrimalDual< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 134 of file primal_dual.h.
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::PrimalDual< SCALAR >::is_converged(), and TEST_CASE().
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
is_converged() [2/2]
template<class SCALAR> bool sopt::algorithm::PrimalDual< SCALAR >::is_converged (t_Vector const & x, t_Vector const & residual) const inline
Facilitates call to user-provided convergence function.
Definition at line 148 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::is_converged(), and sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual.
{
     return static_cast<bool>(is_converged()) and is_converged()(x, residual);
   }
operator()() [1/7]
template<class SCALAR> Diagnostic sopt::algorithm::PrimalDual< SCALAR >::operator() (t_Vector & out) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
Definition at line 154 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), and sopt::algorithm::PrimalDual< SCALAR >::operator()().
Referenced by sopt::algorithm::PrimalDual< SCALAR >::operator()().
 { return operator()(out, initial_guess()); }
operator()() [2/7]
template<class SCALAR> Diagnostic sopt::algorithm::PrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 158 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [3/7]
template<class SCALAR> Diagnostic sopt::algorithm::PrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 164 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [4/7]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::PrimalDual< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 170 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::operator()().
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [5/7]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::PrimalDual< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 175 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
operator()() [6/7]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::PrimalDual< SCALAR >::operator() () const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 183 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), and sopt::algorithm::PrimalDual< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), and sopt::algorithm::PrimalDual< SCALAR >::operator()().
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, initial_guess());
     return result;
   }
operator()() [7/7]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::PrimalDual< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PD.
Definition at line 189 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, and sopt::algorithm::PrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
Phi()
template<class SCALAR> template<class... ARGS> PrimalDual& ::type sopt::algorithm::PrimalDual< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 196 of file primal_dual.h.
References sopt::linear_transform().
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess().
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Psi()
template<class SCALAR> template<class... ARGS> PrimalDual& ::type sopt::algorithm::PrimalDual< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 202 of file primal_dual.h.
References sopt::linear_transform().
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess().
{
     Psi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
SOPT_MACRO() [1/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [2/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (update_scale , Real)
Update parameter.
SOPT_MACRO() [3/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (gamma , Real)
γ parameter.
SOPT_MACRO() [4/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (sigma , Real)
sigma parameter
SOPT_MACRO() [5/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (xi , Real)
xi parameter
SOPT_MACRO() [6/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (rho , Real)
rho parameter
SOPT_MACRO() [7/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (tau , Real)
tau parameter
SOPT_MACRO() [8/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [9/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
It takes as input two arguments: the current solution x and the current residual.
SOPT_MACRO() [10/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (constraint , t_Constraint)
A function applying a simple constraint.
SOPT_MACRO() [11/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [12/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (Psi , t_LinearTransform)
Wavelet operator.
SOPT_MACRO() [13/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (f_proximal , t_Proximal)
First proximal.
SOPT_MACRO() [14/14]
template<class SCALAR> sopt::algorithm::PrimalDual< SCALAR >::SOPT_MACRO (g_proximal , t_Proximal)
Second proximal.
target() [1/2]
template<class SCALAR> t_Vector const& sopt::algorithm::PrimalDual< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 139 of file primal_dual.h.
Referenced by sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::PrimalDual< SCALAR >::PrimalDual(), and sopt::algorithm::PrimalDual< SCALAR >::target().
 { return target_; }
target() [2/2]
template<class SCALAR> template<class DERIVED > PrimalDual<Scalar>& sopt::algorithm::PrimalDual< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 142 of file primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::target().
{
     target_ = target;
     return *this;
   }
The documentation for this class was generated from the following file:
/mydata/cpp/sopt/primal_dual.h