SOPT: sopt::algorithm::ImagingPrimalDual< SCALAR > Class Template Reference
sopt::algorithm::ImagingPrimalDual< SCALAR > Class Template Reference
#include <imaging_primal_dual.h>
Classes
struct Diagnostic
Values indicating how the algorithm ran.
struct DiagnosticAndResult
Holds result vector as well.
Public Types
typedef PD::value_type value_type
typedef PD::Scalar Scalar
typedef PD::Real Real
typedef PD::t_Vector t_Vector
typedef PD::t_LinearTransform t_LinearTransform
template<class T >
using t_Proximal = std::function< void(t_Vector &, const T &, const t_Vector &)>
typedef PD::t_IsConverged t_IsConverged
typedef PD::t_Constraint t_Constraint
typedef PD::t_Random_Updater t_Random_Updater
typedef PD::value_type value_type
typedef PD::Scalar Scalar
typedef PD::Real Real
typedef PD::t_Vector t_Vector
typedef PD::t_LinearTransform t_LinearTransform
template<class T >
using t_Proximal = std::function< void(t_Vector &, const T &, const t_Vector &)>
typedef PD::t_IsConverged t_IsConverged
typedef PD::t_Constraint t_Constraint
typedef PD::t_Random_Updater t_Random_Updater
Public Member Functions
template<class DERIVED >
ImagingPrimalDual (Eigen::MatrixBase< DERIVED > const &target)
virtual ~ImagingPrimalDual ()
SOPT_MACRO (l1_proximal, t_Proximal< Real >)
The l1 prox functioning as f.
SOPT_MACRO (l1_proximal_weighted, t_Proximal< Vector< Real >>)
The l1 prox with weights functioning as f.
SOPT_MACRO (l1_proximal_weights, Vector< Real >)
The l1 prox weights functioning.
SOPT_MACRO (l2ball_proximal, proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
gamma parameter
SOPT_MACRO (update_scale, Real)
update parameter
SOPT_MACRO (positivity_constraint, bool)
Apply positivity constraint.
SOPT_MACRO (real_constraint, bool)
Apply real constraint.
SOPT_MACRO (sigma, Real)
sigma parameter
SOPT_MACRO (tau, Real)
tau parameter
SOPT_MACRO (xi, Real)
xi parameter
SOPT_MACRO (rho, Real)
rho parameter
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (precondition_stepsize, Real)
precondtion step size parameter
SOPT_MACRO (precondition_weights, t_Vector)
precondition weights parameter
SOPT_MACRO (precondition_iters, t_uint)
precondition iterations parameter
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (Psi, t_LinearTransform)
Wavelet operator.
SOPT_MACRO (random_measurement_updater, t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO (random_wavelet_updater, t_Random_Updater)
lambda that determines if to update wavelets
t_Vector const & target () const
Vector of target measurements.
template<class DERIVED >
ImagingPrimalDual< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() () const
Calls Primal Dual.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PD.
template<class... ARGS>
ImagingPrimalDual &::type Phi (ARGS &&... args)
proximal::WeightedL2Ball< Scalar > & l2ball_proximal ()
Proximal of the L2 ball.
template<class... ARGS>
ImagingPrimalDual &::type Psi (ARGS &&... args)
SOPT_MACRO (epsilon, l2ball, WeightedL2Ball)
SOPT_MACRO (weights, l2ball, WeightedL2Ball)
ImagingPrimalDual< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingPrimalDual< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingPrimalDual< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
template<class DERIVED >
ImagingPrimalDual (Eigen::MatrixBase< DERIVED > const &target)
virtual ~ImagingPrimalDual ()
SOPT_MACRO (l2_proximal, t_Proximal< Real >)
The l2 prox functioning as f.
SOPT_MACRO (l2_proximal_weighted, t_Proximal< Vector< Real >>)
The l2 prox with weights functioning as f.
SOPT_MACRO (l2_proximal_weights, Vector< Real >)
The l2 prox weights functioning.
SOPT_MACRO (l2ball_proximal, proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO (residual_tolerance, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (relative_variation, Real)
Convergence of the relative variation of the objective functions.
SOPT_MACRO (residual_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (objective_convergence, t_IsConverged)
Convergence of the residuals.
SOPT_MACRO (itermax, t_uint)
Maximum number of iterations.
SOPT_MACRO (gamma, Real)
gamma parameter
SOPT_MACRO (update_scale, Real)
update parameter
SOPT_MACRO (positivity_constraint, bool)
Apply positivity constraint.
SOPT_MACRO (real_constraint, bool)
Apply real constraint.
SOPT_MACRO (sigma, Real)
sigma parameter
SOPT_MACRO (tau, Real)
tau parameter
SOPT_MACRO (xi, Real)
xi parameter
SOPT_MACRO (rho, Real)
rho parameter
SOPT_MACRO (nu, Real)
ν parameter.
SOPT_MACRO (precondition_stepsize, Real)
precondtion step size parameter
SOPT_MACRO (precondition_weights, t_Vector)
precondition weights parameter
SOPT_MACRO (precondition_iters, t_uint)
precondition iterations parameter
SOPT_MACRO (is_converged, t_IsConverged)
A function verifying convergence.
SOPT_MACRO (Phi, t_LinearTransform)
Measurement operator.
SOPT_MACRO (Psi, t_LinearTransform)
Wavelet operator.
SOPT_MACRO (random_measurement_updater, t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO (random_wavelet_updater, t_Random_Updater)
lambda that determines if to update wavelets
t_Vector const & target () const
Vector of target measurements.
template<class DERIVED >
ImagingPrimalDual< Scalar > & target (Eigen::MatrixBase< DERIVED > const &target)
Sets the vector of target measurements.
Diagnostic operator() (t_Vector &out) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
Diagnostic operator() (t_Vector &out, std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector, t_Vector > const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() (std::tuple< t_Vector const &, t_Vector const &> const &guess) const
Calls Primal Dual.
DiagnosticAndResult operator() () const
Calls Primal Dual.
DiagnosticAndResult operator() (DiagnosticAndResult const &warmstart) const
Makes it simple to chain different calls to PD.
template<class... ARGS>
ImagingPrimalDual &::type Phi (ARGS &&... args)
proximal::WeightedL2Ball< Scalar > & l2ball_proximal ()
Proximal of the L2 ball.
template<class... ARGS>
ImagingPrimalDual &::type Psi (ARGS &&... args)
SOPT_MACRO (epsilon, l2ball, WeightedL2Ball)
SOPT_MACRO (weights, l2ball, WeightedL2Ball)
ImagingPrimalDual< Scalar > & residual_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingPrimalDual< Scalar > & objective_convergence (Real const &tolerance)
Helper function to set-up default residual convergence function.
ImagingPrimalDual< Scalar > & is_converged (std::function< bool(t_Vector const &x)> const &func)
Convergence function that takes only the output as argument.
Detailed Description
template<class SCALAR>
class sopt::algorithm::ImagingPrimalDual< SCALAR >
Definition at line 20 of file imaging_primal_dual.h.
Member Typedef Documentation
Real [1/2]
template<class SCALAR> typedef PD::Real sopt::algorithm::ImagingPrimalDual< SCALAR >::Real
Definition at line 26 of file l2_primal_dual.h.
Real [2/2]
template<class SCALAR> typedef PD::Real sopt::algorithm::ImagingPrimalDual< SCALAR >::Real
Definition at line 27 of file imaging_primal_dual.h.
Scalar [1/2]
template<class SCALAR> typedef PD::Scalar sopt::algorithm::ImagingPrimalDual< SCALAR >::Scalar
Definition at line 25 of file l2_primal_dual.h.
Scalar [2/2]
template<class SCALAR> typedef PD::Scalar sopt::algorithm::ImagingPrimalDual< SCALAR >::Scalar
Definition at line 26 of file imaging_primal_dual.h.
t_Constraint [1/2]
template<class SCALAR> typedef PD::t_Constraint sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Constraint
Definition at line 32 of file l2_primal_dual.h.
t_Constraint [2/2]
template<class SCALAR> typedef PD::t_Constraint sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Constraint
Definition at line 33 of file imaging_primal_dual.h.
t_IsConverged [1/2]
template<class SCALAR> typedef PD::t_IsConverged sopt::algorithm::ImagingPrimalDual< SCALAR >::t_IsConverged
Definition at line 31 of file l2_primal_dual.h.
t_IsConverged [2/2]
template<class SCALAR> typedef PD::t_IsConverged sopt::algorithm::ImagingPrimalDual< SCALAR >::t_IsConverged
Definition at line 32 of file imaging_primal_dual.h.
t_LinearTransform [1/2]
template<class SCALAR> typedef PD::t_LinearTransform sopt::algorithm::ImagingPrimalDual< SCALAR >::t_LinearTransform
Definition at line 28 of file l2_primal_dual.h.
t_LinearTransform [2/2]
template<class SCALAR> typedef PD::t_LinearTransform sopt::algorithm::ImagingPrimalDual< SCALAR >::t_LinearTransform
Definition at line 29 of file imaging_primal_dual.h.
t_Proximal [1/2]
template<class SCALAR> template<class T > using sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Proximal = std::function<void(t_Vector &, const T &, const t_Vector &)>
Definition at line 30 of file l2_primal_dual.h.
t_Proximal [2/2]
template<class SCALAR> template<class T > using sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Proximal = std::function<void(t_Vector &, const T &, const t_Vector &)>
Definition at line 31 of file imaging_primal_dual.h.
t_Random_Updater [1/2]
template<class SCALAR> typedef PD::t_Random_Updater sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Random_Updater
Definition at line 33 of file l2_primal_dual.h.
t_Random_Updater [2/2]
template<class SCALAR> typedef PD::t_Random_Updater sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Random_Updater
Definition at line 34 of file imaging_primal_dual.h.
t_Vector [1/2]
template<class SCALAR> typedef PD::t_Vector sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Vector
Definition at line 27 of file l2_primal_dual.h.
t_Vector [2/2]
template<class SCALAR> typedef PD::t_Vector sopt::algorithm::ImagingPrimalDual< SCALAR >::t_Vector
Definition at line 28 of file imaging_primal_dual.h.
value_type [1/2]
template<class SCALAR> typedef PD::value_type sopt::algorithm::ImagingPrimalDual< SCALAR >::value_type
Definition at line 24 of file l2_primal_dual.h.
value_type [2/2]
template<class SCALAR> typedef PD::value_type sopt::algorithm::ImagingPrimalDual< SCALAR >::value_type
Definition at line 25 of file imaging_primal_dual.h.
Constructor & Destructor Documentation
ImagingPrimalDual() [1/2]
template<class SCALAR> template<class DERIVED > sopt::algorithm::ImagingPrimalDual< SCALAR >::ImagingPrimalDual (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for PD
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 52 of file imaging_primal_dual.h.
References sopt::proximal::l1_norm(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
       : l1_proximal_([](t_Vector &out, const Real &gamma, const t_Vector &x) {
           proximal::l1_norm(out, gamma, x);
         }),
         l1_proximal_weighted_([](t_Vector &out, const Vector<Real> &gamma, const t_Vector &x) {
           proximal::l1_norm(out, gamma, x);
         }),
         l1_proximal_weights_(Vector<Real>::Ones(1)),
         l2ball_proximal_(1e0),
         residual_tolerance_(1e-4),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         sigma_(1),
         tau_(0.5),
         gamma_(0.5),
         update_scale_(1),
         precondition_stepsize_(0.5),
         precondition_weights_(t_Vector::Ones(target.size())),
         precondition_iters_(0),
         xi_(1),
         rho_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         Psi_(linear_transform_identity<Scalar>()),
         random_measurement_updater_([]() { return true; }),
         random_wavelet_updater_([]() { return true; }),
         target_(target) {}
~ImagingPrimalDual() [1/2]
template<class SCALAR> virtual sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual () inline virtual
Definition at line 82 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal(), sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence(), sopt::sigma(), sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
 {}
ImagingPrimalDual() [2/2]
template<class SCALAR> template<class DERIVED > sopt::algorithm::ImagingPrimalDual< SCALAR >::ImagingPrimalDual (Eigen::MatrixBase< DERIVED > const & target) inline
Setups imaging wrapper for PD
Parameters
[in] f_proximal proximal operator of the \(f\) function.
[in] g_proximal proximal operator of the \(g\) function
Definition at line 51 of file l2_primal_dual.h.
References sopt::proximal::l2_norm(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
       : l2_proximal_([](t_Vector &out, const Real &gamma, const t_Vector &x) {
           proximal::l2_norm(out, gamma, x);
         }),
         l2_proximal_weighted_([](t_Vector &out, const Vector<Real> &gamma, const t_Vector &x) {
           proximal::l2_norm(out, gamma, x);
         }),
         l2_proximal_weights_(Vector<Real>::Ones(1)),
         l2ball_proximal_(1e0),
         residual_tolerance_(1e-4),
         relative_variation_(1e-4),
         residual_convergence_(nullptr),
         objective_convergence_(nullptr),
         itermax_(std::numeric_limits<t_uint>::max()),
         sigma_(1),
         tau_(0.5),
         gamma_(0.5),
         update_scale_(1),
         precondition_stepsize_(0.5),
         precondition_weights_(t_Vector::Ones(target.size())),
         precondition_iters_(0),
         xi_(1),
         rho_(1),
         nu_(1),
         is_converged_(),
         Phi_(linear_transform_identity<Scalar>()),
         Psi_(linear_transform_identity<Scalar>()),
         random_measurement_updater_([]() { return true; }),
         random_wavelet_updater_([]() { return true; }),
         target_(target) {}
~ImagingPrimalDual() [2/2]
template<class SCALAR> virtual sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual () inline virtual
Definition at line 81 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal(), sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence(), sopt::sigma(), sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
 {}
Member Function Documentation
is_converged() [1/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 265 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), sopt::l2_norm(), sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal(), sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::positive_quadrant(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi(), sopt::ScalarRelativeVariation< TYPE >::relative_tolerance(), sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence(), sopt::sigma(), SOPT_HIGH_LOG, SOPT_LOW_LOG, SOPT_THROW, and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
is_converged() [2/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged (std::function< bool(t_Vector const &x)> const & func) inline
Convergence function that takes only the output as argument.
Definition at line 266 of file imaging_primal_dual.h.
References sopt::l1_norm(), sopt::l2_norm(), sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal(), sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::positive_quadrant(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi(), sopt::ScalarRelativeVariation< TYPE >::relative_tolerance(), sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence(), sopt::sigma(), SOPT_HIGH_LOG, SOPT_LOW_LOG, SOPT_THROW, and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
{
     return is_converged([func](t_Vector const &x, t_Vector const &) { return func(x); });
   }
l2ball_proximal() [1/2]
template<class SCALAR> proximal::WeightedL2Ball<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 224 of file l2_primal_dual.h.
 { return l2ball_proximal_; }
l2ball_proximal() [2/2]
template<class SCALAR> proximal::WeightedL2Ball<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::l2ball_proximal () inline
Proximal of the L2 ball.
Non-const version to setup the object.
Definition at line 225 of file imaging_primal_dual.h.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
 { return l2ball_proximal_; }
objective_convergence() [1/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 261 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence().
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
objective_convergence() [2/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 262 of file imaging_primal_dual.h.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), sopt::algorithm::ImagingPrimalDual< SCALAR >::objective_convergence(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
{
     return objective_convergence(nullptr).relative_variation(tolerance);
   }
operator()() [1/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
Definition at line 171 of file l2_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
{
     return operator()(out, PD::initial_guess(target(), Phi(), nu()));
   }
operator()() [2/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
Definition at line 172 of file imaging_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
{
     return operator()(out, PD::initial_guess(target(), Phi(), nu()));
   }
operator()() [3/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 177 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [4/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 178 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [5/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 183 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [6/14]
template<class SCALAR> Diagnostic sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (t_Vector & out, std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[out] out Output vector x
[in] guess initial guess
Definition at line 184 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(out, std::get<0>(guess), std::get<1>(guess));
   }
operator()() [7/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 189 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [8/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (std::tuple< t_Vector, t_Vector > const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 190 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     return operator()(std::tie(std::get<0>(guess), std::get<1>(guess)));
   }
operator()() [9/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 194 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
operator()() [10/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (std::tuple< t_Vector const &, t_Vector const &> const & guess) const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 195 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x, guess);
     return result;
   }
operator()() [11/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() () const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 202 of file l2_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::target(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x,
                                                    PD::initial_guess(target(), Phi(), nu()));
     return result;
   }
operator()() [12/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() () const inline
Calls Primal Dual.
Parameters
[in] guess initial guess
Definition at line 203 of file imaging_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::initial_guess(), sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi(), sopt::algorithm::ImagingPrimalDual< SCALAR >::target(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()().
{
     DiagnosticAndResult result;
     static_cast<Diagnostic &>(result) = operator()(result.x,
                                                    PD::initial_guess(target(), Phi(), nu()));
     return result;
   }
operator()() [13/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PD.
Definition at line 209 of file l2_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, and sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
operator()() [14/14]
template<class SCALAR> DiagnosticAndResult sopt::algorithm::ImagingPrimalDual< SCALAR >::operator() (DiagnosticAndResult const & warmstart) const inline
Makes it simple to chain different calls to PD.
Definition at line 210 of file imaging_primal_dual.h.
References sopt::algorithm::PrimalDual< SCALAR >::Diagnostic::residual, and sopt::algorithm::ImagingPrimalDual< SCALAR >::DiagnosticAndResult::x.
{
     DiagnosticAndResult result = warmstart;
     static_cast<Diagnostic &>(result) = operator()(result.x, warmstart.x, warmstart.residual);
     return result;
   }
Phi() [1/2]
template<class SCALAR> template<class... ARGS> ImagingPrimalDual& ::type sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 217 of file l2_primal_dual.h.
References sopt::linear_transform().
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Phi() [2/2]
template<class SCALAR> template<class... ARGS> ImagingPrimalDual& ::type sopt::algorithm::ImagingPrimalDual< SCALAR >::Phi (ARGS &&... args) inline
Definition at line 218 of file imaging_primal_dual.h.
References sopt::linear_transform().
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), main(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
{
     Phi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Psi() [1/2]
template<class SCALAR> template<class... ARGS> ImagingPrimalDual& ::type sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 228 of file l2_primal_dual.h.
References sopt::linear_transform().
{
     Psi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
Psi() [2/2]
template<class SCALAR> template<class... ARGS> ImagingPrimalDual& ::type sopt::algorithm::ImagingPrimalDual< SCALAR >::Psi (ARGS &&... args) inline
Definition at line 229 of file imaging_primal_dual.h.
References sopt::linear_transform().
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), main(), TEST_CASE(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
{
     Psi_ = linear_transform(std::forward<ARGS>(args)...);
     return *this;
   }
residual_convergence() [1/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 257 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence().
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
residual_convergence() [2/2]
template<class SCALAR> ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence (Real const & tolerance) inline
Helper function to set-up default residual convergence function.
Definition at line 258 of file imaging_primal_dual.h.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), main(), sopt::algorithm::ImagingPrimalDual< SCALAR >::residual_convergence(), TEST_CASE(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
{
     return residual_convergence(nullptr).residual_tolerance(tolerance);
   }
SOPT_MACRO() [1/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l2_proximal , t_Proximal< Real >)
The l2 prox functioning as f.
SOPT_MACRO() [2/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l1_proximal , t_Proximal< Real >)
The l1 prox functioning as f.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
SOPT_MACRO() [3/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l2_proximal_weighted , t_Proximal< Vector< Real >>)
The l2 prox with weights functioning as f.
SOPT_MACRO() [4/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l1_proximal_weighted , t_Proximal< Vector< Real >>)
The l1 prox with weights functioning as f.
SOPT_MACRO() [5/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l2_proximal_weights , Vector< Real >)
The l2 prox weights functioning.
SOPT_MACRO() [6/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l1_proximal_weights , Vector< Real >)
The l1 prox weights functioning.
SOPT_MACRO() [7/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l2ball_proximal , proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO() [8/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (l2ball_proximal , proximal::WeightedL2Ball< Scalar >)
The weighted L2 proximal functioning as g.
SOPT_MACRO() [9/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [10/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (residual_tolerance , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [11/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [12/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (relative_variation , Real)
Convergence of the relative variation of the objective functions.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [13/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [14/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (residual_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [15/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [16/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (objective_convergence , t_IsConverged)
Convergence of the residuals.
If negative, this convergence criteria is disabled.
SOPT_MACRO() [17/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [18/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (itermax , t_uint)
Maximum number of iterations.
SOPT_MACRO() [19/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (gamma , Real)
gamma parameter
SOPT_MACRO() [20/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (gamma , Real)
gamma parameter
SOPT_MACRO() [21/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (update_scale , Real)
update parameter
SOPT_MACRO() [22/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (update_scale , Real)
update parameter
SOPT_MACRO() [23/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (positivity_constraint , bool)
Apply positivity constraint.
SOPT_MACRO() [24/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (positivity_constraint , bool)
Apply positivity constraint.
SOPT_MACRO() [25/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (real_constraint , bool)
Apply real constraint.
SOPT_MACRO() [26/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (real_constraint , bool)
Apply real constraint.
SOPT_MACRO() [27/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (sigma , Real)
sigma parameter
SOPT_MACRO() [28/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (sigma , Real)
sigma parameter
SOPT_MACRO() [29/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (tau , Real)
tau parameter
SOPT_MACRO() [30/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (tau , Real)
tau parameter
SOPT_MACRO() [31/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (xi , Real)
xi parameter
SOPT_MACRO() [32/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (xi , Real)
xi parameter
SOPT_MACRO() [33/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (rho , Real)
rho parameter
SOPT_MACRO() [34/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (rho , Real)
rho parameter
SOPT_MACRO() [35/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [36/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (nu , Real)
ν parameter.
SOPT_MACRO() [37/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_stepsize , Real)
precondtion step size parameter
SOPT_MACRO() [38/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_stepsize , Real)
precondtion step size parameter
SOPT_MACRO() [39/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_weights , t_Vector)
precondition weights parameter
SOPT_MACRO() [40/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_weights , t_Vector)
precondition weights parameter
SOPT_MACRO() [41/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_iters , t_uint)
precondition iterations parameter
SOPT_MACRO() [42/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (precondition_iters , t_uint)
precondition iterations parameter
SOPT_MACRO() [43/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [44/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (is_converged , t_IsConverged)
A function verifying convergence.
SOPT_MACRO() [45/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [46/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (Phi , t_LinearTransform)
Measurement operator.
SOPT_MACRO() [47/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (Psi , t_LinearTransform)
Wavelet operator.
SOPT_MACRO() [48/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (Psi , t_LinearTransform)
Wavelet operator.
SOPT_MACRO() [49/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (random_measurement_updater , t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO() [50/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (random_measurement_updater , t_Random_Updater)
lambda that determines if to update measurements
SOPT_MACRO() [51/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (random_wavelet_updater , t_Random_Updater)
lambda that determines if to update wavelets
SOPT_MACRO() [52/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (random_wavelet_updater , t_Random_Updater)
lambda that determines if to update wavelets
SOPT_MACRO() [53/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (epsilon , l2ball , WeightedL2Ball)
SOPT_MACRO() [54/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (epsilon , l2ball , WeightedL2Ball)
SOPT_MACRO() [55/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (weights , l2ball , WeightedL2Ball)
SOPT_MACRO() [56/56]
template<class SCALAR> sopt::algorithm::ImagingPrimalDual< SCALAR >::SOPT_MACRO (weights , l2ball , WeightedL2Ball)
target() [1/4]
template<class SCALAR> t_Vector const& sopt::algorithm::ImagingPrimalDual< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 161 of file l2_primal_dual.h.
 { return target_; }
target() [2/4]
template<class SCALAR> t_Vector const& sopt::algorithm::ImagingPrimalDual< SCALAR >::target () const inline
Vector of target measurements.
Definition at line 162 of file imaging_primal_dual.h.
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::ImagingPrimalDual(), sopt::algorithm::ImagingPrimalDual< SCALAR >::is_converged(), sopt::algorithm::ImagingPrimalDual< SCALAR >::operator()(), sopt::algorithm::ImagingPrimalDual< SCALAR >::target(), and sopt::algorithm::ImagingPrimalDual< SCALAR >::~ImagingPrimalDual().
 { return target_; }
target() [3/4]
template<class SCALAR> template<class DERIVED > ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 164 of file l2_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
{
     target_ = target;
     return *this;
   }
target() [4/4]
template<class SCALAR> template<class DERIVED > ImagingPrimalDual<Scalar>& sopt::algorithm::ImagingPrimalDual< SCALAR >::target (Eigen::MatrixBase< DERIVED > const & target) inline
Sets the vector of target measurements.
Definition at line 165 of file imaging_primal_dual.h.
References sopt::algorithm::ImagingPrimalDual< SCALAR >::target().
{
     target_ = target;
     return *this;
   }
The documentation for this class was generated from the following files:
/mydata/cpp/sopt/imaging_primal_dual.h
/mydata/cpp/sopt/l2_primal_dual.h