SOPT: sopt::wavelets::SARA Class Reference
sopt::wavelets::SARA Class Reference
Sparsity Averaging Reweighted Analysis.
#include <sara.h>
Public Member Functions
SARA (std::initializer_list< std::tuple< std::string, t_uint >> const &init)
Easy constructor.
template<class ITERATOR , class T = typename std::enable_if< std::is_convertible<decltype(std::get<0>(*std::declval<ITERATOR>())), std::string>::value and std::is_convertible<decltype(std::get<1>(*std::declval<ITERATOR>())), t_uint>::value, ::type >
SARA (ITERATOR first, ITERATOR last)
Construct from any iterator over a (std:string, t_uint) tuple.
SARA (const_iterator first, const_iterator last)
virtual ~SARA ()
Destructor.
template<class T0 >
T0::PlainObject direct (Eigen::ArrayBase< T0 > const &signal) const
Direct transform.
template<class T0 , class T1 >
void direct (Eigen::ArrayBase< T1 > &coefficients, Eigen::ArrayBase< T0 > const &signal) const
Direct transform.
template<class T0 , class T1 >
void direct (Eigen::ArrayBase< T1 > &&coefficients, Eigen::ArrayBase< T0 > const &signal) const
Direct transform.
template<class T0 >
T0::PlainObject indirect (Eigen::ArrayBase< T0 > const &coeffs) const
Indirect transform.
template<class T0 , class T1 >
void indirect (Eigen::ArrayBase< T1 > const &coefficients, Eigen::ArrayBase< T0 > &signal) const
Indirect transform.
template<class T0 , class T1 >
void indirect (Eigen::ArrayBase< T1 > const &coeffs, Eigen::ArrayBase< T0 > &&signal) const
Indirect transform.
t_uint max_levels () const
Number of levels over which to do transform.
void emplace_back (std::string const &name, t_uint nlevels)
Adds a wavelet of specific type.
Detailed Description
Sparsity Averaging Reweighted Analysis.
Definition at line 19 of file sara.h.
Constructor & Destructor Documentation
SARA() [1/3]
sopt::wavelets::SARA::SARA (std::initializer_list< std::tuple< std::string, t_uint >> const & init) inline
Easy constructor.
Definition at line 29 of file sara.h.
       : SARA(init.begin(), init.end()) {}
SARA() [2/3]
template<class ITERATOR , class T = typename std::enable_if< std::is_convertible<decltype(std::get<0>(*std::declval<ITERATOR>())), std::string>::value and std::is_convertible<decltype(std::get<1>(*std::declval<ITERATOR>())), t_uint>::value, ::type > sopt::wavelets::SARA::SARA (ITERATOR first, ITERATOR last) inline
Construct from any iterator over a (std:string, t_uint) tuple.
Definition at line 38 of file sara.h.
{
     for (; first != last; ++first) emplace_back(std::get<0>(*first), std::get<1>(*first));
   }
References emplace_back().
SARA() [3/3]
sopt::wavelets::SARA::SARA (const_iterator first, const_iterator last) inline
Definition at line 42 of file sara.h.
 : std::vector<Wavelet>(first, last) {}
~SARA()
virtual sopt::wavelets::SARA::~SARA () inline virtual
Destructor.
Definition at line 44 of file sara.h.
 {}
Member Function Documentation
direct() [1/3]
template<class T0 > T0::PlainObject sopt::wavelets::SARA::direct (Eigen::ArrayBase< T0 > const & signal) const
Direct transform.
Parameters
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the maximum number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Returns
wavelets coefficients arranged by columns: if the input is n by m, then the output is n by m * d, with d the number of wavelets.
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 188 of file sara.h.
{
   typedef decltype(this->front().direct(signal)) t_Output;
   t_Output result = t_Output::Zero(signal.rows(), signal.cols() * size());
   (*this).direct(result, signal);
   return result;
 }
Referenced by direct().
direct() [2/3]
template<class T0 , class T1 > void sopt::wavelets::SARA::direct (Eigen::ArrayBase< T1 > && coefficients, Eigen::ArrayBase< T0 > const & signal) const inline
Direct transform.
Parameters
[in,out] coefficients Output wavelet coefficients. Must be of the type as the input. If the input is n by m, and l is the number of wavelets, then the output should be n by (m * l).
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data. This version allows non-constant Eigen expressions to be passe on without the ugly const_cast of the cannonical approach.
Definition at line 76 of file sara.h.
{
     direct(coefficients, signal);
   }
References direct().
direct() [3/3]
template<class T0 , class T1 > void sopt::wavelets::SARA::direct (Eigen::ArrayBase< T1 > & coefficients, Eigen::ArrayBase< T0 > const & signal) const
Direct transform.
Parameters
[in,out] coefficients Output wavelet coefficients. Must be of the type as the input. If the input is n by m, and d is the number of wavelets, then the output should be n by (m * d).
[in] signal computes wavelet coefficients for this signal. Its size must be a multiple of $2^l$ where $l$ is the maximum number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 125 of file sara.h.
{
   SOPT_WAVELET_ERROR_MACRO(signal);
   if (coeffs.rows() != signal.rows() or coeffs.cols() != signal.cols() * static_cast<t_int>(size()))
     coeffs.derived().resize(signal.rows(), signal.cols() * size());
   if (coeffs.rows() != signal.rows() or coeffs.cols() != signal.cols() * static_cast<t_int>(size()))
     throw std::length_error("Incorrect size for output matrix(or could not resize)");
   if (size() == 0) return;
   auto const Ncols = signal.cols();
   {
 #ifndef SOPT_OPENMP
     SOPT_TRACE("Calling direct sara without threads");
 #endif
     if (Ncols == 1)
       for (size_type i = 0; i < size(); ++i) at(i).direct(coeffs.col(i), signal.col(0));
     else
       for (size_type i = 0; i < size(); ++i)
         at(i).direct(coeffs.leftCols((i + 1) * Ncols).rightCols(Ncols), signal);
   }
   coeffs /= std::sqrt(size());
 }
References SOPT_TRACE, and SOPT_WAVELET_ERROR_MACRO.
emplace_back()
void sopt::wavelets::SARA::emplace_back (std::string const & name, t_uint nlevels) inline
Adds a wavelet of specific type.
Definition at line 113 of file sara.h.
{
     std::vector<Wavelet>::emplace_back(factory(name, nlevels));
   }
References sopt::wavelets::factory().
Referenced by main(), and SARA().
indirect() [1/3]
template<class T0 > T0::PlainObject sopt::wavelets::SARA::indirect (Eigen::ArrayBase< T0 > const & coeffs) const
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d transform).
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 180 of file sara.h.
{
   typedef decltype(this->front().indirect(coeffs)) t_Output;
   t_Output signal = t_Output::Zero(coeffs.rows(), coeffs.cols() / size());
   (*this).indirect(coeffs, signal);
   return signal;
 }
Referenced by indirect().
indirect() [2/3]
template<class T0 , class T1 > void sopt::wavelets::SARA::indirect (Eigen::ArrayBase< T1 > const & coefficients, Eigen::ArrayBase< T0 > & signal) const
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d
[in,out] signal Reconstructed signal. Must be of the same size and type as the input.
Supports 1 and 2 dimensional tranforms for real and complex data.
Definition at line 148 of file sara.h.
{
   if (size() == 0) throw std::runtime_error("Empty wavelets: adjoint operation undefined");
   if (signal.cols() == 1) {
     if (coeffs.rows() % (1u << max_levels()) != 0)
       throw std::length_error("Inconsistent number of columns and wavelet levels");
   } else
     SOPT_WAVELET_ERROR_MACRO(coeffs);
   if (coeffs.cols() % size() != 0)
     throw std::length_error(
         "Columns of coefficient matrix and number of wavelets are inconsistent");
   if (coeffs.rows() != signal.rows() or coeffs.cols() != signal.cols() * static_cast<t_int>(size()))
     signal.derived().resize(coeffs.rows(), coeffs.cols() / size());
   if (coeffs.rows() != signal.rows() or coeffs.cols() != signal.cols() * static_cast<t_int>(size()))
     throw std::length_error("Incorrect size for output matrix(or could not resize)");
   auto const Ncols = signal.cols();
   {
 #ifndef SOPT_OPENMP
     SOPT_TRACE("Calling indirect sara without threads");
 #endif
     signal = T0::Zero(signal.rows(), signal.cols());
     if (Ncols == 1)
       for (size_type i = 0; i < size(); ++i) signal.col(0) += at(i).indirect(coeffs.col(i));
     else
       for (size_type i = 0; i < size(); ++i)
         signal += at(i).indirect(coeffs.leftCols((i + 1) * Ncols).rightCols(Ncols));
   }
   signal /= std::sqrt(size());
 }
References max_levels(), SOPT_TRACE, and SOPT_WAVELET_ERROR_MACRO.
indirect() [3/3]
template<class T0 , class T1 > void sopt::wavelets::SARA::indirect (Eigen::ArrayBase< T1 > const & coeffs, Eigen::ArrayBase< T0 > && signal) const inline
Indirect transform.
Parameters
[in] coefficients Input wavelet coefficients. Its size must be a multiple of $2^l$ where $l$ is the number of levels. Can be a matrix (2d-transform) or a column vector (1-d
[in,out] signal Reconstructed signal. Must be of the same size and type as the input.
Supports 1 and 2 dimensional tranforms for real and complex data. This version allows non-constant Eigen expressions to be passe on without the ugly const_cast of the cannonical approach.
Definition at line 101 of file sara.h.
{
     indirect(coeffs, signal);
   }
References indirect().
max_levels()
t_uint sopt::wavelets::SARA::max_levels () const inline
Number of levels over which to do transform.
Definition at line 106 of file sara.h.
{
     if (size() == 0) return 0;
     auto cmp = [](Wavelet const &a, Wavelet const &b) { return a.levels() < b.levels(); };
     return std::max_element(begin(), end(), cmp)->levels();
   }
References a, and b.
Referenced by indirect().
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/wavelets/sara.h