SOPT: sopt::ScalarRelativeVariation< TYPE > Class Template Reference
sopt::ScalarRelativeVariation< TYPE > Class Template Reference
#include <relative_variation.h>
Public Types
typedef TYPE Scalar
Underlying scalar type.
typedef real_type< Scalar >::type Real
Underlying scalar type.
Public Member Functions
ScalarRelativeVariation (Real relative_tolerance=1e-12, Real absolute_tolerance=1e-12, std::string const &name="")
Maximum variation from one step to the next.
ScalarRelativeVariation (ScalarRelativeVariation const &c)
Copy constructor.
bool operator() (Scalar const &current)
True if object has changed by less than tolerance.
Real relative_tolerance () const
Allowed variation.
RelativeVariation< Scalar > & relative_tolerance (Real &e) const
Allowed variation.
Real absolute_tolerance () const
Allowed variation.
RelativeVariation< Scalar > & absolute_tolerance (Real &e) const
Allowed variation.
const std::string & name () const
Name that gets interpolated into the log's output.
const ScalarRelativeVariation & name (std::string const &name) const
Scalar previous () const
Detailed Description
template<class TYPE>
class sopt::ScalarRelativeVariation< TYPE >
Definition at line 55 of file relative_variation.h.
Member Typedef Documentation
Real
template<class TYPE > typedef real_type<Scalar>::type sopt::ScalarRelativeVariation< TYPE >::Real
Underlying scalar type.
Definition at line 60 of file relative_variation.h.
Scalar
template<class TYPE > typedef TYPE sopt::ScalarRelativeVariation< TYPE >::Scalar
Underlying scalar type.
Definition at line 58 of file relative_variation.h.
Constructor & Destructor Documentation
ScalarRelativeVariation() [1/2]
template<class TYPE > sopt::ScalarRelativeVariation< TYPE >::ScalarRelativeVariation (Real relative_tolerance = 1e-12, Real absolute_tolerance = 1e-12, std::string const & name = "") inline
Maximum variation from one step to the next.
Definition at line 62 of file relative_variation.h.
       : name_(name),
         relative_tolerance_(relative_tolerance),
         absolute_tolerance_(absolute_tolerance),
         previous_(0),
         is_first_(true){};
ScalarRelativeVariation() [2/2]
template<class TYPE > sopt::ScalarRelativeVariation< TYPE >::ScalarRelativeVariation (ScalarRelativeVariation< TYPE > const & c) inline
Copy constructor.
Definition at line 70 of file relative_variation.h.
       : relative_tolerance_(c.relative_tolerance_),
         previous_(c.previous_),
         is_first_(c.is_first_){};
Member Function Documentation
absolute_tolerance() [1/2]
template<class TYPE > Real sopt::ScalarRelativeVariation< TYPE >::absolute_tolerance () const inline
Allowed variation.
Definition at line 86 of file relative_variation.h.
 { return relative_tolerance_; }
absolute_tolerance() [2/2]
template<class TYPE > RelativeVariation<Scalar>& sopt::ScalarRelativeVariation< TYPE >::absolute_tolerance (Real & e) const inline
Allowed variation.
Definition at line 88 of file relative_variation.h.
{
     absolute_tolerance_ = e;
     return *this;
   }
name() [1/2]
template<class TYPE > const std::string& sopt::ScalarRelativeVariation< TYPE >::name () const inline
Name that gets interpolated into the log's output.
Definition at line 94 of file relative_variation.h.
 { return name_; }
Referenced by sopt::ScalarRelativeVariation< TYPE >::name().
name() [2/2]
template<class TYPE > const ScalarRelativeVariation& sopt::ScalarRelativeVariation< TYPE >::name (std::string const & name) const inline
Definition at line 95 of file relative_variation.h.
{
     name_ = name;
     return *this;
   }
References sopt::ScalarRelativeVariation< TYPE >::name().
operator()()
template<class SCALAR > bool sopt::ScalarRelativeVariation< SCALAR >::operator() (Scalar const & current)
True if object has changed by less than tolerance.
Definition at line 124 of file relative_variation.h.
{
   if (is_first_) {
     previous_ = current;
     is_first_ = false;
     return false;
   }
   auto const average = (std::abs(previous_) + std::abs(current)) * 0.5;
   auto const diff = std::abs(previous_ - current);
   auto const result =
       diff <= relative_tolerance() * std::abs(average) or std::abs(diff) < absolute_tolerance();
   SOPT_LOW_LOG("    - {} relative variation: {} < {} * {} or {} < {} is {}", name(), diff,
                relative_tolerance(), average, diff, absolute_tolerance(),
                result ? "true" : "false");
   previous_ = current;
   return result;
 }
References SOPT_LOW_LOG.
previous()
template<class TYPE > Scalar sopt::ScalarRelativeVariation< TYPE >::previous () const inline
Definition at line 100 of file relative_variation.h.
 { return previous_; }
relative_tolerance() [1/2]
template<class TYPE > Real sopt::ScalarRelativeVariation< TYPE >::relative_tolerance () const inline
Allowed variation.
Definition at line 79 of file relative_variation.h.
 { return relative_tolerance_; }
Referenced by TEST_CASE().
relative_tolerance() [2/2]
template<class TYPE > RelativeVariation<Scalar>& sopt::ScalarRelativeVariation< TYPE >::relative_tolerance (Real & e) const inline
Allowed variation.
Definition at line 81 of file relative_variation.h.
{
     relative_tolerance_ = e;
     return *this;
   }
The documentation for this class was generated from the following file:
/home/runner/work/sopt/sopt/cpp/sopt/relative_variation.h