SOPT: /home/runner/work/sopt/sopt/cpp/tests/cppflow_model.cc File Reference
cppflow_model.cc File Reference
#include <iostream>
#include <vector>
#include <catch.hpp>
#include "sopt/logging.h"
#include "sopt/types.h"
#include "sopt/utilities.h"
#include "sopt/cppflow_utils.h"
#include <cppflow/cppflow.h>
#include <cppflow/ops.h>
#include <cppflow/model.h>
#include "tools_for_tests/directories.h"
#include "tools_for_tests/tiffwrappers.h"
Typedefs
using Scalar = double
using Image = sopt::Image< Scalar >
Functions
TEST_CASE ("Cppflow Model")
Typedef Documentation
Image
using Image = sopt::Image<Scalar>
Definition at line 20 of file cppflow_model.cc.
Scalar
using Scalar = double
Definition at line 19 of file cppflow_model.cc.
Function Documentation
TEST_CASE()
TEST_CASE ("Cppflow Model")
Definition at line 23 of file cppflow_model.cc.
{
   // read in image
   std::string const input_image = "cameraman256";
   Image const image = sopt::notinstalled::read_standard_tiff(input_image);
   int const image_rows = image.rows();
   int const image_cols = image.cols();
   cppflow::tensor input_tensor = sopt::cppflowutils::convert_image_to_tensor(image, image_rows, image_cols);
   // Read in model
   cppflow::model model(std::string(sopt::notinstalled::models_directory() + "/DnCNN/snr_15_model.pb/"));
   // Run model on image
   // TODO: Automatically detect the string parameters, see issue #320
   auto output_vector = model({{"serving_default_input0:0", input_tensor}}, {"StatefulPartitionedCall:0"});
   // Get values from output (has to be same type as the input to the model - float)
   auto output_tensor = output_vector[0].get_data<float>();
   auto output_image = sopt::cppflowutils::convert_tensor_to_image(output_tensor, image_rows, image_cols);
   // compare input image to cleaned output image
   // calculate mean squared error sum_i ( ( x_true(i) - x_est(i) ) **2 )
   // check this is less than the number of pixels * 0.01
   auto mse = (image - output_image).square().sum() / image.size();
   CAPTURE(mse);
   CHECK(mse < 0.01);
 }
References sopt::cppflowutils::convert_image_to_tensor(), sopt::cppflowutils::convert_tensor_to_image(), sopt::notinstalled::models_directory(), and sopt::notinstalled::read_standard_tiff().