SOPT: /home/runner/work/sopt/sopt/cpp/tests/mpi_session.cc File Reference
mpi_session.cc File Reference
#include <iterator>
#include <regex>
#include <vector>
#include "catch.hpp"
#include "sopt/logging.h"
#include "sopt/mpi/session.h"
Macros
#define CATCH_CONFIG_RUNNER
Functions
TEST_CASE ("Create/delete session")
int main (int argc, const char **argv)
Variables
std::vector< char const * > cargs
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Definition at line 1 of file mpi_session.cc.
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 22 of file mpi_session.cc.
{
   Catch::Session session;  // There must be exactly once instance
   // Removes output qualifiers from arguments
   auto avoid = false;
   auto const N = std::string("--out=").size();
   std::vector<std::string> const args(argv, argv + argc);
   for (auto const &arg : args)
     if (avoid)
       avoid = false;
     else if (arg == "-o" or arg == "--out")
       avoid = true;
     else if (arg.size() < N or arg.substr(0, N) != "--out=")
       cargs.push_back(arg.c_str());
   auto const returnCode = session.applyCommandLine(cargs.size(), const_cast<char **>(cargs.data()));
   if (returnCode != 0)  // Indicates a command line error
     return returnCode;
   sopt::logging::initialize();
   auto const result = session.run();
   return result;
 }
References cargs, sopt::logging::initialize(), and N.
TEST_CASE()
TEST_CASE ("Create/delete session")
Definition at line 11 of file mpi_session.cc.
{
   CHECK(mpi::initialized() == false);
   CHECK(mpi::finalized() == false);
   auto session = mpi::init(cargs.size(), cargs.data());
   CHECK(mpi::initialized() == true);
   CHECK(mpi::finalized() == false);
   session.reset();
   CHECK(mpi::initialized() == true);
   CHECK(mpi::finalized() == true);
 }
References cargs, sopt::mpi::finalized(), sopt::mpi::init(), and sopt::mpi::initialized().
Variable Documentation
cargs
std::vector<char const *> cargs
Definition at line 10 of file mpi_session.cc.
Referenced by main(), and TEST_CASE().