SOPT: sopt::gradient_operator Namespace Reference
sopt::gradient_operator Namespace Reference
Functions
template<class T >
Vector< T > diff (const Vector< T > &x)
Numerical derivative of 1d vector.
template<class T >
Vector< T > diff_adjoint (const Vector< T > &x)
Numerical derivative adjoint of 1d vector.
template<class T >
Vector< T > diff2d (const Vector< T > &x, const t_int rows, const t_int cols)
Numerical derivative of 2d image.
template<class T >
Vector< T > diff2d_adjoint (const Vector< T > &x, const t_int rows, const t_int cols)
Numerical derivative adjoint of 2d image.
template<class T >
LinearTransform< Vector< T > > gradient_operator (const t_int rows, const t_int cols)
Function Documentation
diff()
template<class T > Vector<T> sopt::gradient_operator::diff (const Vector< T > & x)
Numerical derivative of 1d vector.
Definition at line 11 of file gradient_operator.h.
{
   if (x.size() < 2) return Vector<T>::Zero(x.size());
   Vector<T> output = Vector<T>::Zero(x.size());
   output.segment(0, x.size() - 1) = x.segment(1, x.size() - 1) - x.segment(0, x.size() - 1);
   return output;
 }
Referenced by sopt::ScalarRelativeVariation< TYPE >::operator()().
diff2d()
template<class T > Vector<T> sopt::gradient_operator::diff2d (const Vector< T > & x, const t_int rows, const t_int cols)
Numerical derivative of 2d image.
Definition at line 27 of file gradient_operator.h.
{
   Matrix<T> output = Matrix<T>::Zero(rows, 2 * cols);
   const Matrix<T> &input_image = Matrix<T>::Map(x.data(), rows, cols);
   for (Eigen::Index i(0); i < rows; i++)
     output.block(0, 0, rows, cols).row(i) = diff<T>(input_image.row(i));
   for (Eigen::Index i(0); i < cols; i++)
     output.block(0, cols, rows, cols).col(i) = diff<T>(input_image.col(i));
   return Vector<T>::Map(output.data(), output.size());
 }
References cols, and rows.
Referenced by gradient_operator().
diff2d_adjoint()
template<class T > Vector<T> sopt::gradient_operator::diff2d_adjoint (const Vector< T > & x, const t_int rows, const t_int cols)
Numerical derivative adjoint of 2d image.
Definition at line 38 of file gradient_operator.h.
{
   const Matrix<T> &input_image = Matrix<T>::Map(x.data(), rows, 2 * cols);
   Matrix<T> output = Matrix<T>::Zero(rows, cols);
   for (Eigen::Index i(0); i < rows; i++)
     output.row(i) += diff_adjoint<T>(input_image.block(0, 0, rows, cols).row(i));
   for (Eigen::Index i(0); i < cols; i++)
     output.col(i) += diff_adjoint<T>(input_image.block(0, cols, rows, cols).col(i));
   return Vector<T>::Map(output.data(), output.size());
 }
References cols, and rows.
Referenced by gradient_operator().
diff_adjoint()
template<class T > Vector<T> sopt::gradient_operator::diff_adjoint (const Vector< T > & x)
Numerical derivative adjoint of 1d vector.
Definition at line 19 of file gradient_operator.h.
{
   Vector<T> output = Vector<T>::Zero(x.size());
   output.segment(0, x.size() - 1) -= x.segment(0, x.size() - 1);
   if (output.size() > 2) output.segment(1, x.size() - 1) = x.segment(0, x.size() - 1);
   return output;
 }
gradient_operator()
template<class T > LinearTransform<Vector<T> > sopt::gradient_operator::gradient_operator (const t_int rows, const t_int cols)
Definition at line 48 of file gradient_operator.h.
{
   return LinearTransform<Vector<T>>(
       [rows, cols](Vector<T> &out, Vector<T> const &x) {
         assert(x.size() == rows * cols * 2);
         out = diff2d_adjoint(x, rows, cols) / 2.;
         assert(out.size() == rows * cols);
       },
       {{0, 1, static_cast<t_int>(rows * cols)}},
       [rows, cols](Vector<T> &out, Vector<T> const &x) {
         assert(x.size() == rows * cols);
         out = diff2d(x, rows, cols) / 2.;
         assert(out.size() == 2 * rows * cols);
       },
       {{0, 1, static_cast<t_int>(2 * rows * cols)}});
 }
References cols, diff2d(), diff2d_adjoint(), and rows.