SOPT: sopt::proximal Namespace Reference
sopt::proximal Namespace Reference
Holds some standard proximals.
Namespaces
details
Classes
class EuclidianNorm
Proximal of euclidian norm.
class L1
L1 proximal, including linear transform.
class L1TightFrame
L1 proximal, including linear transform.
class L2Ball
Proximal for indicator function of L2 ball.
class L2Norm
Proximal for the L2 norm.
class Translation
Translation over proximal function.
class WeightedL2Ball
Typedefs
template<typename FUNC , typename T0 >
using ProximalExpression = details::DelayedProximalFunction< FUNC, Eigen::MatrixBase< T0 > >
Eigen expression from proximal functions.
template<typename FUNC , typename T0 >
using EnveloppeExpression = details::DelayedProximalEnveloppeFunction< FUNC, Eigen::MatrixBase< T0 > >
Eigen expression from proximal enveloppe functions.
Functions
template<typename T0 >
auto euclidian_norm (typename real_type< typename T0::Scalar >::type const &t, Eigen::MatrixBase< T0 > const &x) -> decltype(EuclidianNorm(), t, x)
Proximal of the euclidian norm.
template<typename T0 , typename T1 >
void l1_norm (Eigen::DenseBase< T0 > &out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const &x)
Proximal of the l1 norm.
template<typename T0 , typename T1 , typename T2 >
void l1_norm (Eigen::DenseBase< T0 > &out, Eigen::DenseBase< T2 > const &gamma, Eigen::DenseBase< T1 > const &x)
Proxmal of the weighted l1 norm.
template<typename S >
void l1_norm (Vector< S > &out, typename real_type< S >::type gamma, Vector< S > const &x)
Proximal of the l1 norm \detail This specialization makes it easier to use in algorithms, e.g. within SDMM::append.
template<typename T0 , typename T1 >
void l2_norm (Eigen::DenseBase< T0 > &out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const &x)
Proximal of the l2 norm (note this is different from the l2 ball indicator function)
template<typename T0 , typename T1 , typename T2 >
void l2_norm (Eigen::DenseBase< T0 > &out, Eigen::DenseBase< T2 > const &gamma, Eigen::DenseBase< T1 > const &x)
template<typename T0 , typename T1 >
void tv_norm (Eigen::DenseBase< T0 > &out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const &x)
Proximal of the l1,2 norm that is used in the TV norm.
template<typename T0 , typename T1 , typename T2 >
void tv_norm (Eigen::DenseBase< T0 > &out, Eigen::DenseBase< T2 > const &gamma, Eigen::DenseBase< T1 > const &x)
template<typename T0 , typename T1 >
void id (Eigen::DenseBase< T0 > &out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const &x)
Proximal of a function that is always zero, the identity.
template<typename T >
auto l1_norm (typename real_type< typename T::Scalar >::type gamma, Eigen::DenseBase< T > const &x) -> decltype(sopt::soft_threshhold(x, gamma))
Proximal of l1 norm.
template<typename T >
void positive_quadrant (Vector< T > &out, typename real_type< T >::type, Vector< T > const &x)
Proximal for projection on the positive quadrant.
template<typename FUNCTION , typename VECTOR >
Translation< FUNCTION, VECTOR > translate (FUNCTION const &func, VECTOR const &translation)
Translates given proximal by given vector.
Detailed Description
Holds some standard proximals.
Typedef Documentation
EnveloppeExpression
template<typename FUNC , typename T0 > using sopt::proximal::EnveloppeExpression = typedef details::DelayedProximalEnveloppeFunction<FUNC, Eigen::MatrixBase<T0> >
Eigen expression from proximal enveloppe functions.
Definition at line 87 of file proximal_expression.h.
ProximalExpression
template<typename FUNC , typename T0 > using sopt::proximal::ProximalExpression = typedef details::DelayedProximalFunction<FUNC, Eigen::MatrixBase<T0> >
Eigen expression from proximal functions.
Definition at line 84 of file proximal_expression.h.
Function Documentation
euclidian_norm()
template<typename T0 > auto sopt::proximal::euclidian_norm (typename real_type< typename T0::Scalar >::type const & t, Eigen::MatrixBase< T0 > const & x) -> decltype(EuclidianNorm(), t, x)
Proximal of the euclidian norm.
Definition at line 57 of file proximal.h.
{
   return EuclidianNorm()(t, x);
 }
id()
template<typename T0 , typename T1 > void sopt::proximal::id (Eigen::DenseBase< T0 > & out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const & x)
Proximal of a function that is always zero, the identity.
Definition at line 135 of file proximal.h.
{
   out = x;
 }
Referenced by TEST_CASE().
l1_norm() [1/4]
template<typename T0 , typename T1 , typename T2 > void sopt::proximal::l1_norm (Eigen::DenseBase< T0 > & out, Eigen::DenseBase< T2 > const & gamma, Eigen::DenseBase< T1 > const & x)
Proxmal of the weighted l1 norm.
Definition at line 70 of file proximal.h.
{
   out = sopt::soft_threshhold<T0, T2>(x, gamma);
 }
l1_norm() [2/4]
template<typename T0 , typename T1 > void sopt::proximal::l1_norm (Eigen::DenseBase< T0 > & out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const & x)
Proximal of the l1 norm.
Definition at line 64 of file proximal.h.
{
   out = sopt::soft_threshhold<T0>(x, gamma);
 }
Referenced by TEST_CASE().
l1_norm() [3/4]
template<typename T > auto sopt::proximal::l1_norm (typename real_type< typename T::Scalar >::type gamma, Eigen::DenseBase< T > const & x) -> decltype(sopt::soft_threshhold(x, gamma))
Proximal of l1 norm.
For more complex version involving linear transforms and weights, see L1TightFrame and L1 classes. In practice, this is an alias for soft_threshhold.
Definition at line 144 of file proximal.h.
{
   return sopt::soft_threshhold(x, gamma);
 }
References sopt::soft_threshhold().
l1_norm() [4/4]
template<typename S > void sopt::proximal::l1_norm (Vector< S > & out, typename real_type< S >::type gamma, Vector< S > const & x)
Proximal of the l1 norm \detail This specialization makes it easier to use in algorithms, e.g. within SDMM::append.
Definition at line 78 of file proximal.h.
{
   l1_norm<Vector<S>, Vector<S>>(out, gamma, x);
 }
l2_norm() [1/2]
template<typename T0 , typename T1 , typename T2 > void sopt::proximal::l2_norm (Eigen::DenseBase< T0 > & out, Eigen::DenseBase< T2 > const & gamma, Eigen::DenseBase< T1 > const & x)
Definition at line 90 of file proximal.h.
{
   out = x.derived().array() * 1. / (1. + gamma.derived().array()).array();
 }
Referenced by sopt::proximal::EuclidianNorm::operator()(), sopt::proximal::L2Ball< T >::operator()(), and sopt::proximal::WeightedL2Ball< T >::operator()().
l2_norm() [2/2]
template<typename T0 , typename T1 > void sopt::proximal::l2_norm (Eigen::DenseBase< T0 > & out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const & x)
Proximal of the l2 norm (note this is different from the l2 ball indicator function)
Definition at line 84 of file proximal.h.
{
   out = x.derived() * 1. / (1. + gamma);
 }
Referenced by sopt::algorithm::ImagingPrimalDual< SCALAR >::ImagingPrimalDual(), sopt::algorithm::L2ForwardBackward< SCALAR >::L2ForwardBackward(), and sopt::proximal::L2Norm< T >::operator()().
positive_quadrant()
template<typename T > void sopt::proximal::positive_quadrant (Vector< T > & out, typename real_type< T >::type , Vector< T > const & x)
Proximal for projection on the positive quadrant.
Definition at line 151 of file proximal.h.
{
   out = sopt::positive_quadrant(x);
 };
References sopt::positive_quadrant().
translate()
template<typename FUNCTION , typename VECTOR > Translation<FUNCTION, VECTOR> sopt::proximal::translate (FUNCTION const & func, VECTOR const & translation)
Translates given proximal by given vector.
Definition at line 362 of file proximal.h.
{
   return Translation<FUNCTION, VECTOR>(func, translation);
 }
Referenced by main(), SCENARIO(), and TEST_CASE().
tv_norm() [1/2]
template<typename T0 , typename T1 , typename T2 > void sopt::proximal::tv_norm (Eigen::DenseBase< T0 > & out, Eigen::DenseBase< T2 > const & gamma, Eigen::DenseBase< T1 > const & x)
Definition at line 115 of file proximal.h.
{
   typename Eigen::Index const size = x.size() / 2;
   typename T1::PlainObject const &u = x.segment(0, size);
   typename T1::PlainObject const &v = x.segment(size, size);
   out = T0::Zero(size * 2);
   for (typename Eigen::Index i(0); i < size; i++) {
     const t_real norm = std::sqrt(std::abs(u(i) * u(i) + v(i) * v(i)));
     if (norm > gamma(i)) {
       out(i) = (1 - gamma(i) / norm) * u(i);
       out(size + i) = (1 - gamma(i) / norm) * v(i);
     } else {
       out(i) = 0;
       out(size + i) = 0;
     }
   }
 }
tv_norm() [2/2]
template<typename T0 , typename T1 > void sopt::proximal::tv_norm (Eigen::DenseBase< T0 > & out, typename real_type< typename T0::Scalar >::type gamma, Eigen::DenseBase< T1 > const & x)
Proximal of the l1,2 norm that is used in the TV norm.
Definition at line 97 of file proximal.h.
{
   typename Eigen::Index const size = x.size() / 2;
   typename T1::PlainObject const &u = x.segment(0, size);
   typename T1::PlainObject const &v = x.segment(size, size);
   out = T0::Zero(size * 2);
   for (typename Eigen::Index i(0); i < size; i++) {
     const t_real norm = std::sqrt(std::abs(u(i) * u(i) + v(i) * v(i)));
     if (norm > gamma) {
       out(i) = (1 - gamma / norm) * u(i);
       out(size + i) = (1 - gamma / norm) * v(i);
     } else {
       out(i) = 0;
       out(size + i) = 0;
     }
   }
 }