SOPT: sopt::utilities Namespace Reference
sopt::utilities Namespace Reference
Functions
Image read_tiff (std::string const &name)
Reads tiff image.
void write_tiff (Image<> const &image, std::string const &filename)
Writes a tiff greyscale file.
template<typename T >
Vector< T > & get_wavelet_basis_coefficients (Vector< T > &coeffs, const t_uint basis_index, const t_uint size)
return wavelet basis coefficients from a dictionary
template<typename T >
Vector< T > & get_wavelet_levels_1d (Vector< T > &coeffs, const t_uint level, const t_uint size)
return wavelet basis coefficients for a given level and below (1d case)
template<typename T >
Vector< T > & get_wavelet_levels (Vector< T > &coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients for a given level and below (2d case)
template<typename T >
Vector< T > & get_wavelet_low_high_pass (Vector< T > &coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients low pass (rows) and high pass (cols) for a given level
template<typename T >
Vector< T > & get_wavelet_high_high_pass (Vector< T > &coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
template<typename T >
Vector< T > & get_wavelet_high_low_pass (Vector< T > &coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
template<typename T >
Vector< T > & get_wavelet_low_low_pass (Vector< T > &coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
template<typename T >
Vector< T > & get_wavelet_high_pass_1d (Vector< T > &coeffs, const t_uint level, const t_uint size)
return 1d high pass filter for a given level of a wavelet
Function Documentation
get_wavelet_basis_coefficients()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_basis_coefficients (Vector< T > & coeffs, const t_uint basis_index, const t_uint size)
return wavelet basis coefficients from a dictionary
Definition at line 105 of file wavelets.h.
{
   assert(coeffs.size() > basis_index * size);
   return coeffs.segment(basis_index * size, size);
 }
get_wavelet_high_high_pass()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_high_high_pass (Vector< T > & coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
Definition at line 139 of file wavelets.h.
{
   auto const Nx = rows >> level;  // bitshift to divide by 2^level
   auto const Ny = cols >> level;
   const Matrix<T> signal =
       Matrix<T>::Map(get_wavelet_levels(coeffs, level, rows, cols).data(), Nx, Ny);
   return Vector<T>::Map(signal.bottomRightCorner(signal.rows() / 2, signal.cols() / 2).data(),
                         signal.size() / 4);
 }
References cols, get_wavelet_levels(), and rows.
get_wavelet_high_low_pass()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_high_low_pass (Vector< T > & coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
Definition at line 149 of file wavelets.h.
{
   auto const Nx = rows >> level;  // bitshift to divide by 2^level
   auto const Ny = cols >> level;
   const Matrix<T> signal =
       Matrix<T>::Map(get_wavelet_levels(coeffs, level, rows, cols).data(), Nx, Ny);
   return Vector<T>::Map(signal.bottomLeftCorner(signal.rows() / 2, signal.cols() / 2).data(),
                         signal.size() / 4);
 }
References cols, get_wavelet_levels(), and rows.
get_wavelet_high_pass_1d()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_high_pass_1d (Vector< T > & coeffs, const t_uint level, const t_uint size)
return 1d high pass filter for a given level of a wavelet
Definition at line 116 of file wavelets.h.
{
   auto const N = static_cast<t_uint>(coeffs.size()) >> level;  // bitshift to divide by 2^level
   return get_wavelet_levels(coeffs, level, size).tail(N / 2);
 }
References get_wavelet_levels(), and N.
get_wavelet_levels()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_levels (Vector< T > & coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients for a given level and below (2d case)
Definition at line 121 of file wavelets.h.
{
   const Matrix<T> signal = Matrix<T>::Map(coeffs.data(), rows, cols);
   auto const Nx = static_cast<t_uint>(signal.rows()) >> level;  // bitshift to divide by 2^level
   auto const Ny = static_cast<t_uint>(signal.cols()) >> level;
   return Vector<T>::Map(signal.topLeftCorner(Nx, Ny).data(), Nx * Ny);
 }
References cols, and rows.
Referenced by get_wavelet_high_high_pass(), get_wavelet_high_low_pass(), get_wavelet_high_pass_1d(), get_wavelet_low_high_pass(), and get_wavelet_low_low_pass().
get_wavelet_levels_1d()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_levels_1d (Vector< T > & coeffs, const t_uint level, const t_uint size)
return wavelet basis coefficients for a given level and below (1d case)
Definition at line 111 of file wavelets.h.
{
   auto const N = static_cast<t_uint>(coeffs.size()) >> level;  // bitshift to divide by 2^level
   return coeffs.head(N);
 }
References N.
get_wavelet_low_high_pass()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_low_high_pass (Vector< T > & coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients low pass (rows) and high pass (cols) for a given level
Definition at line 129 of file wavelets.h.
{
   auto const Nx = rows >> level;  // bitshift to divide by 2^level
   auto const Ny = cols >> level;
   const Matrix<T> signal =
       Matrix<T>::Map(get_wavelet_levels(coeffs, level, rows, cols).data(), Nx, Ny);
   return Vector<T>::Map(signal.topRightCorner(signal.rows() / 2, signal.cols() / 2).data(),
                         signal.size() / 4);
 }
References cols, get_wavelet_levels(), and rows.
get_wavelet_low_low_pass()
template<typename T > Vector< T > & sopt::utilities::get_wavelet_low_low_pass (Vector< T > & coeffs, const t_uint level, const t_uint rows, const t_uint cols)
return wavelet basis coefficients high pass (rows) and high pass (cols) for a given level
Definition at line 159 of file wavelets.h.
{
   auto const Nx = rows >> level;  // bitshift to divide by 2^level
   auto const Ny = cols >> level;
   const Matrix<T> signal =
       Matrix<T>::Map(get_wavelet_levels(coeffs, level, rows, cols).data(), Nx, Ny);
   return Vector<T>::Map(signal.topLeftCorner(signal.rows() / 2, signal.cols() / 2).data(),
                         signal.size() / 4);
 }
References cols, get_wavelet_levels(), and rows.
read_tiff()
sopt::Image sopt::utilities::read_tiff (std::string const & filename)
Reads tiff image.
Definition at line 38 of file utilities.cc.
{
   SOPT_MEDIUM_LOG("Reading image file {} ", filename);
   TIFF *tif = TIFFOpen(filename.c_str(), "r");
   if (tif == nullptr) SOPT_THROW("Could not open file ") << filename;
   uint32_t width;
   uint32_t height;
   uint32_t t;
   TIFFGetField(tif, TIFFTAG_IMAGEWIDTH, &width);
   TIFFGetField(tif, TIFFTAG_IMAGELENGTH, &height);
   TIFFGetField(tif, TIFFTAG_PHOTOMETRIC, &t);
   SOPT_LOW_LOG("- image size {}, {} ", width, height);
   Image<> result = Image<>::Zero(height, width);
   uint32_t *raster = static_cast<uint32_t *>(_TIFFmalloc(width * height * sizeof(uint32_t)));
   if (raster == nullptr) SOPT_THROW("Could not allocate memory to read file ") << filename;
   if (TIFFReadRGBAImage(tif, width, height, raster, 0) == 0)
     SOPT_THROW("Could not read file ") << filename;
   uint32_t *pixel = raster;
   for (uint32_t i(0); i < height; ++i)
     for (uint32_t j(0); j < width; ++j, ++pixel) result(i, j) = convert_to_greyscale(*pixel);
   _TIFFfree(raster);
   TIFFClose(tif);
   return result;
 }
References SOPT_LOW_LOG, SOPT_MEDIUM_LOG, and SOPT_THROW.
Referenced by main(), and sopt::notinstalled::read_standard_tiff().
write_tiff()
void sopt::utilities::write_tiff (Image<> const & image, std::string const & filename)
Writes a tiff greyscale file.
Definition at line 68 of file utilities.cc.
{
   SOPT_MEDIUM_LOG("Writing image file {} ", filename);
   SOPT_LOW_LOG("- image size {}, {} ", image.rows(), image.cols());
   TIFF *tif = TIFFOpen(filename.c_str(), "w");
   if (tif == nullptr) SOPT_THROW("Could not open file ") << filename;
   uint32_t const width = image.cols();
   uint32_t const height = image.rows();
   SOPT_TRACE("Allocating buffer");
   std::vector<uint32_t> raster(width * height);
   TIFFSetField(tif, TIFFTAG_IMAGEWIDTH, width);
   TIFFSetField(tif, TIFFTAG_IMAGELENGTH, height);
   TIFFSetField(tif, TIFFTAG_SAMPLESPERPIXEL, sizeof(decltype(raster)::value_type));
   TIFFSetField(tif, TIFFTAG_BITSPERSAMPLE, 8);
   TIFFSetField(tif, TIFFTAG_ROWSPERSTRIP, height);
   TIFFSetField(tif, TIFFTAG_PLANARCONFIG, PLANARCONFIG_CONTIG);
   TIFFSetField(tif, TIFFTAG_COMPRESSION, COMPRESSION_LZW);
   TIFFSetField(tif, TIFFTAG_PHOTOMETRIC, PHOTOMETRIC_RGB);
   TIFFSetField(tif, TIFFTAG_ORIENTATION, ORIENTATION_BOTLEFT);
   SOPT_TRACE("Initializing buffer");
   auto pixel = raster.begin();
   for (uint32_t i(0); i < height; ++i)
     for (uint32_t j(0); j < width; ++j, ++pixel) *pixel = convert_from_greyscale(image(i, j));
   SOPT_TRACE("Writing strip");
   TIFFWriteEncodedStrip(tif, 0, raster.data(), width * height * sizeof(decltype(raster)::value_type));
   TIFFWriteDirectory(tif);
   SOPT_TRACE("Closing tif");
   TIFFClose(tif);
   SOPT_TRACE("Freeing raster");
 }
References SOPT_LOW_LOG, SOPT_MEDIUM_LOG, SOPT_THROW, and SOPT_TRACE.
Referenced by main().