SOPT: sopt::objective_functions Namespace Reference
sopt::objective_functions Namespace Reference
Functions
template<typename T >
std::function< t_real(T)> const unconstrained_regularisation (const std::function< t_real(T)> &g, const t_real &sig, const T &y, const sopt::OperatorFunction< T > &measurement_operator)
returns g(x) + ||y - Φ x||_2^2 as a function
template<typename T >
std::function< t_real(T)> const unconstrained_L1_regularisation (const t_real &gamma, const t_real &sig, const T &y, const sopt::OperatorFunction< T > &measurement_operator, const sopt::LinearTransform< T > &wavelet_operator)
returns ||ψ^t x||_1 + ||y - Φ x||_2^2 as a function
template<typename T >
std::function< t_real(T)> const unconstrained_regularisation (const std::function< t_real(T)> &g, const t_real &sig, const T &y, const sopt::LinearTransform< T > &measurement_operator)
template<typename T >
std::function< t_real(T)> const unconstrained_l1_regularisation (const t_real &gamma, const t_real &sig, const T &y, const sopt::LinearTransform< T > &measurement_operator, const sopt::LinearTransform< T > &wavelet_operator)
template<typename T >
std::function< t_real(T)> const unconstrained_l1_regularisation (const t_real &gamma, const t_real &sig, const T &y, const sopt::OperatorFunction< T > &measurement_operator, const sopt::LinearTransform< T > &wavelet_operator)
Function Documentation
unconstrained_l1_regularisation() [1/2]
template<typename T > std::function< t_real(T)> const sopt::objective_functions::unconstrained_l1_regularisation (const t_real & gamma, const t_real & sig, const T & y, const sopt::LinearTransform< T > & measurement_operator, const sopt::LinearTransform< T > & wavelet_operator)
Definition at line 43 of file objective_functions.h.
{
   if (gamma <= 0) SOPT_THROW("regularsiation paramter is not greater than 0.");
   const std::function<t_real(T)> g = [=](const T &x) -> t_real {
     return sopt::l1_norm(wavelet_operator.adjoint() * x) * gamma;
   };
   return unconstrained_regularisation<T>(g, sig, y, measurement_operator);
 }
References sopt::LinearTransform< VECTOR >::adjoint(), sopt::l1_norm(), and SOPT_THROW.
unconstrained_L1_regularisation()
template<typename T > std::function<t_real(T)> const sopt::objective_functions::unconstrained_L1_regularisation (const t_real & gamma, const t_real & sig, const T & y, const sopt::OperatorFunction< T > & measurement_operator, const sopt::LinearTransform< T > & wavelet_operator)
returns ||ψ^t x||_1 + ||y - Φ x||_2^2 as a function
unconstrained_l1_regularisation() [2/2]
template<typename T > std::function<t_real(T)> const sopt::objective_functions::unconstrained_l1_regularisation (const t_real & gamma, const t_real & sig, const T & y, const sopt::OperatorFunction< T > & measurement_operator, const sopt::LinearTransform< T > & wavelet_operator)
Definition at line 61 of file objective_functions.h.
{
   const LinearTransform<T> mop = {measurement_operator, measurement_operator};
   return unconstrained_l1_regularisation<T>(gamma, sig, mop * y, mop, wavelet_operator);
 }
unconstrained_regularisation() [1/2]
template<typename T > std::function< t_real(T)> const sopt::objective_functions::unconstrained_regularisation (const std::function< t_real(T)> & g, const t_real & sig, const T & y, const sopt::LinearTransform< T > & measurement_operator)
Definition at line 35 of file objective_functions.h.
{
   return [=](const T &x) -> t_real {
     return g(x) + 0.5 * std::pow(sopt::l2_norm(y - measurement_operator * x) / sig, 2);
   };
 }
References sopt::l2_norm().
unconstrained_regularisation() [2/2]
template<typename T > std::function< t_real(T)> const sopt::objective_functions::unconstrained_regularisation (const std::function< t_real(T)> & g, const t_real & sig, const T & y, const sopt::OperatorFunction< T > & measurement_operator)
returns g(x) + ||y - Φ x||_2^2 as a function
Definition at line 54 of file objective_functions.h.
{
   const LinearTransform<T> mop = {measurement_operator, measurement_operator};
   return unconstrained_regularisation<T>(g, sig, mop * y, mop);
 }