SOPT: sopt::notinstalled Namespace Reference
sopt::notinstalled Namespace Reference
Functions
std::string data_directory ()
Holds images and such.
std::string output_directory ()
Output artefacts from tests.
Image read_standard_tiff (std::string const &name)
Reads tiff image from sopt data directory if it exists.
Function Documentation
data_directory()
std::string sopt::notinstalled::data_directory () inline
Holds images and such.
Definition at line 10 of file directories.in.h.
Referenced by read_standard_tiff().
 { return "@PROJECT_SOURCE_DIR@/images"; }
output_directory()
std::string sopt::notinstalled::output_directory () inline
Output artefacts from tests.
Definition at line 12 of file directories.in.h.
 { return "@PROJECT_BINARY_DIR@/outputs"; }
read_standard_tiff()
sopt::Image sopt::notinstalled::read_standard_tiff (std::string const & name)
Reads tiff image from sopt data directory if it exists.
Definition at line 10 of file tiffwrappers.cc.
References data_directory(), and sopt::utilities::read_tiff().
Referenced by main(), and TEST_CASE().
{
   std::string const stdname = sopt::notinstalled::data_directory() + "/" + name + ".tiff";
   bool const is_std = std::ifstream(stdname).good();
   return sopt::utilities::read_tiff(is_std ? stdname : name);
 }