SOPT: sopt::mpi Namespace Reference
sopt::mpi Namespace Reference
Namespaces
details
Functions
std::shared_ptr< details::initializer > init (int argc, const char **argv)
std::shared_ptr< details::initializer > session_singleton ()
bool initialized ()
bool finalized ()
void finalize ()
Function Documentation
finalize()
void sopt::mpi::finalize ()
Definition at line 77 of file session.cc.
                 {
   if (finalized() or not initialized()) return;
   MPI_Finalize();
 }
References finalized(), and initialized().
finalized()
bool sopt::mpi::finalized ()
Definition at line 71 of file session.cc.
                  {
   int finalized;
   MPI_Finalized(&finalized);
   return finalized != 0;
 }
Referenced by finalize(), init(), and TEST_CASE().
init()
void sopt::mpi::init (int argc, const char ** argv) inline
Definition at line 27 of file session.cc.
{
   if (finalized()) throw std::runtime_error("MPI session has already been finalized");
   if (not initialized()) {
     assert(details::initializer::singleton.expired());
     std::shared_ptr<details::initializer> ptr(new details::initializer,
                                               &details::initializer::deleter);
 #ifdef SOPT_OPENMP
     int provided;
     if (MPI_Init_thread(&argc, const_cast<char ***>(&argv), MPI_THREAD_FUNNELED, &provided) ==
         MPI_SUCCESS)
 #else
     if (MPI_Init(&argc, const_cast<char ***>(&argv)) == MPI_SUCCESS)
 #endif
       details::initializer::singleton = ptr;
 #ifdef SOPT_OPENMP
     if (provided < MPI_THREAD_FUNNELED) SOPT_THROW("MPI threading support not sufficient.");
 #endif
     return details::initializer::singleton.lock();
   }
   return session_singleton();
 }
References finalized(), initialized(), session_singleton(), and SOPT_THROW.
Referenced by main(), and TEST_CASE().
initialized()
bool sopt::mpi::initialized () inline
Definition at line 61 of file session.cc.
                    {
   int flag;
   auto const error = MPI_Initialized(&flag);
   if (error != MPI_SUCCESS) {
     SOPT_ERROR("Error while calling MPI_Initialized ({})", error);
     throw std::runtime_error("MPI error");
   }
   return static_cast<bool>(flag);
 }
References SOPT_ERROR.
Referenced by finalize(), init(), session_singleton(), and TEST_CASE().
session_singleton()
std::shared_ptr<details::initializer> sopt::mpi::session_singleton ()
Definition at line 50 of file session.cc.
{
   if (not initialized()) throw std::runtime_error("MPI session not initialized");
   if (details::initializer::singleton.expired()) {
     std::shared_ptr<details::initializer> ptr(new details::initializer,
                                               &details::initializer::deleter);
     details::initializer::singleton = ptr;
     return details::initializer::singleton.lock();
   }
   return details::initializer::singleton.lock();
 }
References initialized().
Referenced by init().