SOPT: /mydata/cpp/tests/primal_dual.cc File Reference
primal_dual.cc File Reference
#include <catch.hpp>
#include <random>
#include <assert.h>
#include <Eigen/Dense>
#include "sopt/primal_dual.h"
#include "sopt/proximal.h"
#include "sopt/types.h"
Classes
struct is_primal_dual_ref< T >
Typedefs
typedef sopt::t_real Scalar
typedef sopt::Vector< Scalar > t_Vector
typedef sopt::Matrix< Scalar > t_Matrix
Functions
sopt::t_int random_integer (sopt::t_int min, sopt::t_int max)
TEST_CASE ("Primal Dual, testing norm(output - target()) < l2ball_epsilon()", "[primaldual][integration]")
TEST_CASE ("Check type returned on setting variables")
Variables
auto const N = 5
Typedef Documentation
Scalar
typedef sopt::t_real Scalar
Definition at line 16 of file primal_dual.cc.
t_Matrix
typedef sopt::Matrix<Scalar> t_Matrix
Definition at line 20 of file primal_dual.cc.
t_Vector
typedef sopt::Vector<Scalar> t_Vector
Definition at line 19 of file primal_dual.cc.
Function Documentation
random_integer()
sopt::t_int random_integer (sopt::t_int min, sopt::t_int max)
Definition at line 12 of file primal_dual.cc.
References mersenne().
Referenced by TEST_CASE().
{
   extern std::unique_ptr<std::mt19937_64> mersenne;
   std::uniform_int_distribution<sopt::t_int> uniform_dist(min, max);
   return uniform_dist(*mersenne);
 };
TEST_CASE() [1/2]
TEST_CASE ("Primal Dual)
Definition at line 24 of file primal_dual.cc.
References sopt::epsilon(), mersenne(), N, sopt::positive_quadrant(), sopt::algorithm::PrimalDual< SCALAR >::Psi(), random_integer(), and sopt::target().
{
   using namespace sopt;
   t_Matrix const mId = t_Matrix::Identity(N, N);
   auto const sigma1 = 1.0;
   auto const sigma2 = 1.0;
   t_Vector target = t_Vector::Random(N);
   target = sopt::positive_quadrant(target);
   auto const epsilon = target.stableNorm() / 2;
   auto const primaldual = algorithm::PrimalDual<Scalar>(target)
                               .Phi(mId)
                               .Psi(mId)
                               .itermax(5000)
                               .kappa(0.1)
                               .tau(0.49)
                               .l2ball_epsilon(epsilon)
                               .relative_variation(1e-4)
                               .residual_convergence(epsilon);
   auto const result = primaldual();
   CHECK((result.x - target).stableNorm() <= epsilon);
 }
TEST_CASE() [2/2]
TEST_CASE ("Check type returned on setting variables")
Definition at line 136 of file primal_dual.cc.
References sopt::algorithm::PrimalDual< SCALAR >::is_converged(), sopt::algorithm::PrimalDual< SCALAR >::Phi(), and sopt::algorithm::PrimalDual< SCALAR >::Psi().
{
   // Yeah, could be static asserts
   using namespace sopt;
   using namespace sopt::algorithm;
   PrimalDual<double> pd(Vector<double>::Zero(0));
   CHECK(is_primal_dual_ref<decltype(pd.itermax(500))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.kappa(1))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.relative_variation(5e-4))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.l2ball_epsilon(1e-4))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.residual_convergence(1.001))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.nu(1e0))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.sigma1(1e0))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.sigma2(1e0))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.levels(1))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.positivity_constraint(true))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.l1_proximal_weights(Vector<double>::Zero(0)))>::value);
   typedef ConvergenceFunction<double> ConvFunc;
   CHECK(is_primal_dual_ref<decltype(pd.is_converged(std::declval<ConvFunc>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.is_converged(std::declval<ConvFunc &>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.is_converged(std::declval<ConvFunc &&>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.is_converged(std::declval<ConvFunc const &>()))>::value);
   typedef LinearTransform<Vector<double>> LinTrans;
   CHECK(is_primal_dual_ref<decltype(pd.Phi(linear_transform_identity<double>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Phi(std::declval<LinTrans>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Phi(std::declval<LinTrans &&>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Phi(std::declval<LinTrans &>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Phi(std::declval<LinTrans const &>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Psi(linear_transform_identity<double>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Psi(std::declval<LinTrans>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Psi(std::declval<LinTrans &&>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Psi(std::declval<LinTrans &>()))>::value);
   CHECK(is_primal_dual_ref<decltype(pd.Psi(std::declval<LinTrans const &>()))>::value);
 }
Variable Documentation
N
auto const N = 5
Definition at line 22 of file primal_dual.cc.
Referenced by TEST_CASE().