SOPT: /home/runner/work/sopt/sopt/cpp/tests/tf_inpainting.cc File Reference
tf_inpainting.cc File Reference
#include <algorithm>
#include <exception>
#include <functional>
#include <iostream>
#include <random>
#include <vector>
#include <ctime>
#include <catch.hpp>
#include "sopt/imaging_forward_backward.h"
#include "sopt/tf_g_proximal.h"
#include "sopt/logging.h"
#include "sopt/maths.h"
#include "sopt/relative_variation.h"
#include "sopt/sampling.h"
#include "sopt/types.h"
#include "sopt/utilities.h"
#include "tools_for_tests/directories.h"
#include "tools_for_tests/tiffwrappers.h"
Typedefs
typedef double Scalar
typedef sopt::Vector< Scalar > Vector
typedef sopt::Matrix< Scalar > Matrix
typedef sopt::Image< Scalar > Image
Functions
TEST_CASE ("Inpainting")
Typedef Documentation
Image
typedef sopt::Image<Scalar> Image
Definition at line 29 of file tf_inpainting.cc.
Matrix
typedef sopt::Matrix<Scalar> Matrix
Definition at line 28 of file tf_inpainting.cc.
Scalar
typedef double Scalar
Definition at line 26 of file tf_inpainting.cc.
Vector
typedef sopt::Vector<Scalar> Vector
Definition at line 27 of file tf_inpainting.cc.
Function Documentation
TEST_CASE()
TEST_CASE ("Inpainting")
Definition at line 31 of file tf_inpainting.cc.
{
   extern std::unique_ptr<std::mt19937_64> mersenne;
   std::string const input = "cameraman256";
   std::string const model_path = std::string(sopt::notinstalled::models_directory() + "/DnCNN/snr_15_model.pb/");
   Image const image = sopt::notinstalled::read_standard_tiff(input);
   sopt::t_uint nmeasure = std::floor(0.5 * image.size());
   sopt::LinearTransform<Vector> const sampling =
       sopt::linear_transform<Scalar>(sopt::Sampling(image.size(), nmeasure, *mersenne));
   Vector const y0 = sampling * Vector::Map(image.data(), image.size());
   auto const snr = 30.0;
   auto const sigma = y0.stableNorm() / std::sqrt(y0.size()) * std::pow(10.0, -(snr / 20.0));
   auto const epsilon = std::sqrt(nmeasure + 2 * std::sqrt(y0.size())) * sigma;
   std::normal_distribution<> gaussian_dist(0, sigma);
   Vector y(y0.size());
   for (sopt::t_int i = 0; i < y0.size(); i++) y(i) = y0(i) + gaussian_dist(*mersenne);
   sopt::t_real const gamma = 18;
   sopt::t_real const beta = sigma * sigma * 0.5;
   auto fb = sopt::algorithm::ImagingForwardBackward<Scalar>(y);
   fb.itermax(500)
     .beta(beta)    // stepsize
     .sigma(sigma)  // sigma
     .gamma(gamma)  // regularisation paramater
     .fista(false)  // switch to use FISTA algorithm in Forward Backward algorithm, should be false if using learned TF model
     .relative_variation(1e-3)
     .residual_tolerance(0)
     .tight_frame(true)
     .Phi(sampling);
   // Create a shared pointer to an instance of the TFGProximal class
   auto gp = std::make_shared<sopt::algorithm::TFGProximal<Scalar>>(model_path);
   // Inject it into the ImagingForwardBackward object
   fb.g_proximal(gp);
   auto const diagnostic = fb();
   CHECK(diagnostic.good);
   CHECK(diagnostic.niters < 500);
   // compare input image to cleaned output image
   // calculate mean squared error sum_i ( ( x_true(i) - x_est(i) ) **2 )
   // check this is less than the number of pixels * 0.01
   auto mse = (image - diagnostic.x.array()).square().sum() / image.size();
   CAPTURE(image.size());
   CAPTURE(image.sum());
   CAPTURE(diagnostic.x.array().sum());
   CAPTURE(mse);
   CHECK(mse < 0.01);
 }
References sopt::epsilon(), mersenne(), sopt::notinstalled::models_directory(), sopt::notinstalled::read_standard_tiff(), and sopt::sigma().