SOPT: /home/runner/work/sopt/sopt/cpp/tests/tf_model.cc File Reference
tf_model.cc File Reference
#include <iostream>
#include <vector>
#include <catch2/catch_all.hpp>
#include "sopt/logging.h"
#include "sopt/types.h"
#include "sopt/utilities.h"
#include "sopt/ort_session.h"
#include "tools_for_tests/directories.h"
#include "tools_for_tests/tiffwrappers.h"
Typedefs
using Scalar = double
using Image = sopt::Image< Scalar >
using Vector = sopt::Vector< Scalar >
Functions
TEST_CASE ("Cppflow Model")
Typedef Documentation
Image
using Image = sopt::Image<Scalar>
Definition at line 17 of file tf_model.cc.
Scalar
using Scalar = double
Definition at line 16 of file tf_model.cc.
Vector
using Vector = sopt::Vector<Scalar>
Definition at line 18 of file tf_model.cc.
Function Documentation
TEST_CASE()
TEST_CASE ("Cppflow Model")
Definition at line 21 of file tf_model.cc.
{
   // read in image
   const std::string input_image = "cameraman256";
   const Image image = sopt::tools::read_standard_tiff(input_image);
   const int image_rows = image.rows();
   const int image_cols = image.cols();
   // Read in model
   const std::string path(sopt::tools::models_directory() + "/snr_15_model.onnx");
   sopt::ORTsession model(path);
   // Run model on image
   const Image output_image = model.compute(image);
   // compare input image to cleaned output image
   // calculate mean squared error sum_i ( ( x_true(i) - x_est(i) ) **2 )
   // check this is less than the number of pixels * 0.01
   auto mse = (image - output_image).square().sum() / image.size();
   CAPTURE(mse);
   CHECK(mse < 0.01);
 }
References sopt::ORTsession::compute(), sopt::tools::models_directory(), and sopt::tools::read_standard_tiff().