var searchData=
[
  ['unconstrained_5fl1_5fregularisation_456',['unconstrained_l1_regularisation',['../namespacesopt_1_1objective__functions.html#a121b17bc750fe21815f86cc3d790c3a3',1,'sopt::objective_functions::unconstrained_l1_regularisation(const t_real &amp;gamma, const t_real &amp;sig, const T &amp;y, const sopt::LinearTransform&lt; T &gt; &amp;measurement_operator, const sopt::LinearTransform&lt; T &gt; &amp;wavelet_operator)'],['../namespacesopt_1_1objective__functions.html#a8df7f628fc3eb79b95e541a6dd40e256',1,'sopt::objective_functions::unconstrained_l1_regularisation(const t_real &amp;gamma, const t_real &amp;sig, const T &amp;y, const sopt::OperatorFunction&lt; T &gt; &amp;measurement_operator, const sopt::LinearTransform&lt; T &gt; &amp;wavelet_operator)'],['../namespacesopt_1_1objective__functions.html#a5038115d2ed074e7239812b338d57524',1,'sopt::objective_functions::unconstrained_L1_regularisation(const t_real &amp;gamma, const t_real &amp;sig, const T &amp;y, const sopt::OperatorFunction&lt; T &gt; &amp;measurement_operator, const sopt::LinearTransform&lt; T &gt; &amp;wavelet_operator)']]],
  ['unconstrained_5fregularisation_457',['unconstrained_regularisation',['../namespacesopt_1_1objective__functions.html#a05459b3a0a0e163d2501deca1bf0c4ad',1,'sopt::objective_functions::unconstrained_regularisation(const std::function&lt; t_real(T)&gt; &amp;g, const t_real &amp;sig, const T &amp;y, const sopt::OperatorFunction&lt; T &gt; &amp;measurement_operator)'],['../namespacesopt_1_1objective__functions.html#a0ff3f5cdedb39448a8fba43492413872',1,'sopt::objective_functions::unconstrained_regularisation(const std::function&lt; t_real(T)&gt; &amp;g, const t_real &amp;sig, const T &amp;y, const sopt::LinearTransform&lt; T &gt; &amp;measurement_operator)']]],
  ['underlying_5fvalue_5ftype_458',['underlying_value_type',['../classsopt_1_1details_1_1underlying__value__type.html',1,'sopt::details']]],
  ['underlying_5fvalue_5ftype_3c_20scalar_20_3e_459',['underlying_value_type&lt; SCALAR &gt;',['../classsopt_1_1details_1_1underlying__value__type.html',1,'sopt::details::underlying_value_type&lt; SCALAR &gt;'],['../classsopt_1_1details_1_1underlying__value__type.html',1,'sopt::details::underlying_value_type&lt; Scalar &gt;']]],
  ['underlying_5fvalue_5ftype_3c_20t_20_3e_460',['underlying_value_type&lt; T &gt;',['../classsopt_1_1details_1_1underlying__value__type.html',1,'sopt::details']]],
  ['underlying_5fvalue_5ftype_3c_20t_2c_20false_20_3e_461',['underlying_value_type&lt; T, false &gt;',['../classsopt_1_1details_1_1underlying__value__type_3_01T_00_01false_01_4.html',1,'sopt::details']]],
  ['underlying_5fvalue_5ftype_3c_20t_2c_20true_20_3e_462',['underlying_value_type&lt; T, true &gt;',['../classsopt_1_1details_1_1underlying__value__type_3_01T_00_01true_01_4.html',1,'sopt::details']]],
  ['update_5fdelta_463',['update_delta',['../classsopt_1_1algorithm_1_1Reweighted.html#ac95decb5be98a11646002717ce179150',1,'sopt::algorithm::Reweighted::update_delta(Real delta) const'],['../classsopt_1_1algorithm_1_1Reweighted.html#ac673ff8e4da0195e428561e03f15ce45',1,'sopt::algorithm::Reweighted::update_delta() const'],['../classsopt_1_1algorithm_1_1Reweighted.html#a98ec3ad03f985a4f954dff65a72bc250',1,'sopt::algorithm::Reweighted::update_delta(t_DeltaUpdate const &amp;ud) const']]],
  ['upsample_464',['upsample',['../tests_2wavelets_8cc.html#a6e22f7a3bd26f99b5acf9c2bcac1d085',1,'wavelets.cc']]],
  ['utilities_2ecc_465',['utilities.cc',['../utilities_8cc.html',1,'']]],
  ['utilities_2eh_466',['utilities.h',['../mpi_2utilities_8h.html',1,'(Global Namespace)'],['../utilities_8h.html',1,'(Global Namespace)']]]
];
