var searchData=
[
  ['delayedproximalenveloppefunction',['DelayedProximalEnveloppeFunction',['../da/d6b/classsopt_1_1proximal_1_1details_1_1DelayedProximalEnveloppeFunction.html',1,'sopt::proximal::details']]],
  ['delayedproximalfunction',['DelayedProximalFunction',['../d2/df2/classsopt_1_1proximal_1_1details_1_1DelayedProximalFunction.html',1,'sopt::proximal::details']]],
  ['derived',['Derived',['../d3/d0a/structsopt_1_1details_1_1HasValueType_1_1Derived.html',1,'sopt::details::HasValueType']]],
  ['diagnostic',['Diagnostic',['../d2/d02/structsopt_1_1proximal_1_1L1_1_1Diagnostic.html',1,'sopt::proximal::L1&lt; SCALAR &gt;::Diagnostic'],['../d1/d40/structsopt_1_1algorithm_1_1SDMM_1_1Diagnostic.html',1,'sopt::algorithm::SDMM&lt; SCALAR &gt;::Diagnostic'],['../dd/d32/structsopt_1_1algorithm_1_1PrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::PrimalDual&lt; SCALAR &gt;::Diagnostic'],['../d5/df4/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ImagingForwardBackward&lt; SCALAR &gt;::Diagnostic'],['../d2/dfb/structsopt_1_1ConjugateGradient_1_1Diagnostic.html',1,'sopt::ConjugateGradient::Diagnostic'],['../d4/d13/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ImagingProximalADMM&lt; SCALAR &gt;::Diagnostic'],['../d9/d51/structsopt_1_1algorithm_1_1ForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ForwardBackward&lt; SCALAR &gt;::Diagnostic'],['../d0/d45/structsopt_1_1algorithm_1_1ProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ProximalADMM&lt; SCALAR &gt;::Diagnostic']]],
  ['diagnosticandresult',['DiagnosticAndResult',['../d6/db2/structsopt_1_1algorithm_1_1ForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ForwardBackward&lt; SCALAR &gt;::DiagnosticAndResult'],['../d1/d4c/structsopt_1_1algorithm_1_1SDMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::SDMM&lt; SCALAR &gt;::DiagnosticAndResult'],['../d4/df8/structsopt_1_1algorithm_1_1PowerMethod_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PowerMethod&lt; SCALAR &gt;::DiagnosticAndResult'],['../d7/d96/structsopt_1_1ConjugateGradient_1_1DiagnosticAndResult.html',1,'sopt::ConjugateGradient::DiagnosticAndResult&lt; T &gt;'],['../dc/d61/structsopt_1_1algorithm_1_1PrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PrimalDual&lt; SCALAR &gt;::DiagnosticAndResult'],['../d6/d73/structDummyAlgorithm_1_1DiagnosticAndResult.html',1,'DummyAlgorithm::DiagnosticAndResult'],['../d3/dde/structsopt_1_1proximal_1_1L1_1_1DiagnosticAndResult.html',1,'sopt::proximal::L1&lt; SCALAR &gt;::DiagnosticAndResult'],['../d2/d45/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingForwardBackward&lt; SCALAR &gt;::DiagnosticAndResult'],['../df/db8/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingProximalADMM&lt; SCALAR &gt;::DiagnosticAndResult'],['../d9/dce/structsopt_1_1algorithm_1_1ProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ProximalADMM&lt; SCALAR &gt;::DiagnosticAndResult']]],
  ['diagnosticandresultreg',['DiagnosticAndResultReg',['../db/df3/structsopt_1_1algorithm_1_1JointMAP_1_1DiagnosticAndResultReg.html',1,'sopt::algorithm::JointMAP']]],
  ['directfilter',['DirectFilter',['../d1/d4b/structsopt_1_1wavelets_1_1WaveletData_1_1DirectFilter.html',1,'sopt::wavelets::WaveletData']]],
  ['dummyalgorithm',['DummyAlgorithm',['../dd/d0b/structDummyAlgorithm.html',1,'']]]
];
