var searchData=
[
  ['delayedproximalenveloppefunction_497',['DelayedProximalEnveloppeFunction',['../classsopt_1_1proximal_1_1details_1_1DelayedProximalEnveloppeFunction.html',1,'sopt::proximal::details']]],
  ['delayedproximalfunction_498',['DelayedProximalFunction',['../classsopt_1_1proximal_1_1details_1_1DelayedProximalFunction.html',1,'sopt::proximal::details']]],
  ['derived_499',['Derived',['../structsopt_1_1details_1_1HasValueType_1_1Derived.html',1,'sopt::details::HasValueType']]],
  ['diagnostic_500',['Diagnostic',['../structsopt_1_1algorithm_1_1ImagingPrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::ImagingPrimalDual&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1ProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ProximalADMM&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1SDMM_1_1Diagnostic.html',1,'sopt::algorithm::SDMM&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1TVPrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::TVPrimalDual&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ImagingForwardBackward&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1PrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::PrimalDual&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1proximal_1_1L1_1_1Diagnostic.html',1,'sopt::proximal::L1&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1ConjugateGradient_1_1Diagnostic.html',1,'sopt::ConjugateGradient::Diagnostic'],['../structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ImagingProximalADMM&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1ForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ForwardBackward&lt; SCALAR &gt;::Diagnostic'],['../structsopt_1_1algorithm_1_1L2ForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::L2ForwardBackward&lt; SCALAR &gt;::Diagnostic']]],
  ['diagnosticandresult_501',['DiagnosticAndResult',['../structsopt_1_1ConjugateGradient_1_1DiagnosticAndResult.html',1,'sopt::ConjugateGradient::DiagnosticAndResult&lt; T &gt;'],['../structsopt_1_1algorithm_1_1ForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ForwardBackward&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1SDMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::SDMM&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1ImagingPrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingPrimalDual&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1ProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ProximalADMM&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1TVPrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::TVPrimalDual&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1PowerMethod_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PowerMethod&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1PrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PrimalDual&lt; SCALAR &gt;::DiagnosticAndResult'],['../structDummyAlgorithm_1_1DiagnosticAndResult.html',1,'DummyAlgorithm::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingForwardBackward&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1proximal_1_1L1_1_1DiagnosticAndResult.html',1,'sopt::proximal::L1&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingProximalADMM&lt; SCALAR &gt;::DiagnosticAndResult'],['../structsopt_1_1algorithm_1_1L2ForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::L2ForwardBackward&lt; SCALAR &gt;::DiagnosticAndResult']]],
  ['diagnosticandresultreg_502',['DiagnosticAndResultReg',['../structsopt_1_1algorithm_1_1JointMAP_1_1DiagnosticAndResultReg.html',1,'sopt::algorithm::JointMAP']]],
  ['directfilter_503',['DirectFilter',['../structsopt_1_1wavelets_1_1WaveletData_1_1DirectFilter.html',1,'sopt::wavelets::WaveletData']]],
  ['dummyalgorithm_504',['DummyAlgorithm',['../structDummyAlgorithm.html',1,'']]]
];
