get_filename_component(sopt_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
message(STATUS "Linking to sopt package in ${sopt_CMAKE_DIR}")
set(sopt_INCLUDE_DIR "@ALL_INCLUDE_DIRS@")
if(NOT TARGET libsopt AND EXISTS "${sopt_CMAKE_DIR}/soptCTargets.cmake")
  include("${sopt_CMAKE_DIR}/soptCTargets.cmake")
endif()
if(NOT TARGET sopt AND EXISTS "${sopt_CMAKE_DIR}/soptCPPTargets.cmake")
  include("${sopt_CMAKE_DIR}/soptCPPTargets.cmake")
endif()

unset(sopt_LIBRARIES)
if(TARGET sopt)
  list(APPEND sopt_LIBRARIES sopt)
  set(sopt_CPP_LIBRARY sopt)
endif()
if(TARGET libsopt)
  list(APPEND sopt_LIBRARIES libsopt)
  set(sopt_C_LIBRARY libsopt)
endif()
set(sopt_HAS_MPI @SOPT_MPI@)
