name: Documentation

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    if: github.event.pull_request.draft == false
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  OMP_NUM_THREADS: 2

jobs:
  make-documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out sopt
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev libyaml-cpp-dev doxygen graphviz ccache libeigen3-dev libtiff-dev
          git clone https://github.com/catchorg/Catch2.git -b v3.4.0
          mkdir Catch2/build
          cd Catch2/build
          cmake .. -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${PWD}
          make -j$(nproc --ignore 1)
          make -j$(nproc --ignore 1) install
          cd -

      - name: Build
        run: |
          export CMAKE_PREFIX_PATH=${{github.workspace}}/Catch2/build/lib/cmake:$CMAKE_PREFIX_PATH
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. --fresh -DCMAKE_INSTALL_PREFIX=${PWD} -Ddompi=OFF -Dopenmp=OFF -Ddocs=ON -Donnxrt=ON
          make -j$(nproc --ignore 1)
          make -j$(nproc --ignore 1) install

      - name: Make Docweb
        run: |
          cd build
          make docweb VERBOSE=1

      - name: Deploy to GH pages
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/cpp/docs/html # The folder the action should deploy.
