name: Documentation

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    if: github.event.pull_request.draft == false
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
    
env:
  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_REVISIONS_ENABLED: 1
  OMP_NUM_THREADS: 2
  CONAN_CPU_COUNT: 2

jobs:
  make-documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out sopt
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev libyaml-cpp-dev graphviz

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.59.0

      - name: Install Tensorflow API on Ubuntu
        uses: UCL/install-tensorflow-action@main
        with:
          version: 2.11.0
          os: linux

      - name: Configure
        run: |
          conan install doxygen/1.9.4@#2af713e135f12722e3536808017ba086 --update
          echo "::set-env name=PREV_PATH::$PATH"
          conan install ${{github.workspace}} -if ${{github.workspace}}/build --build missing  -s compiler.libcxx=libstdc++11 -o mpi=off -o openmp=off -o docs=on -o cppflow=on -pr:h=default -pr:b=default

      - name: Build
        run: conan build ${{github.workspace}} -bf ${{github.workspace}}/build

      - name: Make Docweb
        run: |
          export PATH=$PATH:$PREV_PATH
          cd build
          make docweb VERBOSE=1

      - name: Deploy to GH pages
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/cpp/docs/html # The folder the action should deploy.
